refactor: modify frontend url
woowacourse/service-apply pull request #120
Opened 2020-10-05 07:43 UTC by lalize

Closes #116

2020-10-05 08:03 UTC, dks301 requested changes
수고하셨습니다 👍

2020-10-05 08:03 UTC, dks301 commented on frontend/src/api/applicants.js
> +    .post(`${BASE_URL}/register`, {
여기도 이제 `register` 없어도 되지 않나요??

2020-10-05 09:02 UTC, lalize commented on frontend/src/router/index.js
> +    path: "/application-forms/edit",
new / edit 으로 접근하지 않아도 지원서 등록 컴포넌트를 렌더링하기 때문에 제거했습니다.
그리고 일반적으로 children은 중첩된 router-view를 사용할 때 쓴다고 하네요.

2020-10-05 09:06 UTC, lalize commented on frontend/src/api/applicants.js
> +    .post(`${BASE_URL}/register`, {
프론트 페이지 경로 수정 PR이라 백엔드는 따로 논의가 필요할 것 같습니다.

2020-10-05 09:20 UTC, dks301 approved these changes

2020-10-06 07:14 UTC, lowoon approved these changes
수고하셨습니다.
간단한 코멘트 하나 남겼습니다.

2020-10-06 07:14 UTC, lowoon commented on frontend/src/components/RecruitItem.vue
> +    @click="goRegisterApplicant"
page나 view를 붙여 해당 페이지로 이동한다는 의미가 붙으면 조금 더 명확할 것 같아요

2020-10-06 07:23 UTC, woowahan-pjs approved these changes
수고 많으셨습니다. 👍

2020-10-06 07:23 UTC, LTTTTTE commented on frontend/src/api/applicants.js
> +      data: "token",
로그인이 실패해도 가짜 토큰을 주네요
그래서인지 로그인 성공이라는 alert를 띄워줬어요
나중에 한번에 없어지는 .catch들인가요?

2020-10-06 07:24 UTC, lalize commented on frontend/src/api/applicants.js
> +      data: "token",
.catch는 전부 삭제될 예정입니다.

2020-10-06 07:27 UTC, LTTTTTE approved these changes

2020-10-06 07:28 UTC, LTTTTTE commented on frontend/src/api/applicants.js
> +      data: "token",
그렇군요 고생하셨습니다👍🏼

2020-10-06 07:29 UTC, merged