feat(excel): implement excel download
woowacourse/service-apply pull request #121
Opened 2020-10-05 07:57 UTC by ddaaac

resolve #86, #108

2020-10-06 02:10 UTC, dks301 approved these changes
다운로드 기능이 깔끔해졌네요.
회의때 나온 네이밍만 반영하면 될 것 같아요!
수고하셨습니다 👍

2020-10-09 10:07 UTC, hotheadfactory approved these changes
엑셀 파일로 만드는 과정이 신기하네요 :)
Approve 할게요!

2020-10-09 10:07 UTC, hotheadfactory commented on src/main/kotlin/apply/application/ExcelService.kt
> +    fun Boolean.toText(): String {
확장함수 사용 👍

2020-10-11 11:12 UTC, lalize commented on src/main/kotlin/apply/application/ExcelService.kt
> +    fun Boolean.toText(): String {
private을 붙여도 될 것 같아요.

2020-10-12 11:30 UTC, toneyparky approved these changes
수고하셨습니다.

범과 운!

2020-10-12 15:03 UTC, woowahan-pjs requested changes
수고 많으셨습니다. 👍 
리뷰를 반영하면서 실제 테스트를 함께 해 주세요.

2020-10-12 15:03 UTC, woowahan-pjs commented on src/main/kotlin/apply/domain/evaluationtarget/EvaluationAnswers.kt
>  }
느낌을 보세요.

```kotlin
@Embeddable
class EvaluationAnswers(
    answers: List<EvaluationAnswer> = emptyList()
) {
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "evaluation_target_answers")
    private val _answers: MutableList<EvaluationAnswer> = answers.toMutableList()
    val answers: List<EvaluationAnswer>
        get() = _answers

    fun add(evaluationAnswer: EvaluationAnswer) {
        _answers.add(evaluationAnswer)
    }

    fun countTotalScore(): Int {
        return _answers.map { it.score }.sum()
    }

    fun findScoreByEvaluationItemId(evaluationItemId: Long): Int? =
        _answers.find { it.evaluationItemId == evaluationItemId }?.score
}
```

2020-10-12 15:03 UTC, woowahan-pjs commented on src/main/kotlin/apply/utils/ExcelGenerator.kt
> +            sheet.autoSizeColumn(col)
`repeat()`를 찾아보고 그 기능을 사용해 보면 어떨까요?

```suggestion
        repeat(columnSize) {
            sheet.autoSizeColumn(it)
```

2020-10-12 15:42 UTC, ddaaac commented on src/main/kotlin/apply/application/EvaluationTargetResponse.kt
> +        EvaluationAnswerResponse.from(answers)
그러게요... 굳이 왜 빼놨을까요 ㅋㅋ

2020-10-12 15:42 UTC, ddaaac commented on src/main/kotlin/apply/domain/evaluationtarget/EvaluationAnswers.kt
>      fun findScoreByEvaluationItemId(evaluationItemId: Long): Int? =
기본 점수는 도메인이겠군요!

2020-10-12 15:42 UTC, ddaaac commented on src/main/kotlin/apply/domain/evaluationtarget/EvaluationAnswers.kt
>  }
js 코드를 보는 기분이네요.
`answer`는 확실히 보호되겠네요~~

2020-10-12 15:42 UTC, ddaaac commented on src/main/kotlin/apply/utils/ExcelGenerator.kt
> +            sheet.autoSizeColumn(col)
코틀린은 syntax sugar 범벅이네요 ㅋㅋ

2020-10-12 16:38 UTC, woowahan-pjs approved these changes
수고 많으셨습니다. 👍

2020-10-12 16:39 UTC, merged