feat(application): implement the my application api
woowacourse/service-apply pull request #130
Opened 2020-10-07 05:48 UTC by dks301

close #123

2020-10-07 06:43 UTC, lalize requested changes
불러온 모집과 지원서를 조합하여 내가 지원한 모집을 구하는 게 아니라 내가 지원한 모집을 응답하는 API를 만들 수는 없을까요?

2020-10-07 06:43 UTC, lalize commented on frontend/src/views/MyApplications.vue
> +      this.appliedRecruitments = this.findAppliedRecruitments(applicationFormsData, recruitments)
/recruits 를 거치지 않고 내 지원서 보기를 한 경우는 어떻게 될까요?

2020-10-07 06:43 UTC, lalize commented on frontend/src/store/recruitments.js
> +  },
어떤 계산도 하지 않는데 getters를 사용해야할까요?

2020-10-07 06:43 UTC, lalize commented on frontend/src/views/Recruits.vue
> +    this.recruitments = this.$store.getters["recruitments"]
컴포넌트의 상태를 새로 추가하지 않고 mapState를 사용하여 store에 있는 값을 그대로 사용할 수 있겠네요.

2020-10-07 11:38 UTC, ddaaac requested changes
핀의 의견과 동일합니다.
백엔드에서 "내 모집"이라는 정보를 찾아서 주면 develop 브랜치에서 큰 변동사항 없는 코드가 나올 것 같아요.

2020-10-07 12:33 UTC, dks301 commented on frontend/src/views/MyApplications.vue
> +      this.appliedRecruitments = this.findAppliedRecruitments(applicationFormsData, recruitments)
그런 문제가 있었네요 😵

2020-10-07 12:33 UTC, dks301 commented on frontend/src/store/recruitments.js
> +  },
단순히 자바의 getter와 같은 건줄 알았는데 , `Components의 계산된 속성(computed)의 공통 사용 정의`이군요 👍

2020-10-07 15:34 UTC, lalize commented on src/main/kotlin/apply/application/RecruitmentDtos.kt
> +    val isHidden: Boolean,
이 부분은 프론트에서 쓰지 않는 것 같네요!

2020-10-07 16:00 UTC, ddaaac reviewed
약간의 코멘트 남겼습니다~

2020-10-07 16:00 UTC, ddaaac commented on src/test/kotlin/apply/ui/api/RecruitmentRestControllerTest.kt
> +    private lateinit var recruitmentItemService: RecruitmentItemService
개행!

2020-10-08 02:27 UTC, toneyparky approved these changes
회의의 결론대로 진행하도록 하지요~!

우선 지금 상황으로 머지를 한 후에, 나머지를 이슈는 다른 이슈에서 처리하는 방향으로 가죠~!

수고 많았습니다.

2020-10-08 04:08 UTC, dks301 commented on src/main/kotlin/apply/application/RecruitmentDtos.kt
> +    val isHidden: Boolean,
이 부분은 applicationForms에서 가져올 때 수정될 것 같아요 👍

2020-10-08 04:09 UTC, dks301 commented on frontend/src/views/MyApplications.vue
> +      alert("로그인이 필요합니다.")
충돌 해결하는 사람이 처리하면 되겠네요 👍

2020-10-08 04:10 UTC, dks301 commented on src/main/kotlin/apply/application/RecruitmentService.kt
> +        val submittedRecruitments = appliedRecruitments.map { it.recruitmentId to it.submitted }.toMap()
오 저도 이 기능이 이미 있을 것 같긴 했는데 역시 코틀린에는 있었군요...! 👍

2020-10-08 04:10 UTC, dks301 commented on src/main/kotlin/apply/ui/api/ApplicationFormRestController.kt
> +
회의 결과에 따라 다시 수정할 필요가 있을 것 같아서 남겨놓았었습니다 😄

2020-10-08 06:44 UTC, ddaaac commented on frontend/src/views/MyApplications.vue
> +      alert("로그인이 필요합니다.")
이제 처리하면 되겠네요 👍

2020-10-08 06:53 UTC, lowoon approved these changes
수고하셨습니다 👍 
간단한 코멘트 남겼습니다.

2020-10-08 06:53 UTC, lowoon commented on frontend/src/views/MyApplications.vue
> +      alert("로그인이 필요합니다.")
로그인이 필요한 경우와 로그인 정보가 잘못된 경우 2가지가 있을 것 같은데 메시지는 어떻게 되는지 궁금하네요

2020-10-08 06:53 UTC, lowoon commented on src/main/kotlin/apply/ui/api/ApplicationFormRestController.kt
> +
`Controller`들이 모두 `ApiResponse`를 사용하는 것으로 수정해야할 것 같습니다.
`develop`브랜치를 머지하면 conflict가 일어날 거에요

2020-10-08 07:57 UTC, lalize approved these changes
수고하셨습니다 👍

2020-10-08 10:17 UTC, dks301 commented on frontend/src/views/MyApplications.vue
> +      alert("로그인이 필요합니다.")
@lowoon 사용자에게 구체적인 메시지를 알려줄 필요는 없이 `로그인이 필요합니다`라고 하면 될 것 같아요.
보안상 좋지 않을 수 있고, 사용자는 왜 로그인이 안되는지는 관심이 없을 것 같아요 :)

2020-10-08 10:28 UTC, lowoon commented on frontend/src/views/MyApplications.vue
> +      alert("로그인이 필요합니다.")
제 생각인데 다른 서비스 로그인할 때 비밀번호든 아이디든 잘못된 것을 알려줬던 것같아서요.
현재는 어떤 것이 잘못됐는지까지 알려주지 않아도 되지만 사용자도 어떤게 잘못된 건지 알아야할 것 같아서요

2020-10-08 10:43 UTC, dks301 commented on frontend/src/views/MyApplications.vue
> +      alert("로그인이 필요합니다.")
이 부분은 토큰이 유효하지 않을 경우(ex.토큰 만료) 로그인 페이지로 이동하는 부분이라고 생각해서 이렇게 구현했습니다 😄
아이디와 비밀번호 중 어느 것이 잘못됐는지는 로그인 페이지에서는 알려줄거에요!

2020-10-09 01:22 UTC, ddaaac reviewed
api가 확정이 되었으니 이에 맞게 수정하면 될 것 같네요.

몇가지 수정사항 남겼습니다.

2020-10-09 01:22 UTC, ddaaac commented on frontend/src/views/MyApplications.vue
> -  },
이 메서드가 살아나겠군요

2020-10-09 01:22 UTC, ddaaac commented on frontend/src/views/MyApplications.vue
> -      })
여기서 `fetchMeyRecruitments(token)`은 빠지겠네요. 그리고 `recruitmentData` 대신에 지금은 mock 데이터를 넣어두면 될 것 같아요.

2020-10-09 13:21 UTC, ddaaac approved these changes
잘 작동하는 거 확인했습니다!

고생하셨어요~

2020-10-11 11:52 UTC, woowahan-pjs approved these changes
수고 많으셨습니다. 👍

2020-10-11 11:53 UTC, merged