feat(application): submit only one application form
woowacourse/service-apply pull request #181
Opened 2020-10-15 10:18 UTC by lalize

Close #178

2020-10-15 10:35 UTC, ddaaac requested changes
코멘트 남겼어요!

2020-10-15 10:35 UTC, ddaaac commented on src/main/kotlin/apply/application/ApplicationFormService.kt
>          applicationFormRepository.save(applicationForm)
궁금한데 혹시 여기서는 더티체킹이 작동하나요?

2020-10-15 10:35 UTC, ddaaac commented on src/test/kotlin/apply/application/ApplicationFormServiceTest.kt
> +        every { applicationFormRepository.existsByApplicantIdAndSubmittedTrue(any()) } returns true
지금처럼 리턴값이 true라면 이미 제출한 지원서가 존재한다는 건데 예외를 던져야하지 않나요? 😊

제 생각엔 `UpdateApplicationFormRequest`의 `isSubmitted` 값이 false라 테스트를 통과하는 것 같아요!

2020-10-15 13:22 UTC, lalize commented on src/main/kotlin/apply/application/ApplicationFormService.kt
>          applicationFormRepository.save(applicationForm)
더티 체킹 작동 하네요. 같이 수정했습니다~

2020-10-15 13:24 UTC, lalize commented on src/test/kotlin/apply/application/ApplicationFormServiceTest.kt
> +        every { applicationFormRepository.existsByApplicantIdAndSubmittedTrue(any()) } returns true
맞아요! 예외를 테스트 해야 하는 데 뭘 테스트 하려고 했던 것일까요...

2020-10-15 22:39 UTC, woowahan-pjs approved these changes
수고 많으셨습니다. 👍

2020-10-16 02:17 UTC, ddaaac approved these changes
고생하셨습니다~

2020-10-16 02:48 UTC, dks301 reviewed
수고하셨습니다 👍 
간단한 코멘트 남겼으니 확인부탁해요 :)

2020-10-16 02:48 UTC, dks301 commented on src/main/kotlin/apply/application/ApplicationFormService.kt
> +            require(!applicationFormRepository.existsByApplicantIdAndSubmittedTrue(applicantId)) {
```suggestion
require(applicationFormRepository.existsByApplicantIdAndSubmittedFalse(applicantId)) {
```
개인적으로 ! 연산 보다는 바로 사용하는게 읽기 좋다고 생각하는데 취향이니 참고만해주세요 :)

2020-10-16 02:48 UTC, dks301 commented on src/main/kotlin/apply/application/ApplicationFormService.kt
>          if (request.isSubmitted) {
백엔드에서 Boolean 변수는 submitted 와 같이 사용하기로 했었던 것 같은데 수정이 안되어있네요
이 부분도 같이 수정해주시면 좋을 것 같아요 👍

2020-10-16 02:48 UTC, dks301 commented on src/test/kotlin/apply/domain/applicationform/ApplicationFormRepositoryTest.kt
> +                mutableListOf(
`ApplicationFormFixtures`가 이미 있으니 가져다 쓰던가 없다면 만들어서 사용하면 좋겠네요!

2020-10-16 02:53 UTC, LTTTTTE approved these changes
고생하셨습니다👍🏼

2020-10-16 03:05 UTC, lalize commented on src/main/kotlin/apply/application/ApplicationFormService.kt
> +            require(!applicationFormRepository.existsByApplicantIdAndSubmittedTrue(applicantId)) {
제안 해주신 쿼리 메소드는 제출하지 않는 지원서가 하나라도 존재하면 `true`이기 때문에 모든 지원서를 제출할 수 있어요.

2020-10-16 04:20 UTC, dks301 commented on src/main/kotlin/apply/application/ApplicationFormService.kt
> +            require(!applicationFormRepository.existsByApplicantIdAndSubmittedTrue(applicantId)) {
그렇네요...! 제가 말한대로 기능하려면 `notExistsByApplicantIdAndSubmittedTrue`가 필요하겠네요 😅
지금 그대로 사용해야겠네요 👍

2020-10-16 04:22 UTC, dks301 approved these changes
수고하셨습니다 👍

2020-10-16 05:38 UTC, merged