refactor(test): migrate Mockito to Mockk
woowacourse/service-apply pull request #251
Opened 2021-07-03 13:33 UTC by knae11

Close #63

2021-07-03 13:49 UTC, ecsimsw commented
ApplicationRestControllerTest, '잘못된 비밀번호 변경 요청에 응답으로 Unauthorized를 반환한다' 테스트의 기댓값을 수정하였습니다.

잘못된 비밀번호로 비밀번호 변경을 요청할 경우, 기존의 코드에선 응답 코드가 NoContent 를 확인하였으나,
비밀번호 불일치로 예외가 발생하는 경우, 응답의 상태 코드로 Unauthorized 임을 확인하는 것이 적절하다고 판단되어 응답 코드의 기댓값 자체를 수정하였습니다.

```
// 수정 전
mockMvc.post("/api/applicants/edit-password") {
    content = objectMapper.writeValueAsBytes(inValidEditPasswordRequest)
    contentType = MediaType.APPLICATION_JSON
    header(AUTHORIZATION, "Bearer valid_token")
}.andExpect {
    status { isNoContent }
}
```

```
// 수정 후
mockMvc.post("/api/applicants/edit-password") {
    content = objectMapper.writeValueAsString(inValidEditPasswordRequest)
    contentType = MediaType.APPLICATION_JSON
    header(AUTHORIZATION, "Bearer valid_token")
}.andExpect {
    status { isUnauthorized }
}
```

2021-07-03 13:53 UTC, knae11 commented
Mockito에서 Mockk 전환시 참고할만한 작은 팁

# Mockito → Mockk

- `@Mock` → `@MockK`
- anyLong() →  ofType(Long::class)
- given → every {}
- `@MockBean` → `@MockkBean`
- willReturn() → returns 또는 answers { }

# 객체비교

- Mock 테스트 대상의 인자 값으로 객체를 넣을 경우 객체비교가 필요(이때 주소가 다르면 다른 객체로 인식)
- 동등성으로 객체 비교
    - eq() : 객체를 deepEquals 비교
    - 

# Return Void

- willDoNothing()은 Void 리턴으로 대체가능

[https://notwoods.github.io/mockk-guidebook/docs/tips/unit/](https://notwoods.github.io/mockk-guidebook/docs/tips/unit/)

```kotlin
every { evaluationRepository.deleteById(ofType(Long::class)) } returns Unit
every { evaluationRepository.deleteById(ofType(Long::class)) } just Runs
```

2021-07-03 13:56 UTC, knae11 commented
# ApplicationRestController 암호화 사용시 테스트 문제발생

```kotlin
    @Test
    fun `잘못된 비밀번호 변경 요청에 응답으로 Unauthorized를 반환한다`() {
        every { jwtTokenProvider.isValidToken("valid_token") } answers { true }
        every { jwtTokenProvider.getSubject("valid_token") } answers { applicantRequest.email }
        every { applicantService.getByEmail(applicantRequest.email) } answers { applicantRequest.toEntity() }
        every {
            applicantService.editPassword(ofType(Long::class), eq(inValidEditPasswordRequest))
        } throws ApplicantAuthenticationException()

        val inValidEditPasswordRequest: HashMap<String, String> = createInValidEditPasswordRequest()

        mockMvc.post("/api/applicants/edit-password") {
            content = objectMapper.writeValueAsString(inValidEditPasswordRequest) // -> 재생성 필요
            contentType = MediaType.APPLICATION_JSON
            header(AUTHORIZATION, "Bearer valid_token")
        }.andExpect {
            status { isUnauthorized }
        }
    }

    private fun createInValidEditPasswordRequest(): HashMap<String, String> {
        val inValidEditPasswordRequest: HashMap<String, String> = HashMap()
        inValidEditPasswordRequest["password"] = WRONG_PASSWORD
        inValidEditPasswordRequest["newPassword"] = NEW_PASSWORD
        return inValidEditPasswordRequest
    }
```

- Password 객체가 사용되는 inValidEditPasswordRequest는 만들어질때 sha-256으로 암호화가 됨
- objectMapper로 request를 만들 때, 기존에 작성해둔 `private val inValidEditPasswordRequest = validEditPasswordRequest.copy(password = Password(WRONG_PASSWORD))` 를 사용하면 암호화된 내용이 또 암호화가 진행되어 내부 값이 달라짐
- 예시)

    ```kotlin
    inValidEditPasswordRequest // wrongPassword(text) → 4e12(암호화)
    objectMapper.writeValueAsString(inValidEditPasswordRequest) 
    // 컨트롤러와 매핑하기 위한 json -> Object 변환과정에서 값으로 4e12(기존 암호화된 값)가 들어와서 이것이 암호화 됨
    // 4e12를 비교하기 원하나 새로운 암호값인 9rw1(암호화)가 되어 eq()비교에도 다른 값으로 인식해 Mock 설정 값을 거치치 않음
    ```

- 새롭게 key-value 형태의 문자 값으로 다시 객체를 만들어(`createInValidEditPasswordRequest()`) 이것을 json → Object 작업을 통해 암호화가 이루어져야 내부 값이 같음을 비교가능

2021-07-14 00:53 UTC, NewWisdom requested changes
굳굳 ~~!!!
이슈에 남겨준 mockk 정리 덕분에 저희도 이번에 컨트롤러 테스트 짜는데 수월하게 적용할 수 있었습니다!!! 
정리 너무 감사합니다 짱짱맨 🙇‍♂️🙇‍♂️
수고 많으셨어요 배럴 코기 👏👏👏

2021-07-14 00:53 UTC, NewWisdom commented on src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt
> +        val inValidEditPasswordRequest: HashMap<String, String> = createInValidEditPasswordRequest()
이슈에 남긴 문제로 `createInValidEditPasswordRequest()`를 쓰고 있는 것 확인했습니다!
그런데 여기는 올바른 비번 요청이니까 `validEditPasswordRequest`가 와야하지 않을까요??

2021-07-14 00:53 UTC, NewWisdom commented on src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt
> +            status { isUnauthorized }
굳굳👏👏👏

2021-07-14 00:53 UTC, NewWisdom commented on src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt
> +            content = objectMapper.writeValueAsString(inValidEditPasswordRequest)
여기만 `writeValueAsString()`으로 바꿔준 이유가 있나요??
개인적인 궁금함입니다 ㅎㅎㅎ

2021-07-14 07:31 UTC, woowahan-pjs requested changes
Mockito를 실수로 사용하지 않도록 Gradle 빌드 스크립트에 `exclude(group = "org.mockito")`를 추가하면 어떨까요?

```kts
testImplementation("org.springframework.boot:spring-boot-starter-test") {
    exclude(group = "org.junit.vintage", module = "junit-vintage-engine")
    exclude(group = "org.mockito")
}
```

2021-07-14 07:31 UTC, woowahan-pjs commented on src/test/kotlin/apply/application/CheaterServiceTest.kt
> +        every { cheaterRepository.existsByApplicantId(ofType(Long::class)) } answers { false }
`any()`로 충분해 보이고 필요하다면 `any<Long>()`을 사용하면 어떨까요?

```suggestion
        every { cheaterRepository.existsByApplicantId(any()) } answers { false }
```

2021-07-14 07:31 UTC, woowahan-pjs commented on src/test/kotlin/apply/application/EvaluationServiceTest.kt
> +
정적 분석 검사를 통과하지 않아요. (`./gradlew clean check`)

```suggestion

```

2021-07-14 07:31 UTC, woowahan-pjs commented on src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt
> +        val inValidEditPasswordRequest: HashMap<String, String> = createInValidEditPasswordRequest()
테스트 조건인 `inValidEditPasswordRequest`와 로컬 변수 `inValidEditPasswordRequest`의 이름은 다르게 지으면 어떨까요? 그리고 `HashMap` 대신 코틀린 컬렉션을 사용해 주세요.

2021-07-14 07:31 UTC, woowahan-pjs commented on src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt
> +    }
```suggestion
    private fun createInValidEditPasswordRequest(): Map<String, String> {
        return mapOf(
            "password" to WRONG_PASSWORD,
            "newPassword" to NEW_PASSWORD
        )
    }
```

2021-07-14 13:24 UTC, ddaaac commented on src/test/kotlin/apply/application/CheaterServiceTest.kt
> +        every { cheaterRepository.existsByApplicantId(ofType(Long::class)) } answers { false }
return 대신 answer를 쓰신 이유가 있을까요? [이 스레드](https://stackoverflow.com/a/36627077)를 읽고 생각해보는 것도 좋을 것 같아요.

2021-07-14 21:57 UTC, knae11 commented on src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt
> +    }
수정하였습니다!

2021-07-14 22:00 UTC, knae11 commented on src/test/kotlin/apply/application/EvaluationServiceTest.kt
> +
정적 분석 검사로 코드 포맷팅 다시 맞추었습니다! 😅

2021-07-14 22:06 UTC, knae11 commented on src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt
> +        val inValidEditPasswordRequest: HashMap<String, String> = createInValidEditPasswordRequest()
수정하면서 해당 내용 놓친 것 같아요! 감사합니다! `validEditPasswordRequest`로 수정하였어요! :)

2021-07-15 11:48 UTC, knae11 commented on src/test/kotlin/apply/application/CheaterServiceTest.kt
> +        every { cheaterRepository.existsByApplicantId(ofType(Long::class)) } answers { false }
any() 로 수정할게요! :)

2021-07-15 11:48 UTC, knae11 commented on src/test/kotlin/apply/application/CheaterServiceTest.kt
> +        every { cheaterRepository.existsByApplicantId(ofType(Long::class)) } answers { false }
returns 를 사용하는게 더 알맞겠네요! :) 둘의 차이가 뭘까 고민스러운 점이 많았는데 리뷰를 받고 그 차이점에 대해 좀 더 알게 된 것 같아요 :)

2021-07-15 11:48 UTC, knae11 commented on src/test/kotlin/apply/application/CheaterServiceTest.kt
> +        every { cheaterRepository.existsByApplicantId(ofType(Long::class)) } answers { false }
단순 값 반환은 returns로 수정하였어요

2021-07-15 11:57 UTC, knae11 commented on src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt
> +            content = objectMapper.writeValueAsString(inValidEditPasswordRequest)
아마 뭔가 안되서 이것저것 테스트하다가 남은것 같아요..ㅎㅎ 별 의미는 없었네요 혼란을 드려 죄송해요~ 수정하였습니다!ㅎㅎㅎ

2021-07-15 12:01 UTC, knae11 commented on src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt
> +        val inValidEditPasswordRequest: HashMap<String, String> = createInValidEditPasswordRequest()
`actualInValidEditPasswordRequest` 형식으로 actual로 실제 테스트 요청을 구분해주었습니다. 어떨까요? 혹시 다른 추천하는 변수명이 있다면 제안해주세요 :)

2021-07-15 12:07 UTC, ddaaac approved these changes
고생하셨습니당~

2021-07-16 00:12 UTC, woowahan-pjs approved these changes
고생하였어요. 👍

2021-07-16 00:14 UTC, merged