feat: add HTTP API
woowacourse/service-apply pull request #253
Opened 2021-07-07 00:02 UTC by Rok93

Close #249

2021-07-07 00:18 UTC, NewWisdom commented
[로키 아마찌 작업 일지](https://www.notion.so/newwisdom/07-03-a6985d53cab843869df5742090bc5e74)는 함께 노션에 정리했습니다.

2021-07-07 00:33 UTC, NewWisdom commented
## 공통 논의 사항
### 응답 코드에 대한 고찰

```kotlin
@PostMapping
fun save(@RequestParam("applicantId")applicantId: Long): ResponseEntity<Unit> {
    cheaterService.save(applicantId)
    return ResponseEntity.ok().build()
}
```

Post 요청 —> CREATED (201 응답) 

DELETE 요청 —> NO_CONTENT(204응답) 인걸로 아는데, 뒤죽박죽인 상황. 

통일성이 필요해보임! 

`이거 다음 작업으로 추천!`  (지금 상황에서 병행은 불가!)

### Create, Delete 기능에 대한 테스트 코드 (= 반환 값이 없는 테스트)

현재 아래와 같다. (사실 applicant는 필요도 없음) 해당 테스트가 정말 의미가 있을까? 

```kotlin
    @Test
    internal fun `부정행위자를 추가한다`() {
        val applicant = createApplicant(id = 1L, name = "로키")

        mockMvc.post("/api/cheaters") {
            param("applicantId", applicant.id.toString())
        }
            .andExpect {
                status { isOk }
            }
    }
```

- Dto가 아닌 Entity를  바로 API로 노출해도 괜찮은가? (EvaluationService 부분의 문제)

대표적으로 아래의 함수들은 기존에도 외부로 노출되고 있다. (Vaddin과 조합되어서)

### URL 매핑
* 한 컨트롤러에서 유사한 반환 값(?)을 가지는 경우
* 한 컨트롤러에서 URL 설계 시 pathVariable이 겹치는 문제


### (번외)
* Excel 파일 다운로드 API 테스트 작성법 
* [ExcelService 작업 내용](https://www.notion.so/newwisdom/5d2a9ec66ede4507a7dff5fa9b936697#f4f77292734949fea6742279c91a86ca)

2021-07-13 13:46 UTC, knae11 requested changes
아마찌 내용은 저번에 확인했고, 로키부분에서 하나 누락된 것 같아서 피드백 남겨요~ㅎㅎㅎ
두분 다 엄청 고생하셨어요!ㅎㅎㅎ

추가) 혹시 `ExcelRestController` -> `ExcelController`로 수정하는건 어떨까요? :)

2021-07-13 13:46 UTC, knae11 commented on src/main/kotlin/apply/ui/api/EvaluationRestController.kt
> +    @GetMapping("{evaluationId}")
```suggestion
    @GetMapping("/{evaluationId}")
```
`/`가 누락된 것 같은데 혹시 누락되어도 매핑이 잘 될까요?!ㅎㅎㅎ

2021-07-14 05:53 UTC, woowahan-pjs requested changes
첫 PR이네요! 고생하였어요. 👍 
테스트 코드는 따로 리뷰하지 않고 코드의 일관성을 리뷰하였습니다.

2021-07-14 05:53 UTC, woowahan-pjs commented on build.gradle.kts
> +    id("org.asciidoctor.convert") version "1.5.9.2"
`org.asciidoctor.convert` 대신 `org.asciidoctor.jvm.convert`로 변경되었습니다. Spring REST Docs 문서에서는 아직 언급이 안 되었으니 참고만 해 주세요. 참고로 `org.asciidoctor.convert`는 2.4.0이 최신 버전입니다.
https://asciidoctor.github.io/asciidoctor-gradle-plugin/master/user-guide

2021-07-14 05:53 UTC, woowahan-pjs commented on build.gradle.kts
> +    testImplementation("org.springframework.restdocs:spring-restdocs-mockmvc:2.0.5.RELEASE")
스프링 부트가 버전을 관리하는 모듈입니다. 버전을 선언한 이유가 있나요?
https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html

2021-07-14 05:53 UTC, woowahan-pjs commented on build.gradle.kts
> +val snippetsDir by extra { file("build/generated-snippets") }
```suggestion
}

val snippetsDir by extra { file("build/generated-snippets") }
```

2021-07-14 05:53 UTC, woowahan-pjs commented on build.gradle.kts
> +    bootJar {
```suggestion
    }
    asciidoctor {
        inputs.dir(snippetsDir)
        dependsOn(test)
    }
    bootJar {
```

2021-07-14 05:53 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationService.kt
> +    private val recruitmentRepository: RecruitmentRepository,
후행 쉼표(trailing comma)를 사용하기로 하였군요.

2021-07-14 05:53 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationService.kt
> +    fun deleteById(evaluationId: Long) {
`findById()`의 매개 변수 이름은 `id`인데 `deleteById()`의 매개 변수 이름을 `evaluationId`로 바꾼 이유가 있나요?

2021-07-14 05:53 UTC, woowahan-pjs commented on src/main/kotlin/apply/ui/api/ApplicantRestController.kt
> +    @GetMapping("/{keyword}/recruitments/{recruitmentId}")
특정 모집의 제출된 지원서 중 지원자의 이름 또는 이메일로 지원서 목록을 조회하네요. `/api/recruitments/{recruitmentId}/application-forms?keyword=` 혹은 `applicant=`, `applicantKeyword=`는 어떠세요?

2021-07-14 05:53 UTC, woowahan-pjs commented on src/main/kotlin/apply/ui/api/ApplicantRestController.kt
> +    ): ResponseEntity<ApiResponse<List<ApplicantAndFormResponse>>> {
봉투 패턴(envelope pattern)에 대해서는 다음에 논의해 보시죠.

2021-07-14 05:53 UTC, woowahan-pjs commented on src/main/kotlin/apply/ui/api/EvaluationRestController.kt
> +
```suggestion

```

2021-07-14 05:53 UTC, woowahan-pjs commented on src/main/kotlin/apply/ui/api/EvaluationRestController.kt
> +        evaluationService.save(evaluationData)
나중에 `recruitmentId`도 인자로 전달할 수 있다는 점을 고려해야겠네요.

2021-07-14 05:53 UTC, woowahan-pjs commented on src/test/kotlin/apply/config/RestDocsConfiguration.kt
> +            configurer.operationPreprocessors()
```suggestion
        return RestDocsMockMvcConfigurationCustomizer {
            it.operationPreprocessors()
```

2021-07-14 05:53 UTC, woowahan-pjs commented on src/test/kotlin/apply/ui/api/CheaterRestControllerTest.kt
> +
```suggestion

```

2021-07-14 11:05 UTC, Rok93 commented on src/main/kotlin/apply/ui/api/EvaluationRestController.kt
> +    @GetMapping("{evaluationId}")
헉.....👀 바로 고쳤습니다!! 
Rest는 일단 keep하기로 한 것 같지만... 🤔이야기가 다시 나온김에 `Rest`는 지웠습니다. 😃

2021-07-14 11:32 UTC, Rok93 commented on build.gradle.kts
> +    id("org.asciidoctor.convert") version "1.5.9.2"
이 부분은 일단 그대로 두는걸로 하겠습니다! 😃

2021-07-14 11:32 UTC, Rok93 commented on build.gradle.kts
> +    testImplementation("org.springframework.restdocs:spring-restdocs-mockmvc:2.0.5.RELEASE")
rest-docs를 도입하는 과정에서 참고한 자료에서 그대로 복붙해서 가져왔다가 버전 지우는걸 깜빡했습니다 🥲

2021-07-14 11:36 UTC, Rok93 commented on src/main/kotlin/apply/application/EvaluationService.kt
> +    private val recruitmentRepository: RecruitmentRepository,
제 IDE에서 `Reformat code`을 실행하면 자동으로 '후행 쉼표'를 찍도록 설정이 되어있네요 😅 
'후행 쉼표'의 사용 여부에 대해서 따로 언급한 적이 없기 때문에 제거하겠습니다.

2021-07-14 12:04 UTC, lalize approved these changes
수고 많으셨습니다~ 앞으로도 잘 부탁드려요!

2021-07-14 12:04 UTC, lalize commented on src/test/kotlin/apply/ui/api/EvaluationTargetControllerTest.kt
> +        mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext)
문서화를 위한 테스트로 보이네요. mockMvc 설정이 다른 문서화 테스트에서도 공통적으로 쓰일 것 같은데요.  추상 클래스를 사용하거나해서 문서화를 위한 컨트롤러 테스트 공통 코드를 빼낼 수 있지 않을까요?

2021-07-14 13:14 UTC, ddaaac reviewed
고생의 흔적이 많이 보이네요 😀

수고 정말 많으셨고, 코멘트 한 번씩 확인 부탁드려요!

2021-07-14 13:14 UTC, ddaaac commented on src/test/kotlin/apply/ui/api/CheaterRestControllerTest.kt
> +    private lateinit var applicantService: ApplicantService // todo: 이 객체를 MockBean으로 주입해야하는 이유 찾기
혹시 답을 찾으셨을 수도 있지만 히스토리 차원에서 코멘트 남길게요.


1. `@WebMvcTest`는 [특정한 빈](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.testing.spring-boot-applications.spring-mvc-tests)들만 불러옵니다. 그 특정한 빈 중에는 `WebMvcConfigurer`의 구현체들도 포함이 됩니다.
1. `AuthenticationConfig` 클래스는 `WebMvcConfigurer`의 구현체입니다. 그래서 빈으로 등록하려고 하겠죠. (그래서 필터에 달린 코드 `ComponentScan.Filter(type = FilterType.REGEX, pattern = ["apply.config.*"])`는 빼도 잘 돌아갑니다. 맨 처음에 제가 잘못 만든 레거시 같은데 여기까지 왔군요 🥲 ) 
1. 이 때, 주입받은 `LoginApplicantResolver` 클래스를 빈으로 등록 및 생성하려고 시도합니다. 
1. `LoginApplicantResolver`는 `apply.security` 폴더 내부에 있습니다. `@WebMvcTest::includeFilters`에 이 폴더가 포함되어있고, `LoginApplicantResolver`는 `@Component`이기 때문에 역시 빈으로 등록하려고 시도하고 의존성을 갖고 있는 `JwtTokenProvider`와 `ApplicantService` 역시 생성하려고 합니다.
1. 여기서 `JwtTokenProvider`는 `apply.security` 폴더에 있고 따로 의존성이 없기 때문에 생성과 등록이 잘 되지만 `ApplicantService`는 `@WebMvcTest`의 스캔 범위를 벗어난 `@Service`라서 빈 생성 에러가 납니다. 그래서 `@MockkBean`으로 등록해줘야해요.

------

여기까지가 이유였고, 제가 남기고 싶은 코멘트는 꼭 `@WebMvcTest`를 써야할까 입니다(사실 이것도 이 프로젝트에 제일 먼저 사용한 건 저였던거 같아요 🥲). 컨트롤러 테스트는 결국 문서화 목적이고 가벼울수록 좋습니다. 컨텍스트를 불러오고 빈을 생성하고 하는 과정이 불필요하다고 느껴지더라구요. 그래서 `@WebMvcTest`를 모두 걷어내고 문서화코드를 한번 정리하는 건 어떨까 하는 생각이 드네요.
작은 이슈는 아닐 것 같아서, 따로 이슈를 파고 다음에 진행해봐도 괜찮을 것 같아요. 😄

2021-07-14 13:14 UTC, ddaaac commented on src/test/kotlin/apply/ui/api/EvaluationRestControllerTest.kt
> +@ExtendWith(RestDocumentationExtension::class, SpringExtension::class)
```suggestion
    includeFilters = [
        ComponentScan.Filter(type = FilterType.REGEX, pattern = ["apply.security.*"]),
    ]
)
@Import(RestDocsConfiguration::class)
@ExtendWith(RestDocumentationExtension::class)
```

SpringExtension을 붙인 이유가 있을까요?

2021-07-14 13:14 UTC, ddaaac commented on src/test/kotlin/apply/ui/api/EvaluationTargetControllerTest.kt
> +        ).andExpect(status().isOk)
다른 클래스들에서는 `mockMvc.get()`과 같은 MockMvcDsl을 사용하고 있는데, 여기는 자바 스타일이네요. 포멧을 통일하면 좋을 것 같아요

2021-07-14 13:14 UTC, ddaaac commented on src/test/kotlin/apply/ui/api/EvaluationTargetControllerTest.kt
> +                    getDocumentResponse(),
RestDocsConfiguration이라는 Configuration이 있는데 직접하는 요청/응답을 처리하는 코드도 있네요. 아마도 이것저것 시도해보다가 지우는걸 놓친것 같아요

2021-07-14 13:34 UTC, Rok93 commented on src/main/kotlin/apply/application/EvaluationService.kt
> +    fun deleteById(evaluationId: Long) {
`deleteById()`를 실제로 호출하는 위치(= EvaluationRestController)에는 여러 자원의 id를 사용해서 명시적으로 어떤 자원의 id인지 명시하지 않으면 오해의 여지가 있다고 생각해서 Controller단에서 명시를 했던게 Service단까지 그대로 이어진 것 같아요 😅 
다른 메서드들과 통일성 맞춰서 `id`로 변경했습니다 😃

2021-07-14 13:38 UTC, woowahan-pjs commented on src/main/kotlin/apply/ui/api/ApplicantRestController.kt
> +        @PathVariable("recruitmentId", required = true) recruitmentId: Long
`Long`이기 때문에 `required = true`도 필요 없을 거예요.

2021-07-14 13:49 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationService.kt
> +    private val recruitmentRepository: RecruitmentRepository,
아쉽게도 ktlint가 아직 지원하지 않네요.
`https://github.com/pinterest/ktlint/issues/709`

2021-07-14 14:01 UTC, Rok93 commented on build.gradle.kts
> +    id("org.asciidoctor.convert") version "1.5.9.2"
`org.asciidoctor.convert`을 최신버전(2.4.0)으로 변경했습니다. 😃

2021-07-14 14:21 UTC, knae11 approved these changes

2021-07-14 14:32 UTC, Rok93 commented on src/main/kotlin/apply/ui/api/ApplicantRestController.kt
> +    @GetMapping("/{keyword}/recruitments/{recruitmentId}")
두 분의 의견과 같이 keyword를 쿼리 파라미터로 받는 것은 좋다고 생각합니다. 
해당 api는 지원자와 지원서를 포함한 데이터를 반환하는 것이 맞아서 URI에 정보가 포함되는게 맞지 않나...? 싶기도하고 제이슨이 제안한 URI 방식도 괜찮은 것 같고 갈팡질팡하네요 🙄 
이 부분은 페어와 논의를 좀 해보겠습니다!  🤔

2021-07-14 15:36 UTC, NewWisdom commented on src/main/kotlin/apply/ui/api/ApplicantRestController.kt
> +    @GetMapping("/{keyword}/recruitments/{recruitmentId}")
keyword는 쿼리 파람으로 받는 것이 좋다고 생각합니다!! 
저도 두분의 의견을 듣고 조금 고민을 해보았는데요,
그러다 현재 해당 컨트롤러에서 서비스 `findAllByRecruitmentIdAndKeyword()`의 쓰임새(SelectionView)를 살펴보니까 
지원서 목록 조회보다는 지원자에 대한 정보를 조회하고 부수적으로 지원서의 정보를 이용하는데 사용하는 것 같아서
`/api/applicants`로 시작하는것이 더 명확할수도 있겠다는 생각이 드는데 어떠신가요.????
(이렇게 되면 recruitmentId랑 keyword를 쿼리 파람으로 받게 될 것 같구요)

혹시 제가 잘못 이해한 부분이라면 말씀 부탁드립니다 ㅎㅎㅎㅎ

2021-07-14 17:00 UTC, NewWisdom commented on src/main/kotlin/apply/ui/api/CheaterRestController.kt
> +    fun save(@RequestParam("applicantId") applicantId: Long): ResponseEntity<Unit> {
처음에는 다른 곳과 같이 path variable을 사용할까 하다가  
POST "/api/cheaters/{id}"면 `cheater에 종속된 식별자로 저장한다`로 오해할 수 있겠다고 생각했습니다.
그래서 `applicantId `를 명시하는 의미로 쿼리파라미터를 사용했는데 URI를 좀 수정하는 방안이 좋을까요???

2021-07-14 17:12 UTC, NewWisdom commented on src/test/kotlin/apply/ui/api/EvaluationTargetControllerTest.kt
> +        ).andExpect(status().isOk)
dsl 스타일을 사용하고 싶었는데, 
문서화를 진행한 컨트롤러는 document에 `pathParameters()`를 포함하기 위해 
RestDocumentationRequestBuilder를 사용하여야 했습니다. 
그런데 이를 사용할 경우 dsl 스타일로 작성하는 방법을 찾지 못했습니다 🥲
일단 문서에 pathParameters를 명시하기위해 자바스타일로 갔는데 방법을 좀 더 찾아보겠습니다!!!

2021-07-14 17:15 UTC, MyaGya commented on src/main/kotlin/apply/ui/api/ApplicantRestController.kt
> +    @GetMapping("/{keyword}/recruitments/{recruitmentId}")
keyword를 추가하는 건 저도 동의합니다
내부 코드가 지원서의 정보를 조회하는 데 사용 할 수는 있지만 해당 API에 기대하는 내용은
keyword에 해당하는 모든 지원정보를 가져오는 것 같아요
그걸 생각해보면 저는 제이슨 의견처럼 url을 짜는 편입니다

2021-07-14 17:30 UTC, NewWisdom commented on src/main/kotlin/apply/ui/api/ApplicantRestController.kt
> +        @PathVariable("recruitmentId", required = true) recruitmentId: Long
말씀해주신 불필요한 @PathVariable 옵션을 컨트롤러 전반적으로 제거했습니다! 
감사합니다!!

2021-07-14 17:32 UTC, NewWisdom commented on src/main/kotlin/apply/ui/api/EvaluationRestController.kt
> +        return ResponseEntity.ok().body(Unit)
반환바디가 없는 ok 응답은 `ResponseEntity.ok().build()`로 통일하였습니다  ㅎㅎ
감사합니다!!!

2021-07-14 17:33 UTC, NewWisdom commented on src/test/kotlin/apply/ui/api/EvaluationRestControllerTest.kt
> +@ExtendWith(RestDocumentationExtension::class, SpringExtension::class)
엇 불필요한 코드였네요 ㅎㅎㅎㅎ
제거했습니다 감사합니다!!

2021-07-14 17:35 UTC, NewWisdom commented on src/test/kotlin/apply/ui/api/EvaluationTargetControllerTest.kt
> +                    getDocumentResponse(),
오 맞습니다!!! 
지워도 되는 코드인데 그대로 냅뒀었네요 🥲
감사합니다!

2021-07-14 17:36 UTC, NewWisdom commented on src/main/kotlin/apply/ui/api/RecruitmentRestController.kt
> +    fun deleteById(@PathVariable id: Long): ResponseEntity<Unit> {
반영했습니다!
감사합니다 ㅎㅎ

2021-07-14 17:39 UTC, NewWisdom commented on src/test/kotlin/apply/ui/api/EvaluationTargetControllerTest.kt
> +        mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext)
오 감사합니다 !!!
말씀대로 문서화를 위한 어노테이션이나 mockMvc 설정 등 공통 코드들은 추상클래스로 빼내었습니다 !!!ㅎㅎ

2021-07-14 17:47 UTC, NewWisdom commented on src/test/kotlin/apply/ui/api/CheaterRestControllerTest.kt
> +    private lateinit var applicantService: ApplicantService // todo: 이 객체를 MockBean으로 주입해야하는 이유 찾기
와아 자세한 설명 너무 너무 감사합니다 도움이 많이 되었어요 🙇‍♂️🙇‍♂️
아직 모든 컨트롤러가 문서화되지 않아서 말씀해주신 부분과 API 문서화까지 이슈 파면 좋을 것 같네요!!
말씀해주신 불필요한 필터 코드는 제거 했습니다 :) 감사합니다!

2021-07-14 18:19 UTC, ecsimsw commented on src/main/kotlin/apply/ui/api/ApplicantRestController.kt
> +    @GetMapping("/{keyword}/recruitments/{recruitmentId}")
저도 applicants보다, recruitments에 좀 더 초점을 두고 있습니다.
`/api/recruitments/{recruitmentId}/application-forms?applicantKeyword=` 에 한 표입니다.

2021-07-14 18:25 UTC, ecsimsw commented on src/test/kotlin/apply/ui/api/CheaterRestControllerTest.kt
> +    private lateinit var applicantService: ApplicantService // todo: 이 객체를 MockBean으로 주입해야하는 이유 찾기
사실 '특정 빈만을 로드한다.' 라는 말에, @WebMvcTest 정도면 괜찮겠지..라는 생각으로 '보다 가볍게'를 고민해본 적이 없었습니다.
`컨트롤러 테스트는 결국 문서화 목적`이라는 말 명심하겠습니다.
꼼꼼한 리뷰 감사합니다.

2021-07-15 00:26 UTC, woowahan-pjs commented on src/test/kotlin/apply/ui/api/CheaterRestControllerTest.kt
> +    private lateinit var applicantService: ApplicantService // todo: 이 객체를 MockBean으로 주입해야하는 이유 찾기
@ecsimsw 
모든 컨트롤러 테스트가 문서화 목적이라는 의미는 아닙니다. 😂 저희가 문서화 목적으로 쓰고 있어서 그래요.

2021-07-15 00:58 UTC, woowahan-pjs commented on src/test/kotlin/apply/ui/api/CheaterRestControllerTest.kt
> +    private lateinit var applicantService: ApplicantService // todo: 이 객체를 MockBean으로 주입해야하는 이유 찾기
[느려터진 Spring Rest Docs Test? SpringContext, @MockBean 없이 빠르고 효과적으로 사용하기](https://geminikim.medium.com/%EB%8A%90%EB%A0%A4%ED%84%B0%EC%A7%84-spring-rest-docs-test-springcontext-mockbean-%EC%97%86%EC%9D%B4-%EB%B9%A0%EB%A5%B4%EA%B3%A0-%ED%9A%A8%EA%B3%BC%EC%A0%81%EC%9C%BC%EB%A1%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-dc36861493c9)

2021-07-15 01:20 UTC, ddaaac commented on src/main/kotlin/apply/ui/api/CheaterRestController.kt
> +    fun save(@RequestParam("applicantId") applicantId: Long): ResponseEntity<Unit> {
리소스를 분명하게 식별하는 의미헤서는 `/cheater/applicant/{applicantId}` 도 괜찮아보이네요. 다른 분들 의견도 궁금해요 😃

2021-07-15 01:23 UTC, ddaaac commented on src/test/kotlin/apply/ui/api/CheaterRestControllerTest.kt
> +    private lateinit var applicantService: ApplicantService // todo: 이 객체를 MockBean으로 주입해야하는 이유 찾기
@ecsimsw
![image](https://user-images.githubusercontent.com/43440195/125713226-dfdfd213-d66c-464d-b92a-54537868d8cd.png)
코멘트 남기기 전에 이런 질문도 했었어요. 코멘트 쓸 때 이 부분을 빼먹고 썼네요 ㅎㅎ

2021-07-15 01:30 UTC, ddaaac commented on src/test/kotlin/apply/ui/api/EvaluationTargetControllerTest.kt
> +        ).andExpect(status().isOk)
아 저도 이거 때문에 여기저기 찾아봤었는데 딱히 방법이 없었던 거로 기억나네요 🥲
참고로, restdocs의 코틀린 dsl은 `https://github.com/spring-projects/spring-restdocs/issues/547` 이 스레드에서 논의되고 있어요!
restdocs가 코틀린 dsl을 공식적으로 지원할 때까지 저희는 mockmvc 코틀린 dsl도 사용하지 못하겠네요

2021-07-15 10:43 UTC, lalize commented on src/main/kotlin/apply/ui/api/CheaterRestController.kt
> +    fun save(@RequestParam("applicantId") applicantId: Long): ResponseEntity<Unit> {
@ddaaac 지원자를 부정행위자로 등록 api니 저는 pr 하신 코드 그대로 가는 게 좋아 보여요.

의견 주신 부분은 applicantId로 부정행위자를 특정하여 어떤 로직을 처리하는 api인 경우 논의 해볼 내용이라고 생각합니다.

2021-07-17 08:09 UTC, NewWisdom commented on src/main/kotlin/apply/ui/api/CheaterRestController.kt
> +    fun save(@RequestParam("applicantId") applicantId: Long): ResponseEntity<Unit> {
논의해보니 지금은 Cheater에서 식별자와 함께 applicantId를 쓰고 있지만 
추후 이 부분에 대해 변경이 있을거라 하셨기에 후에 path variable을 받는 방식으로 하겠습니다.
좋은 의견들 감사합니다!!

2021-07-17 08:10 UTC, NewWisdom commented on src/main/kotlin/apply/ui/api/ApplicantRestController.kt
> +    @GetMapping("/{keyword}/recruitments/{recruitmentId}")
해당 API는 `/api/recruitments/{recruitmentId}/application-forms?applicantKeyword=`로 수정하였습니다 
좋은 의견들 감사합니다!!

2021-07-17 08:17 UTC, NewWisdom commented
`/api/recruitments/{recruitmentId}/application-forms?applicantKeyword=` 에 대해서 
keyword에 대한 분기처리를 결국 서비스 레이어에서 하도록 일단 변경해보았습니다. ㅎㅎ
그러다 기존의 있던 메서드 하나에서 분기처리를 하기 위해 `ApplicantService`의 메서드도 좀 변경이 되었습니다.
리뷰 부탁드리겠습니다.
감사합니다 🙇‍♂️

2021-07-17 08:48 UTC, ddaaac commented on src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt
>          mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext)
이제 각 컨트롤러 테스트에 있는 `mockMvc` 재정의는 필요없지 않을까요?

2021-07-17 08:48 UTC, ddaaac commented on src/main/kotlin/apply/application/ApplicantService.kt
>      }
```suggestion
    fun findAllByRecruitmentIdAndSubmittedTrueAndKeyword(recruitmentId: Long, keyword: String?): List<ApplicantAndFormResponse> {
        val applicationFormMap = applicationFormRepository
            .findByRecruitmentIdAndSubmittedTrue(recruitmentId)
            .associateBy { it.applicantId }
        return if (keyword != null) {
            applicationFormMap.match { applicantRepository.findAllByKeyword(keyword) }
        } else {
            applicationFormMap.run { match { applicantRepository.findAllById(keys) } }
        }
```
keyword를 nullable하게 받는 방식 너무 좋네요. 👍  

참고로, 코틀린의 if문은 expression이기 때문에 값을 리턴합니다. 그래서 이런 식으로도 쓸 수 있어요. 아니면 `?.`와 `?:`를 활용해서도 처리할 수 있겠네요. 

----
그리고 조금 더 리팩토링을 진행해봐도 좋을 거 같아요! 안그래도 `match()`메서드가 계속 눈에 밟혔거든요. 중복을 해결하기 위해 만든 메서드였는데 이제 중복도 없어졌으니 가독성을 올려봐도 될 거 같아요. `match()` 메서드를 제거하고 `findAllByRecruitmentIdAndSubmittedTrueAndKeyword()` 메서드만 남겨도 될 것 같지 않나요?

2021-07-17 09:38 UTC, NewWisdom commented on src/test/kotlin/apply/ui/api/ApplicantRestControllerTest.kt
>          mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext)
앗 제거한다는게 놓쳤네요!
꼼꼼한 리뷰 감사합니다!!

2021-07-17 10:03 UTC, ddaaac commented on src/test/kotlin/apply/ui/api/CheaterRestControllerTest.kt
> +        every { cheaterService.findAll() }.answers { expected }
https://github.com/woowacourse/service-apply/pull/251#discussion_r669606182 에도 남겼지만 returns와 answers를 언제 사용하면 적당할지 생각해보면 좋을 거 같아요 :)
그리고 다른 곳은 infix 스타일로 사용된 곳이 많은데 통일하면 좋을 거 같구요.

2021-07-17 10:03 UTC, ddaaac commented on src/test/kotlin/apply/application/ApplicantServiceTest.kt
> +            }
```suggestion
            every { applicantRepository.findAllByKeyword(any()) } answers {
                listOf(createApplicant(name = it.invocation.args[0] as String, id = applicantId))
            }
```

마침 answer를 사용하기 적당한 예제가 있네요. answer를 사용하면 좀 더 간단하게 표현할 수 있습니다 😄

2021-07-17 16:27 UTC, NewWisdom commented on src/test/kotlin/apply/ui/api/CheaterRestControllerTest.kt
> +        every { cheaterService.findAll() }.answers { expected }
해당 코멘트 참고해서 바꾼다는다는걸 여기는 놓쳤었네요!! ㅎㅎㅎ 
반영했습니다 감사합니다!!!

2021-07-17 16:36 UTC, NewWisdom commented on src/main/kotlin/apply/application/ApplicantService.kt
>      }
말씀대로 `findAllByRecruitmentIdAndSubmittedTrueAndKeyword()`을 좀 더 개선해보았습니다!!!!
제안해주신 분기 처리를 지원자리스트 받아오는데 적용하고 `match()`를 제거해보았습니다
아직 코틀린 문법이 익숙치 않은데 좋은 제안 덕분에 많이 배워갑니다 
부족한 부분있으면 말씀부탁드립니다 감사합니다 🙇‍♂️

2021-07-17 16:53 UTC, ddaaac approved these changes
고생 정말 많으셨어요! 첫 pr부터 리뷰가 너무 빡셌네요 ㅋㅋㅋ
제가 만들었던 레거시들이 눈에 보여서 리뷰를 많이 남긴 거 같네요 😄 

앞으로도 잘 부탁드려요 🙇

2021-07-17 16:53 UTC, ddaaac commented on src/main/kotlin/apply/application/ApplicantService.kt
> +        }
```kotlin
        applicants.mapNotNull {
            applicationFormMap[it.id]?.let { form ->
                ApplicantAndFormResponse(it, cheaterApplicantIds.contains(it.id), form)
            }
        }
```

```kotlin
        applicants.filter { applicationFormMap.containsKey(it.id) }
                .map { ApplicantAndFormResponse(it, cheaterApplicantIds.contains(it.id), applicationFormMap.getValue(it.id)) }
```

여러 스타일로 표현할 수 있습니다. 개인적으로는 마지막에 제시한게 제일 마음에 들어요 :)
이 부분은 아마찌(맞나요? ㅋㅋ)에 판단에 맡기겠습니다~

2021-07-17 16:53 UTC, ddaaac commented on src/main/kotlin/apply/application/ApplicantService.kt
> +    fun findAllByRecruitmentIdAndSubmittedTrueAndKeyword(
이름을 조금 더 추상화해도 될 거 같기도 하네요. 메서드명이 너무 길어졌어요

2021-07-17 17:03 UTC, NewWisdom commented on src/main/kotlin/apply/ui/api/ApplicantRestController.kt
> +    @GetMapping("/{keyword}/recruitments/{recruitmentId}")
해당 api를 ApplicationFormRestController로 옮기고 보니 `지원서 불러오기 GET "/api/recruitments/{recruitmentId}/application-forms"`와 중복이 되는 문제를 발견했습니다 .

서로 반환 값이 달라 둘을 구분지어야 하는데, 지원자 정보도 담겨 명확하게 하자는 의견을 반영하여
`"/api/recruitments/{recruitmentId}/application-forms-and-applicants?keyword="`로 다시 변경해보았습니다. 
혹시 더 좋은 의견 있으실까요?!

2021-07-17 17:09 UTC, ddaaac commented on src/test/kotlin/apply/ui/api/EvaluationTargetControllerTest.kt
> +        ).andExpect(status().isOk)
아, 작업일지를 보니 이 부분 작업을 하시는 거 같은데 pathParameter를 사용하고 싶다면 `MockMvcBuilders`와 `RestDocumentationRequestBuilders` 구현의 차이점을 한 번 살펴보시면 좋을 것 같아요.
 [RestDocumentationRequestBuilders의 내부 구현](https://github.com/spring-projects/spring-restdocs/blob/c6e7b567e34d316cbb2424d44d011e2de971201b/spring-restdocs-mockmvc/src/main/java/org/springframework/restdocs/mockmvc/RestDocumentationRequestBuilders.java)을 살펴보는 게 힌트가 될 지도 모르겠네요 😉

2021-07-17 17:10 UTC, NewWisdom commented on src/main/kotlin/apply/application/ApplicantService.kt
> +        }
맞습니다 ㅎㅅㅎ
오 이렇게도 쓸 수 있었네요 저도 마지막 제안이 좋아보입니다!!! 
반영했습니다 감사합니다!!!

2021-07-17 17:13 UTC, NewWisdom commented on src/main/kotlin/apply/application/ApplicantService.kt
> +    fun findAllByRecruitmentIdAndSubmittedTrueAndKeyword(
메서드를 합치면서 명을 다 담다보니 과하게 길어졌네요 ㅎㅎㅎ
`AndSubmittedTrue`는 뺐습니다 !

빡센 리뷰 오히려 좋았(?)습니다!! ㅎㅎㅎㅎ 많이 배워가네요
저도 잘부탁드리겠습니다 🙇‍♂️

2021-07-19 15:20 UTC, Rok93 commented
회의 내용 토대로 `ApplicationFormRestController`에 있는 핸들러들의 URI 맵핑을 수정했습니다. (대부분 작업 이전의 URI로 돌려놨습니다) 
[작업 내용](https://www.notion.so/393c7339122e426eb7d5e87c2f25e6f3) 해당 부분에도 남겨뒀습니다. 

RecruitmentService에 `findAll()`과 `getNotEndedDataById()` 기능을 API로 분리하는 작업을 추가적으로 수행했습니다. 
* `findAll()`은 추가적으로 논의할 부분들이 많다고 판단되어, 이슈로 등록하여 추후 다루기로 하였습니다. 
* `getNotEndedDataById()` 기능을 `/api/recruitments/{recruitmentId}/detail` API로 뽑아냈습니다. 
     * getById가 `/api/recruitments/{recruitmentId}`로 뽑혀있기 때문에 이 기능과 차이를 주기위해 뒤에 `detail`을 추가하였습니다. 
     * `해당 API 설계가 적절한가?`에 대한 의견을 듣고싶습니다 🙏

2021-07-22 12:14 UTC, MyaGya reviewed
코드 짜면서 엄청 힘드셨을 것 같아요, Cheater 관련해서 남기고 싶은 의견이 있었는데 정책이 바뀔 예정이라서 그 부분은 뺏더니 한 부분밖에 리뷰할 곳이 없었어요
- 테스트 코드에는 약해서 해당 부분은 리뷰하지 못했어요
- 주로 컨트롤러와 매핑된 API의 동작이나 어색함이 없는지에 대해서 살펴보았습니다

2021-07-22 12:14 UTC, MyaGya commented on src/main/kotlin/apply/ui/api/EvaluationTargetRestController.kt
> +    fun findAllByEvaluationIdAndKeyword(
해당 API 가 지원 플랫폼 API 엑셀파일에 없는 걸로 보이는데요
GET `/api/recruitments/{recruitmentId}/evaluations/{evaluationId}` 에 해당되는 걸까요?

2021-07-22 19:24 UTC, ecsimsw reviewed
adf

2021-07-22 19:50 UTC, ecsimsw reviewed
정말 고생하셨습니다!!

2021-07-22 19:50 UTC, ecsimsw commented on src/main/kotlin/apply/application/ApplicantService.kt
> +        keyword: String?
findAllByRecruitmentIdAndKeyword에서, keyword를 null로 두면 모집 id로 검색한다는 의도라면, keyword의 기본 값을 null로 주는 것은 어떨까요?

findAllByRecruitmentIdAndKeyword을 호출할 때 keyword에 null을 명시하는 경우가 많은 것 같아 제안 드립니다.

혹시 findAllByRecruitmentIdAndKeyword이라는 메소드 명이 모집 id와 키워드로 검색이라, 일부러 Keyword는 null을 명시하여 Keyword는 필터링하지 않음을 보여준 것이라면 이 코멘트는 무시해주세요.

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/46060746/126699902-5e57f2fd-edad-4a28-af7e-21285673d07d.png">

2021-07-23 01:20 UTC, MyaGya approved these changes

2021-07-23 01:20 UTC, ecsimsw approved these changes

2021-07-23 08:53 UTC, Sehwan-Jang approved these changes
정말 많은 작업이 있었네요 수고하셨습니다!

이번에 api 문서대로 api가 작성되었는지를 위주로 살펴보고 코멘트 남겼습니다 :)

2021-07-23 08:53 UTC, Sehwan-Jang commented on src/main/kotlin/apply/ui/api/ApplicationFormRestController.kt
> +        @PathVariable recruitmentId: Long,
api 문서에도, 코드상에서도 사용하고 있지 않는 것 같아요 🙂

2021-07-23 08:53 UTC, Sehwan-Jang commented on src/main/kotlin/apply/ui/api/EvaluationTargetRestController.kt
> +    fun findAllByEvaluationIdAndKeyword(
마갸가 말씀하신 api는 `EvaluationRestController` 에 따로 뚫려있는 api 로 보입니다.
해당 api는 따로 api 문서에 추가해야 할것 같아요!

2021-07-23 09:03 UTC, Sehwan-Jang commented on src/test/kotlin/apply/application/ApplicantServiceTest.kt
> +    inner class Find {
inner class 로 구현된 테스트 클래스를 실행 시켜 보면 아래와 같이 계층적으로 테스트 결과가 나오는데 개인적으로 보기에 굉장히 좋았어요!
<br>
![image](https://user-images.githubusercontent.com/68985748/126760130-99741350-3892-44e7-95dd-a0b2c61cae09.png)

2021-07-23 15:23 UTC, NewWisdom commented on src/main/kotlin/apply/ui/api/EvaluationTargetRestController.kt
> +    fun findAllByEvaluationIdAndKeyword(
아론 말이 맞습니다!!
해당 api가 keyword를 쿼리파람으로 받기로 변경되었는데, 문서에는 반영이 안됐었네요 ㅎㅎ
`/api/recruitments/{recruitmentId}/evaluations/{evaluationId}/targets?keyword=`로 문서 변경했습니다 감사합니다!

2021-07-23 15:35 UTC, NewWisdom commented on src/test/kotlin/apply/application/ApplicantServiceTest.kt
> +    inner class Find {
원래 해당 메서드가 RecruitmentId로 지원자 정보를 찾는 경우, 키워드가 함께 오는 경우 이렇게 두개의 메서드로 분리되어 있었습니다
이번 리팩토링 하면서 두개의 메서드를 하나로 합치게 되었는데요,
기존에 전반적인 테스트 코드를 보니 한 메서드에 대해 여러 상황이 오는 경우 
`@Nested`를 통해 계층 구조를 나타내고 있어 이 통일성을 가져가기 위해서 위와같이 작성하였습니다
사실 이런 방식으로 테스트를 작성한 것이 처음이라 확신은 없지만 ㅎㅎ
아론이 말한 것과 같이 키워드 유무에 따른 상황을 묶어 테스트 했을 때 가독성도 더 좋다고 느꼈습니다

2021-07-23 15:35 UTC, NewWisdom commented on src/test/kotlin/apply/application/ApplicantServiceTest.kt
> +    inner class Find {
그리고 `지원자 정보와 부정 행위자 여부를 함께 제공한다` 테스트는 중복되고 있는게 맞네요! 
밑의 테스트 코드는 지우는걸 깜빡한 것 같습니다 감사합니다 ㅎㅎ

2021-07-23 15:37 UTC, NewWisdom commented on src/main/kotlin/apply/application/ApplicantService.kt
> +        keyword: String?
기본인자로 null을 주는 것 좋은 방식인 것 같네요!
놓치고 지나간 부분이었는데, 좋은 제안 감사합니당

2021-07-23 15:38 UTC, NewWisdom commented on src/main/kotlin/apply/ui/api/ApplicationFormRestController.kt
> +        @PathVariable recruitmentId: Long,
놓치고 지나간 부분이었네요!! 
제거하였습니다 감사합니다 ㅎㅎ

2021-07-23 15:55 UTC, NewWisdom commented on src/main/kotlin/apply/ui/api/ApplicationFormRestController.kt
> +    @GetMapping("/recruitments/{recruitmentId}/application-forms")
처음에는 상위 패스를 보고 RecruitmentRestController에 두는 것을 고민했습니다!
하지만 RecruitmentRestController는 모집에 대한 기능을 맵핑하는 곳인데 
해당 api 역할을 보면 지원서 조회이니, 지원서에 대한 기능에 더 초점이 맞춰져 있는 것같아
상위 패스만으로 해당 컨트롤러에 위치시키는 것은 충분한 이유가 되지 못할 것 같다고 생각했어요.
패스보다 해당 api 가 하는 역할, 반환 값을 고려하다 보니 컨트롤러 상단 RequestMapping은 깨지지만 
지원서에 대한 ApplicationFormRestController에 있는 것이 더 자연스럽다고 생각했습니다.

또 말씀대로 RecruitmentRestController에 ApplicantService의 의존이 생기는 것 보다 
ApplicationFormRestController에서 지원자에 대한 ApplicantService를 가지고 있는 것이 더 자연스럽다고도 느꼈구요.

저도 해당 api를 어떤 컨트롤러에 두어야 하나 많은 고민을 하다가,
이러한 이유들로 ApplicationFormRestController에 두게 되었네요 ㅎㅎ
좋은 질문 감사합니당

2021-07-26 07:49 UTC, merged