refactor(apply): migrate LoginPage component to react
woowacourse/service-apply pull request #286
Opened 2021-08-01 13:19 UTC by seojihwan

2021-08-03 08:21 UTC, woowapark commented
브랜~
PR에는 구현할 때 기준으로 삼은 요구사항들이 같이 정리되면 더 좋을 것 같아요! 🙏
그래야 '어떤 것들을 확인해야 정상적으로 마이그레이션 되었다고 확인할 수 있을 지' 같이 확인해볼 수 있을 것 같네요!
(작업 완료 후에 다 합쳐서 점검할 때에도 어차피 필요한 부분이고요~)

기존에 요구사항 정리하신 부분 중에서 작업하신 영역에 해당하는 요구사항들이 무엇인지 남겨주시면 될 것 같습니다 :)

2021-08-03 08:31 UTC, woowapark commented on frontend/src/pages/Login/Login.js
> +  const disabled =
'어떠한 조건'일 때 disabled되는 지에 대한 값이니, 
조건을 설명해주는 이름이 더 의미 파악이 쉬울 것 같은데 어떠신가요~

2021-08-03 08:31 UTC, woowapark commented on frontend/src/pages/Login/Login.js
> +          v-model="email"
v-model같은 부분은 vue의 잔재이니 빼주세요~

2021-08-03 08:35 UTC, woowapark commented on frontend/src/pages/Login/Login.js
> +  const [value, setValue] = useState({});
value와 같이 일반적인 단어보다는 좀 더 구체적으로 어떤 정보인지 드러나는 이름이면 좀 더 좋지 않을까 싶네요~!      
여기에서는 로그인뿐이라 크게 복잡해질 일은 없겠지만-     
setValue, setData같은 이름은 편리한 대신 나중에 아무 데이터나 다 뭉태기로 넣어도 될 것 같이 생겨서 처음의 의도 파악을 힘들게 만들 수도 있습니다용

2021-08-03 08:39 UTC, woowapark commented
Storybook은 에러나는 상황이 맞을까용?

2021-08-03 08:39 UTC, woowapark requested changes
리뷰 확인 부탁드려요~

2021-08-04 16:08 UTC, seojihwan commented on frontend/src/pages/Login/Login.js
> +  const [value, setValue] = useState({});
사실 이부분자체가 추상화를 고려해서 작성된부분이라 추후에 중복로직을 분리하면 네이밍의 문제는 사라질 것 같습니다! disabled와 마찬가지로 리팩터링 단계에서 고려해도될까요?

2021-08-05 09:34 UTC, woowapark commented on frontend/src/pages/Login/Login.js
> +  const [value, setValue] = useState({});
넵 알겠습니다~

2021-08-05 09:38 UTC, woowapark commented
- '비밀번호 찾기'의 레이아웃이 아직 맞지 않아 확인이 필요합니다~
- https://github.com/woowacourse/service-apply/pull/287 에서와 마찬가지로,    
  글자수 UI는 기존 서비스, 서비스를 옮긴 피그마 모두에서 없는 부분으로 보이는데요. 추가를 하신 부분일까요 ?-?

2021-08-05 14:39 UTC, seojihwan commented
Vue 코드를 옮기면서 제공되고 있는 ui라고 확신했는데 프로덕션에는 존재하지 않는 ui였네요! 디자인 시안에서 놓쳤다고 생각했는데 아니었네요! 글자수 표시 부분은 삭제하였습니다!

2021-08-06 05:40 UTC, woowapark approved these changes
고생하셨습니다~👏

2021-08-08 19:57 UTC, SunYoungKwon approved these changes
수고하셨어요!

2021-08-09 05:41 UTC, woowapark commented
리뷰 반영까지 고생하셨어요~! 

@woowahan-pjs 
제이슨 확인하신 뒤 머지 부탁드릴게요! 🙏

2021-08-09 05:43 UTC, woowahan-pjs approved these changes

2021-08-09 05:44 UTC, merged