feat:  implement recruitment deletion policy
woowacourse/service-apply pull request #292
Opened 2021-08-02 06:58 UTC by knae11

Closes #278 

# 구현내용
- 제출된 지원서(ApplicationForm)가 있다면 해당 모집(Recruitment)은 삭제될 수 없다.
- 해당 모집이 삭제된다면, 모집항목(RecruitmentItem), 평가(Evaluation), 평가항목(EvaluationItem)이 함께 삭제된다.
    - 지원서가 없다면 ApplicationFormAnswer, EvaluationTarget, EvaluationTargetAnswers 도 존재할 수 없다.

2021-08-07 06:37 UTC, MyaGya reviewed
고생하셨습니다! 간단하게 코멘트 하나 남겼어요.

2021-08-07 06:37 UTC, MyaGya commented on src/main/kotlin/apply/application/RecruitmentService.kt
> +        evaluationRepository.deleteInBatch(evaluations)
지원서를 삭제하고 관련된 평가를 한꺼번에 삭제해주는 코드로 보여요,
그런데 직접 삭제해주고 있는데요, cascade와 같은 설정을 넣어준게 아니라 직접 구현하신 이유가 있을까요?

2021-08-07 06:37 UTC, MyaGya commented on src/test/kotlin/apply/application/RecruitmentServiceTest.kt
> +            every { evaluationItemRepository.deleteInBatch(listOf(createEvaluationItem(id = 4L))) } just Runs
`just Runs` 와  `returns Unit` 두 가지가 동일한 의미로 테스트 코드에서 혼용되고 있는걸로 보이는데요. just Runs 를 사용하신 이유가 있을까요?

2021-08-09 03:32 UTC, Sehwan-Jang commented on src/main/kotlin/apply/application/RecruitmentService.kt
> +        evaluationRepository.deleteInBatch(evaluations)
현재 스키마 상으론 fk도 안걸려있어서 일단 스키마 변경을 일으키지 않는 선에서 구현하려고 하신 것이라고.... 예측해보는데 맞을까요? 😅

2021-08-09 03:39 UTC, Sehwan-Jang approved these changes
안녕하세요 배럴! 정책 구현하시느라 정말 수고하셨어요 🙂
궁금한 점 하나 코멘트 달았습니다.

2021-08-09 03:39 UTC, Sehwan-Jang commented on src/main/kotlin/apply/application/RecruitmentService.kt
> +
이 부분도 반환 타입을 명시해주는 것으로 통일하면 어떨까요?

2021-08-09 03:39 UTC, Sehwan-Jang commented on src/main/kotlin/apply/application/RecruitmentService.kt
> +        check(!recruitment.recruitable)
현재 모집중인 상태의 경우 실수로 모집을 삭제하는 것을 방지하기 위해 추가된 설정일까요?

2021-08-09 05:33 UTC, knae11 commented on src/main/kotlin/apply/application/RecruitmentService.kt
> +        check(!recruitment.recruitable)
네네 맞아요! 해당 내용은 원래 코드가 모집중인 경우 삭제를 불가능하게 되어 있었어서, 그 내용을 유지하기 위함이기도 합니다 😀

2021-08-11 18:00 UTC, NewWisdom reviewed
구현하시느라 수고 많으셨습니다  짱짱 👏👏
확인하고 간단한 코멘트들 몇 가지 남겨보았습니다 :)
화이팅~

2021-08-12 07:18 UTC, knae11 commented on src/main/kotlin/apply/application/RecruitmentService.kt
> +        evaluationRepository.deleteInBatch(evaluations)
현재 JPA 상에서 외래키 관계가 안 맺어져 있고, DB 상에서만 외래키 관계가 맺어져 있어서 cascade 설정을 사용할 수 없는 것으로 알고 있어요!  혹시 제가 잘못 알고 있는 것이라면 알려주세요 🙂

2021-08-12 07:19 UTC, knae11 commented on src/test/kotlin/apply/application/RecruitmentServiceTest.kt
> +            every { evaluationItemRepository.deleteInBatch(listOf(createEvaluationItem(id = 4L))) } just Runs
이부분 통일할게요!  제가 기존에 `just Runs` 쓰던게 남아있어서 그렇네요 `returns Unit`으로 통일하겠습니다 :)

2021-08-12 07:22 UTC, knae11 commented on src/main/kotlin/apply/application/RecruitmentService.kt
> +
이 부분 반환 타입 명시를 놓쳤네요:) 감사합니다!

2021-08-12 07:48 UTC, knae11 commented on src/test/kotlin/apply/application/RecruitmentServiceTest.kt
> +        }
오 맞아요 내부에 없어도 되는데 무의식적으로 기존 테스트코드와 이어서 만들게 된 것 같아요. 해당내용 inner class 밖으로 빼주었습니다! 뉴위즈덤 👍

2021-08-12 07:53 UTC, knae11 commented on src/main/kotlin/apply/application/RecruitmentService.kt
> +        evaluationItemRepository.findAllByEvaluationId(evaluation.id)
위에 내용 코멘트와 더불어서 By~ 를 넣지 않은 이유는 메소드 네이밍이 너무 길어지기 때문입니다.  혹시 다른 분들의 의견도 궁금합니다 😄

2021-08-12 07:58 UTC, knae11 commented on src/main/kotlin/apply/application/RecruitmentService.kt
> +    private fun findRecruitmentItems(recruitmentId: Long, excludedItemIds: List<Long>): List<RecruitmentItem> {
아래 새롭게 find 하는 메소드들과 메소드 명명을 맞추기 위함이었습니다. 

- 해당 내용은 기존 코드이니 원복하고 새로운 코드는 그대로 가는 것이 좋은지
- 모두 `~ToDelete` 없이 통일하는 것이 좋은지
- 모두 `~ToDelete` 포함하여 통일하는 것이 좋은지

다른 분들의 의견도 궁금합니다 :) 


- 다만 새롭게 추가된 내용은 원래 있던 메소드처럼 delete 할 내용을 찾아온다고 하기보다, 단순히 조회하기 때문에 `ToDelete`라는 것을 붙이지 않았습니다.
- 기존의 findRecruitmentItemsToDelete 는 `.filterNot { excludedItemIds.contains(it.id) }` 을 사용하여 어떤 내용들을 걸러주는 역할을 추가적으로 하고 있습니다. 하지만 새롭게 만든 메소드들은 삭제할 대상이긴 하지만 단순히 아이디로 조회해오고 있습니다.

2021-08-31 11:35 UTC, woowahan-pjs commented on src/test/kotlin/apply/application/RecruitmentServiceTest.kt
> +            every { evaluationItemRepository.deleteInBatch(listOf(createEvaluationItem(id = 4L))) } just Runs
`just Runs`로 결정되었습니다.
https://notwoods.github.io/mockk-guidebook/docs/tips/unit

2021-09-01 08:22 UTC, woowahan-pjs requested changes
해결하려는 문제에 초점을 맞춘 덕분에 코드가 훨씬 더 깔끔해졌네요. 👍

2021-09-01 08:22 UTC, woowahan-pjs commented on src/main/resources/db/migration/V1_3__Add_deleted_recruitment.sql
> +    add deleted boolean not null after id;
파일 끝에 개행을 추가해야 하는 이유
https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline

2021-09-01 08:22 UTC, woowahan-pjs commented on src/test/kotlin/apply/application/RecruitmentServiceTest.kt
> +            )
```suggestion
        recruitmentService = RecruitmentService(recruitmentRepository, recruitmentItemRepository, termRepository)
```

2021-09-01 08:22 UTC, woowahan-pjs commented on src/test/kotlin/apply/application/RecruitmentServiceTest.kt
> +    fun `모집중인 경우 모집을 삭제하는 경우 예외를 던진다`() {
'모집 중인 모집을 삭제할 때 예외가 발생한다', 또는 '모집 중인 모집은 삭제할 수 없다'는 어떤가요?

2021-09-01 10:09 UTC, knae11 commented
# 정책 재변경 사항(기존 로직과 거의 유사)

- ✨ 지원서가 있어도 모집을 삭제할 수 있다. (모집삭제와 관련하여 모집중 이외의 제약사항이 없음)
- 모집 삭제는 `deleted` 라는 컬럼을 추가하여 **논리삭제**로 구현
- 기존 로직대로 모집 중인 모집은 삭제할 수 없다.

## 논리삭제 로직학습내용 참고자료

### Recruitment 클래스
- `@SQLDelete` 어노테이션으로 delete 쿼리를 재정의 하여 논리 삭제를 구현할 수 있다.
- `@where` 어노테이션으로 조회 시 쿼리에 where 조건을 자동으로 넣어준다.
- deleted 프로퍼티는 도메인의 측면에서 기술적영역(논리 삭제이지만 삭제로 생각)이므로 해당 프로퍼티는 숨긴다.
- 해당 내용과 관련한 쿼리는 RecruitmentRepositoryTest에서 확인할 수 있다.

### RecruitmentRepositoryTest

- `@EnableJpaRepositories` ,`@EntityScan`어노테이션으로 해당 패키지의 내용으로만 테스트를 진행할 수 있다.

```bash
@EnableJpaRepositories("apply.domain.recruitment")
@EntityScan("apply.domain.recruitment")
@RepositoryTest
```

2021-09-01 11:12 UTC, NewWisdom approved these changes
정리해주신 내용도 봤는데 작업한 내용도 잘 파악되었고,
덕분에 새로운 키워드도 배워갑니다. 감사합니다 ㅎㅎ
보면서 질문만 하나 남겨보았습니다.
수고 많으셨습니다 👏👏
멋져요 !!!!!!!

2021-09-01 11:50 UTC, ecsimsw commented on src/main/resources/db/migration/V1_3__Add_deleted_recruitment.sql
> +    add deleted boolean not null after id;
확인하고 추가하였습니다.

2021-09-01 11:50 UTC, ecsimsw commented on src/test/kotlin/apply/application/RecruitmentServiceTest.kt
> +            )
수정했습니다.

2021-09-01 11:52 UTC, ecsimsw commented on src/test/kotlin/apply/application/RecruitmentServiceTest.kt
> +    fun `모집중인 경우 모집을 삭제하는 경우 예외를 던진다`() {
예외의 내용없이도 테스트 코드를 표현할 수 있다, 더 명확하다,
라는 생각에  '모집 중인 모집은 삭제할 수 없다'을 선택했습니다.

추천 감사합니다.

2021-09-01 13:28 UTC, Sehwan-Jang approved these changes
구현하시느라 정말 수고하셨습니다! 
몇가지 궁금한 부분들만 코멘트 남겼는데 천천히 확인 부탁드려요 🙂
코드는 테스트도 다 통과하고 로컬에서 동작시켜봤을 때도 잘 동작하기에 approve 하겠습니다.

2021-09-01 13:28 UTC, Sehwan-Jang commented on src/test/kotlin/apply/domain/recruitment/RecruitmentRepositoryTest.kt
> +class RecruitmentRepositoryTest(
저도 이부분 궁금하네요! 
`RepositoryTest` 에 이미 `DataJpaTest` 어노테이션이 포함되어 있어 위에 두줄은 주석처리하고 실행해봐도 돌아가는데 혹시 저 두줄을 적용하면 해당 패키지만 스캔하는 걸까요??

2021-09-01 13:28 UTC, Sehwan-Jang commented on src/main/kotlin/apply/domain/recruitment/Recruitment.kt
> +@Where(clause = "deleted=false")
soft delete 👏👏👏
그런데 혹시 논리적 삭제를 도입하게 된 이유가 있을까요? 
혼자 생각해본 결과 지원서가 있는 경우 모집을 삭제했을 때 지원서도 함께 삭제될까봐? 추가된 것일 수도 있다고 생각했는데
그것도 fk 설정이나 orphanRemoval 설정이 걸려있지 않아 이유를 잘 모르겠네요 😅

2021-09-02 06:37 UTC, woowahan-pjs approved these changes
고생하셨습니다. 👍

2021-09-02 06:38 UTC, merged