refactor(apply): abstract the control component logic
woowacourse/service-apply pull request #319
Opened 2021-09-05 15:51 UTC by seojihwan

- formProvider를 통해 폼단위의 로직 공통화
  - form, input, submitButton의 onChange, value, errorMessage, onSubmit, disabled 추상화
- 페이지에 적용

2021-09-07 03:56 UTC, SunYoungKwon commented on frontend/src/components/form/BirthField/BirthField.js
> +      </p>
components/form내에 `RuleField`라는 컴포넌트가 이미 존재합니다! 그 컴포넌트를 가져다 사용하는 것은 어떨까요?

2021-09-07 10:23 UTC, woowapark requested changes
변경 사항이 생각보다 많네요..!     
제일 메인으로 바꾼 건 FormContext 를 만들고 register/unregister 하는 식으로     
기존에 반복되는 로직을 빼낸 부분인 것 같은데,          
개인적으로는 직접 register하고, unregister 도 cleanup시에 챙겨서 해주는 걸 반복해서 써주는 부분이      
휴먼에러로 빼먹기 쉬울 것 같다는 우려는 조금 듭니다.        
FormContext 내부를 고려해서, 어떻게 사용해야 하는 지에 대한 사용법을 추가로 익혀야 하는 느낌이 있는데       
이런 부분은 괜찮을까요? 

@SunYoungKwon @jho2301 
썬&파노 읽고 이해하거나 이후 같은 코드를 수정해야 할 때 이슈가 될 만한 부분이 있을지      
리뷰 의견 부탁드릴게요~

+) 이 변경사항으로 영향 받는 기능 요구사항들의 정상동작은 모두 테스트 되었을까요? 
어떤 요구사항들을 확인해보아야 하나요?

2021-09-07 10:23 UTC, woowapark commented on frontend/src/provider/FormProvider/FormProvider.js
> +    const validator = validators?.[target.name];
저희 IE 지원 필요하던가요...?-?      
필요하다면 `?.` 연산자 지원범위 확인이 필요해보입니다.  
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2021-09-07 10:23 UTC, woowapark commented on frontend/src/provider/FormProvider/FormProvider.js
> +      setErrorMessage((prev) => ({ ...prev, [target.name]: error.message }));
validator 로직이 setValue를 하는 것보다 먼저 있을 필요는 없나요?

2021-09-07 12:02 UTC, seojihwan commented on frontend/src/provider/FormProvider/FormProvider.js
> +      setErrorMessage((prev) => ({ ...prev, [target.name]: error.message }));
validate가 실패한 경우 error를 throw해서 cach블록으로 넘어가게되는데, 
validator가 먼저 동작하는 경우에는 잘못된 사용자 입력이 화면에 나타나지 않고 에러메시지만 나타나서 사용자가 에러메시지를 이해하기 힘들 수 있을 것 같아요.

2021-09-07 12:02 UTC, seojihwan commented on frontend/src/components/form/BirthField/BirthField.js
> +      </p>
기존에 RuleField컴포넌트를 사용하지 않고있는데 삭제하는것은 어떨까요?

2021-09-07 12:15 UTC, SunYoungKwon requested changes
지원자 정보 입력 페이지에서 비밀번호 확인을 알맞게 입력해도 오류메세지가 사라지지 않아 다음 버튼이 활성화되지 않는 버그가 있습니다. 확인부탁해요!

2021-09-07 12:15 UTC, SunYoungKwon commented on frontend/src/components/form/TextField/TextField.module.css
> +}
현재 오류메세지가 없다가 나타나는 경우 기존 요소들을 밀어냅니다. 메세지가 나타나지 않았을 때도 일정한 영역을 차지하고 있으면 좋겠습니다.

![input_error_message](https://user-images.githubusercontent.com/45230497/132341145-166d9c21-c864-457e-ac75-79247839af9f.gif)

2021-09-07 12:15 UTC, SunYoungKwon commented on frontend/src/pages/ApplicantRegister/ApplicantRegister.js
> +  }) => {
코드가 정말 많이 줄어드네요 👍

2021-09-07 12:17 UTC, SunYoungKwon commented on frontend/src/components/form/BirthField/BirthField.js
> +      </p>
삭제하는것도 괜찮은 것 같습니다ㅋㅋㅋ

2021-09-07 12:33 UTC, seojihwan commented on frontend/src/components/form/TextField/TextField.module.css
> +}
적용했습니다!

2021-09-07 12:33 UTC, seojihwan commented
우선은 서버를 켜서 직접 모든 기능이 정상 동작하는지 확인하지 않고 
네트워크요청에 request Header에 정상적으로 값이 실리는지를 확인했습니다.

![image](https://user-images.githubusercontent.com/52202474/132345200-7cc9e61f-b4da-4448-add9-0fdc52c49037.png)

2021-09-07 16:42 UTC, jho2301 reviewed
브랜 고생했어요
리뷰 남겼으니 답변 부탁드려요
저는 이만 자러..

2021-09-07 16:42 UTC, jho2301 commented on frontend/src/provider/FormProvider/FormProvider.js
> +    </FormContext.Provider>
FormProvider랑 Form태그를 분리하면 어떨까요?

 Provider와 Form이 각자 맡는 역할이 달라서 분리시켜주는게 좋다고 생각합니다. 
Provider는 레이아웃에 영향을 끼치지 않고 value를 전달해주는 Provider의 역할만 하는 것이 이후에 읽는 사람이 걸리는 부분 없이 받아들일 수 있지 않을까요?

2021-09-07 16:42 UTC, jho2301 commented on frontend/src/provider/FormProvider/ResetButton.js
> +        }
인라인함수에 제어문이 들어가면 한 번에 받아들이기 힘들 것 같아요. 별도 함수로 정의하면 어떨까요?

2021-09-08 00:31 UTC, seojihwan commented on frontend/src/components/form/BirthField/BirthField.js
> +      </p>
ui상 에러메시지는 하나만 표현되어야해서 이런 형식으로 구현되었는데, 여러 메시지가 필요하다면 ui형태를 바꾸어 줄 필요가 있어보입니다.

2021-09-08 00:45 UTC, seojihwan commented on frontend/src/provider/FormProvider/FormProvider.js
> +    </FormContext.Provider>
FormProvider와 Form태그는 따로 쓰일 수 없는 상황이라고 생각했습니다.
같이 묶여 사용해야하고, 내부적으로 Form태그를 은닉했을때 사용자의 실수를 줄여줍니다.

외부페이지에서 Form을 사용할때 submit 이벤트 핸들러등을 매번 정의하여 사용한다면 추상화 정도가 망가지는 문제, 코드 중복이 발생할 것으로 보입니다.

지금코드는 내부로직을 확인해야하지만 생산성에 있어 더 효율적이지 않을까요?

form태그를 분리한다면 내부 input들의 value나 유효성 정보등을 받아서 다시 form에서 처리해야하는데 코드 구조가 간단하게 처리 될 수 있을지 모르겠습니다. 추상화를 포기한 방식에서 코드 가독성이라는 이점을 얻을 수 있을지 모르겠네요.
대략적인 수도코드나 방법을 제시해주시면 감사하겠습니다.

2021-09-08 01:26 UTC, jho2301 commented on frontend/src/provider/FormProvider/FormProvider.js
> +    </FormContext.Provider>
1. 추상화는 내부의 코드를 보지않고도 어떻게 동작해야하는지 사용자가 추측할 수 있어야 적절하게 적용이 됐다고 할 수 있는데 ,  내부 로직을 확인해야한다면 이것이 적절한 추상화인가 생각해봐야할 것 같습니다. 

2. Form태그를 children으로 받아서 관리하면 Provider와 Form태그가 분리된다 것이 제안입니다

2021-09-09 03:04 UTC, woowapark commented on frontend/src/provider/FormProvider/FormProvider.js
> +    </FormContext.Provider>
#### 참고
- FormProvider 와 Form 엘리먼트를 구분하는 방식 ref
  : https://react-hook-form.com/api/useformcontext/ 
- 현재 상태를 hook으로 취급하는 방식 ref
  : https://github.com/streamich/react-use/blob/master/docs/useAudio.md

2021-09-09 06:27 UTC, seojihwan commented on frontend/src/provider/FormProvider/ResetButton.js
> +        }
함수 네이밍을 추천해주실것이 있을까요??

2021-09-09 07:23 UTC, jho2301 commented on frontend/src/provider/FormProvider/ResetButton.js
> +        }
onReset 어떤가요?

2021-09-09 07:46 UTC, seojihwan commented on frontend/src/provider/FormProvider/ResetButton.js
> +        }
react 공식문서나 다른 레퍼런스를 참조했을때 이벤트에 대한 동작을 처리하는 핸들러 네이밍은 handle prefix를 사용하는데 handleReset은 어떠신가요?
![image](https://user-images.githubusercontent.com/52202474/132644456-707ada44-1dc0-4ef7-b4c7-6a0b2f1cc9a4.png)
![image](https://user-images.githubusercontent.com/52202474/132644542-c91ad3c3-ac28-432a-9248-85561ff492b7.png)

2021-09-09 07:56 UTC, seojihwan commented on frontend/src/provider/FormProvider/ResetButton.js
> +        }
생각해보면 click이벤트를 다루는 것이므로 handleClick이 괜찮은 대안이라고 생각되지만,
기능을 알려주면 더 좋은 네이밍이 될것같아 reset with confirm 이런정도의 네이밍이 될것같네요..

2021-09-09 08:12 UTC, woowapark commented on frontend/src/provider/FormProvider/ResetButton.js
> +        }
- 개인적으로 브랜이 의견 주신 것처럼 네이밍에서 기능이 드러나는 걸 선호하는 편입니다 :)  
- 다만 현재 예시는 아예 `ResetButton`컴포넌트 내부라서 클릭하면 reset이 된다는 걸 컴포넌트 자체에서 알 수 있고, 다른 기능도 없는 상태라 handleClick처럼 핸들러 이름만 넣는 것도 충분하지 않을까 싶어요         

브랜 판단대로 적용해주시면 될 것 같아요~!

2021-09-09 08:24 UTC, seojihwan commented
이야기 나눈 대로 수정 완료했습니다! 충돌은 approve 이후에 해결해보겠습니다.

2021-09-10 06:32 UTC, woowapark approved these changes
수정 사항 확인하였습니다~ 
브랜 논의에 수정까지 고생 많으셨어요! 

@jho2301 @SunYoungKwon 
파노, 썬도 추가 확인 부탁드려요~

브랜
오늘 중까지 추가 의견 특별히 없다면 제이슨에게 머지 요청해주세요~!

2021-09-10 13:53 UTC, SunYoungKwon approved these changes

2021-09-10 13:57 UTC, jho2301 approved these changes

2021-09-12 08:04 UTC, seojihwan commented
@woowahan-pjs  머지 요청드립니다!

2021-09-12 09:06 UTC, woowahan-pjs approved these changes
고생하셨습니다. 👍

2021-09-12 09:09 UTC, merged