feat(authentication): implement the authentication code generation function
woowacourse/service-apply pull request #335
Opened 2021-09-14 14:38 UTC by knae11

- 기존에 만들어진 코드를 사용하여 email을 기준으로 인증코드를 생성하고, 해당 인증 코드를 받아 mail로 보내주는 api 를 구현하였습니다.
- 이메일 인증이 아니라 이메일인증코드 요청 API를 구현하다는 제목에 맞게 코드를 생성하여 요청하는 API를 구현하였습니다.
- ~이슈에 적혀있는 내용은 이메일 인증과 관련된 로직이 섞여있다고 생각하였고, 이메일 인증과 관련된 API는 `@PostMapping("/authenticate-email")`에 구현되어 있다고 판단하였습니다.~
- 이미 존재하는 이메일인 경우(이미 인증되어 가입된 이메일, 이미 인증된 이메일)를 확인하여 예외를 발생시켰습니다.

Closes #326

2021-09-16 14:48 UTC, woowahan-pjs requested changes
인증 코드 만료 기능을 구현하는 것은 어떨까요? 생성 일시를 기준으로 만료를 구현하거나 만료 일시를 직접 관리할 수 있습니다. 생성 후 만료까지는 10분이 적절해 보여요.

2021-09-16 14:48 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/ApplicantAuthenticationService.kt
> +        applicantRepository.findByEmail(email)?.let { throw IllegalStateException() }
이메일이 이미 등록되어 있는지를 메시지로 알려 주는 것이 좋을지는 고민이지만, `check()`를 사용하는 것이 코드를 이해하기에 더 좋은 것 같아요.

```suggestion
        check(!applicantRepository.existsByEmail(email)) { "이미 등록된 이메일입니다." }
```

2021-09-16 14:48 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/ApplicantAuthenticationService.kt
> +        check(!authenticationCodeRepository.existsByEmailAndAuthenticatedTrue(email))
바로 위의 코드로 충분해 보여요.

2021-09-16 14:48 UTC, woowahan-pjs commented on src/test/kotlin/apply/application/ApplicantAuthenticationServiceTest.kt
> +                { assertThat(generatedAuthenticationCode).isEqualTo(authenticationCode.code) },
```suggestion
            val actual = applicantAuthenticationService.generateAuthenticationCode(authenticationCode.email)
            assertAll(
                { assertThat(actual).isEqualTo(authenticationCode.code) },
```

2021-09-16 14:48 UTC, woowahan-pjs commented on src/test/kotlin/apply/application/ApplicantAuthenticationServiceTest.kt
> +                { assertThat(authenticationCode.authenticated).isFalse() }
`authenticationCode`를 테스트한다는 것은 어떤 의미가 가질까요?

2021-09-17 01:43 UTC, knae11 commented
생성할 때, 넣어준 code 가 일치하는 지 여부를 확인하는 것이라고 생각했는데, notNull 또는 테스트 하지 않아도 될 것 같네요 :)

2021-09-17 01:43 UTC, knae11 commented on src/test/kotlin/apply/application/ApplicantAuthenticationServiceTest.kt
> +                { assertThat(authenticationCode.authenticated).isFalse() }
생성할 때, 넣어준 code 가 일치하는 지 여부를 확인하는 것이라고 생각했는데, notNull 또는 테스트 하지 않아도 될 것 같네요 :)

2021-09-17 07:30 UTC, knae11 commented on src/test/kotlin/apply/application/ApplicantAuthenticationServiceTest.kt
> +                { assertThat(authenticationCode.authenticated).isFalse() }
service 에서 리턴해주는 값이 `authenticationCode.code` 가 맞는지 확인해보는 테스트가 필요하다고 생각했었어요! ㅎㅎㅎ 혹시 어떤 의미인지 조금 더 설명해 주실 수 있을까요?ㅎㅎ

2021-09-17 07:30 UTC, knae11 commented on src/test/kotlin/apply/application/ApplicantAuthenticationServiceTest.kt
> +                { assertThat(generatedAuthenticationCode).isEqualTo(authenticationCode.code) },
수정하였습니다 :)

2021-09-17 07:31 UTC, knae11 commented on src/main/kotlin/apply/application/ApplicantAuthenticationService.kt
> +        applicantRepository.findByEmail(email)?.let { throw IllegalStateException() }
반영하였습니다:)

2021-09-17 07:46 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/ApplicantAuthenticationService.kt
> +        applicantRepository.findByEmail(email)?.let { throw IllegalStateException() }
쿼리 메서드가 아닌 `@Query`를 사용한 이유가 궁금해요!

2021-09-17 07:46 UTC, woowahan-pjs commented on src/test/kotlin/apply/application/ApplicantAuthenticationServiceTest.kt
> +                { assertThat(authenticationCode.authenticated).isFalse() }
`{ assertThat(authenticationCode.authenticated).isFalse() }`에 대한 이야기입니다!

2021-09-17 08:20 UTC, knae11 commented
- @woowahan-pjs 만료시간과 관련된 로직은 authenticate() 부분에 추가하였는데 어떤지 궁금하네요 :)
```
fun authenticate(code: String) {
        check(!authenticated) { "이미 인증되었습니다." }
        require(this.code == code) { "인증 코드가 일치하지 않습니다." }
        check(createdDateTime.plusMinutes(EXPIRY_MINUTE_TIME) > LocalDateTime.now()) { "인증 코드가 만료되었습니다." }
        authenticated = true
    }
```

2021-09-17 08:27 UTC, knae11 commented on src/test/kotlin/apply/application/ApplicantAuthenticationServiceTest.kt
> +                { assertThat(authenticationCode.authenticated).isFalse() }
아하 초기값이 false로 잘 셋팅되어 있는지 확인하려고 했던 것인데, 이 부분은 필요 없다면 삭제할게요 :)

2021-09-17 08:36 UTC, knae11 commented on src/main/kotlin/apply/application/ApplicantAuthenticationService.kt
> +        applicantRepository.findByEmail(email)?.let { throw IllegalStateException() }
다른 레포짓토리 메소드를 따라가기 위해서 `@Query` 를 사용하였는데, `existsByInformationEmail` 로 사용하는 것이 더 좋다고 생각하시는 걸까요? 👀

2021-09-19 01:37 UTC, NewWisdom approved these changes
럴배럴 !!!
작업하신 내용 잘 확인했습니다.
빠르고 깔끔하게 잘 작업해주셨네요 👏👏
덕분에 배워갑니당 멋쟁이 진짜 !
수고 많으셨습니다 🔥🔥

2021-09-19 01:37 UTC, NewWisdom commented on src/main/kotlin/apply/domain/applicant/ApplicantRepository.kt
> +fun ApplicantRepository.existsByEmail(email: String): Boolean = existsByInformationEmail(email)
여기에 확장함수 쓰는건 생각도 못해봤는데...
짱짱짱👏👏

2021-09-19 01:37 UTC, NewWisdom commented on src/main/kotlin/apply/ui/api/ApplicantRestController.kt
> +        return ResponseEntity.status(HttpStatus.NO_CONTENT).build()
```suggestion
        return ResponseEntity.noContent().build()
```
위에랑 동일하게 맞춰주면 좋을 것같아요!

2021-09-19 02:25 UTC, ddaaac reviewed
고생하셨어요!

2021-09-19 02:25 UTC, ddaaac commented on src/main/kotlin/apply/domain/authenticationcode/AuthenticationCode.kt
> +        check(expiryDateTime > LocalDateTime.now()) { "인증 코드가 만료되었습니다." }
```suggestion
        check(LocalDateTime.now().isBefore(expiryDateTime)) { "인증 코드가 만료되었습니다." }
```

이건 정말 제 개인적인 견해인데 날짜/시간은 부등호 비교보다 `isBefore` 등의 메서드 사용하는게 보기 편하더라구요.
부등호 비교가 더 읽기 좋다고 생각하시면 그대로 두셔도 좋습니다 ㅎㅎ

2021-09-19 02:48 UTC, knae11 commented on src/main/kotlin/apply/ui/api/ApplicantRestController.kt
> +        return ResponseEntity.status(HttpStatus.NO_CONTENT).build()
반영해주었습니다~

2021-09-19 02:52 UTC, knae11 commented on src/main/kotlin/apply/application/ApplicantAuthenticationService.kt
> +    fun generateAuthenticationCode(email: String): String {
오~ [회원가입을 구현한다 이슈](https://github.com/woowacourse/service-apply/issues/329) 가 있는 것으로 보아 todo 로 남겨둘게요 :)

2021-09-19 02:58 UTC, knae11 commented on src/main/kotlin/apply/domain/authenticationcode/AuthenticationCode.kt
> +        check(expiryDateTime > LocalDateTime.now()) { "인증 코드가 만료되었습니다." }
오! `.isBefore` 메소드 좋네요 👍

2021-09-19 04:13 UTC, woowahan-pjs commented on src/main/kotlin/apply/domain/authenticationcode/AuthenticationCode.kt
> +        check(expiryDateTime > LocalDateTime.now()) { "인증 코드가 만료되었습니다." }
앗! 저는 부등호에 한 표!

2021-09-19 04:42 UTC, knae11 commented on src/main/kotlin/apply/domain/authenticationcode/AuthenticationCode.kt
> +        check(expiryDateTime > LocalDateTime.now()) { "인증 코드가 만료되었습니다." }
오~ 그렇다면 전 둘다 괜찮으므로 앞으로 계속 같이 작업할 제이슨의 의견에 따라 변경하겠습니다~ 혹시 다른 분들도 의견있다면 남겨주세요ㅎㅎㅎ

2021-09-19 08:11 UTC, Rok93 approved these changes
배럴 고생 많으셨어요!! 👍
작업 잘 진행해주셨네요 😃  

한 가지 궁금한 점은 전체 테스트를 돌렸을 때, `AuthenticationCodeRepositoryTest#가장 최근에 생성된 인증 코드를 조회한다` 테스트가 실패하는데 저만 그런건가요!? (배럴이 작업한 내용과는 무관한 듯하여 approve 했습니다) 

추석 잘 보내세요~ 😄

2021-09-20 08:10 UTC, Sehwan-Jang commented on src/main/kotlin/apply/domain/authenticationcode/AuthenticationCode.kt
> +        check(expiryDateTime > LocalDateTime.now()) { "인증 코드가 만료되었습니다." }
저는 당장은 `isBefore` 로 비교하는게 더 빠르게 이해가는데, 익숙해지면 부등호가 더 직관적일 것 같네요~
저희끼리 볼거라면 부등호로 하고 익숙해져보는 것도(?) 좋을 것 같아요 ㅋㅋ

2021-09-20 08:37 UTC, Sehwan-Jang approved these changes
몇가지 참신한 시도들이 보이는 pr이네요 👍👍👍
많이 배워갑니다 수고하셨어요!

2021-09-20 08:37 UTC, Sehwan-Jang commented on src/main/kotlin/apply/application/ApplicantAuthenticationService.kt
> +        check(!applicantRepository.existsByEmail(email)) { "이미 등록된 이메일입니다." }
회원 도메인이 적용된다면 userRepository로 바뀌어야 하긴 하겠네요 :)

2021-09-20 12:32 UTC, knae11 commented on src/main/kotlin/apply/domain/applicant/ApplicantRepository.kt
> +fun ApplicantRepository.existsByEmail(email: String): Boolean = existsByInformationEmail(email)
네 결국 서비스에서 호출하고 싶은건 `@Embedded` 타입인지는 상관이 없고 Email로 조회하는지 여부라고 생각해요. 따라서 Information이 들어가면서 길어지는 것도 가독성 측면에서도 안 좋다고 생각하였습니다.

처음에는 `@Query`로 작성되었는데, exists 를 사용하면서 `@Query`를 사용하는 것은 DB마다 다르게 동작할 수 있어 exists를 쿼리문으로 작성하는 것은 조금 위험하다고 하더라구요. 따라서 확장함수를 사용하여 변환해주었습니다 :)

2021-09-20 12:34 UTC, knae11 commented on src/main/kotlin/apply/application/ApplicantAuthenticationService.kt
> +        check(!applicantRepository.existsByEmail(email)) { "이미 등록된 이메일입니다." }
맞아요. 추후에 회원 도메인이 적용된다면 바뀌어야 할 로직들이 여럿있을 것 같은데 이 부분도 그 중 하나일 듯 싶네요! ㅎㅎㅎ

2021-09-20 12:37 UTC, knae11 commented
@Rok93 저는 테스트가 잘 돌아가고 있어서요ㅠㅠ 혹시 문제가 되는지 다시 한번만 더 확인해 주실 수 있나요? 👀 어떤 부분에서 문제가 되는지 궁금하네요ㅠㅠ

![image](https://user-images.githubusercontent.com/66905013/134003339-9ff2c3a5-3e4b-4725-af68-4a34fbcbac18.png)

2021-09-20 12:38 UTC, knae11 commented on src/main/kotlin/apply/domain/applicant/ApplicantRepository.kt
> +    fun existsByInformationEmail(@Param("email") email: String): Boolean
오!! 놓친 부분 잘 찾아주셔서 감사합니다! 반영하였습니다:)

2021-09-21 02:27 UTC, ddaaac commented
@Rok93 @knae11 

`@RepeatableTest`로 1000번씩 돌려보니깐 3~10건 정도가 깨지네요 
(이유는 테스트 결과를 보고 찾아보시는 게 좋을 거 같아요 😀)

테스트는 약간 수정하면 될 거 같고, 프로덕션 환경에서는 정말 드물게 발생할 수 있을 거 같은데 거기까지 고려해야하는지는 논의를 해보는 게 좋겠네요

2021-09-21 05:02 UTC, knae11 commented
## 테스트 깨지는 원인 분석
![image](https://user-images.githubusercontent.com/66905013/134113907-e409e178-9227-40c7-b589-57037bf1a44a.png)
- datetime(6) 의 의미는 Fractional Seconds 를 6자리까지 구분해주겠다는 의미
- 6자리 밑의 구분은 rounding이 되어 구분이 안 됨
- 컴퓨터가 빠르면 `LocalDateTime.now()`를 하였을 때, 6자리 이하의 유의미한 값으로 구분될 수 있어 마지막 시간이 동일하게 들어갈 수 있어 테스트가 깨지게 된 것으로 추측
- [fractional seconds 참고](https://dev.mysql.com/doc/refman/5.7/en/fractional-seconds.html)

2021-09-21 09:56 UTC, woowahan-pjs approved these changes
고생하셨습니다. 👍

2021-09-21 10:02 UTC, merged