feat: implement send email page
woowacourse/service-apply pull request #337
Opened 2021-09-16 06:11 UTC by Rok93

# 작업 내용 
* 그룹 발송 기능 
* 개별 발송 기능 

## 구현하지 못한 부분 
* `모든` 평가 상태를 조회하는 경우 
`GroupMailFormView#createEvaluationStatusItem` 부분을 적절히 수정하면 될 것 같은데... 
이 부분은 하드코딩하는 방법 말고는 없을까요...? 🤔  

## 사용법 

### 1. 관리자 화면에서 `메일 발송` 탭 클릭 
![image](https://user-images.githubusercontent.com/47850258/133557167-ba111e28-1b13-4ffa-8633-3fbfbdea86f4.png)

### 2. `그룹 발송` 혹은 `개별 발송` 버튼 클릭 
![image](https://user-images.githubusercontent.com/47850258/133557252-731dd6ea-9327-4b87-8bd7-94aa942ef108.png)

### 3. 기본적으로 메일 폼은 아래와 같다. 
> `개별 발송`과 `그룹 발송`은  *수신자를 고르는 컴포넌트만 다르다!* (화면이 잘리는데 하단에 전송 버튼 있음)

> 그룹 발송
> 그룹 발송의 경우 `모집`, `평가`, `평가 상태`를 클릭하면 해당 조건에 맞는 `mailTargets`들을 수신자로 추가한다. 
![image](https://user-images.githubusercontent.com/47850258/133557383-21f7a93c-6a73-4b5e-86bc-5634aea12f10.png)

> 개별 발송 
* 개별 발송의 경우 수신자를 `직접 추가`하거나 플랫폼의 지원자들을 keyword 검색(= email or 이름 의 일부)하여 검색하여 추가(= 지원자 검색 버튼으로 접근)할 수 있다. 
![image](https://user-images.githubusercontent.com/47850258/133557521-de1fed11-d648-4815-8d68-271994006ec4.png)

> 수신자를 추가하면 화면 상에 추가 된 수신자가 `초록색 텍스트박스`로 출력된다.  우측에 `X` 버튼을 클릭하면 해당 수신자는 수신자 리스트에서 제거할 수 있다. (그룹 발송, 개별 발송 모두 동일하게 적용)

![image](https://user-images.githubusercontent.com/47850258/133558011-e2744197-eafa-4192-867a-9ff7573c97bd.png)

## 동작 확인 

그룹 발송 기능 - (MailTargetService 동작 확인)
> 2기 FE의 `자소서` 평가 항목에서 3명의 지원자가 있고 각 상태는 아래와 같습니다. 
* 손흥민 : 제출(10점) 합격 
* 네이마르 : 제출(2점) 탈락
* 즐라탄이브라히모비치: (미제출 = 0점) 탈락
![ED96CB39-9A05-4B9C-BB9A-A9D5969787D5](https://user-images.githubusercontent.com/47850258/133556711-65128c99-5fd4-4057-8b2b-25b9b8a7ef68.png)

### 그룹 필터링 (합격)
![F5E040D9-6729-4F92-BF01-87935F93C35F](https://user-images.githubusercontent.com/47850258/133556747-d9cafc31-57f1-456b-832f-f534bbc63de8.png)
### 그룹핑 결과
![CA115674-6DE6-4403-BEA3-CCB5E5DFE570](https://user-images.githubusercontent.com/47850258/133556769-92441edb-396f-4093-90cc-9e7c3e2c5559.png)

---
### 그룹 필터링 (불합격) 

![98659574-787B-45BB-B887-976E57ECD558](https://user-images.githubusercontent.com/47850258/133556787-38093c20-6409-4952-b36a-0aba0ccf0234.png)
### 그룹핑 결과 
> 미제출자인 `즐라탄이브라히모비치`는 메일 발송 대상에 선정이 안됌 (정상적으로 동작)
![88396E2F-381E-4BC7-AA26-EDC4F75BAC88](https://user-images.githubusercontent.com/47850258/133556814-c343c5d8-0e8e-4acc-a4b9-148ac313bc07.png)

### 이미지 업로드 기능 
> 용량이 초과하면 이미지 파일을 업로드할 수 없다. (https://vaadin.com/docs/v14/flow/components/tutorial-flow-upload) 참고하여  `setMaxFiles` 메서드 사용할 것! (자바 기준, 코틀린은 필드로 접근하여 값을 직접 할당)
![58101332-CF4B-4ED0-88FF-1C578F93A3C1](https://user-images.githubusercontent.com/47850258/133556848-68aa2e12-ce2e-4951-afb0-edba744bb810.png)
![0C6FBEE0-2AB1-4C3F-9597-31E58D69C37D](https://user-images.githubusercontent.com/47850258/133556866-0683aa73-1647-4402-b200-57ea39945e00.png)

> 용량만 초과하지 않는다면, 이미지 갯수는 상관없는 것 같다. 
![1D651303-79EA-4777-B6EC-389D579006CB](https://user-images.githubusercontent.com/47850258/133556911-994e4a26-fba4-456b-815c-c9ef52ca5292.png)

> 용량을 변경하고 싶다면…  [Upload | Using Vaadin Components | Flow | Vaadin 14 Docs]
> 용량 제한 변경 방법 예시 (숫자는 아무 숫자나 입력한 것이니 참고만 할 것!)
![9F15740B-7A61-433A-9196-2F2BE98DF87C](https://user-images.githubusercontent.com/47850258/133557052-882a7d6d-e442-442d-9ae4-b193286971d7.png)

### 이미지 파일을 업로드했을 때…. 포맷
Http-Server 미션 때 배운내용을 활용하여… OutputStream을 생각하면 되는건가…? 
Mail 전송할 때, 어떤 타입이 필요한지를 알아서, 최대한 그 타입으로 미리 만들면 좋을 것 같음. 

### MultiFileMemoryBuffer class에 대한 고찰 
Buttons 파일에 `ImageUpload Button`을 구현하였고 코드는 아래와 같다. 
```kotlin
fun createImageUpload(
    text: String,
    receiver: MultiFileMemoryBuffer,
    succeededListener: UploadSucceededListener
): Upload {
    return Upload(receiver).apply {
        setAcceptedFileTypes("image/jpeg", "image/png", "image/gif")
        uploadButton = createPrimaryButton(text) { }
        addSucceededListener {
            receiver.getInputStream(it.fileName)
        }
    }
}
```

[Upload | Using Vaadin Components | Flow | Vaadin 14 Docs](https://vaadin.com/docs/v14/flow/components/tutorial-flow-upload) 참고 

* The MultiFileMemoryBuffer class is a ready-made implementation of MultiFileReceiver.
* *The data is stored in files on the file system and you can get the data* using a `file name` and the `getInputStream(String)` method. 

## 메일 용어 참고 
[What is a Message Body?](https://www.computerhope.com/jargon/m/messbody.htm)
* subject: 메일 제목 
* recipient: 수신자 
* body: 메일 본문
* (MailFormView의 `currentRecipients`는 현재 선택된 수신자들을 Text Component로 가지는 `HorizontalLayout` ) 

Closes : #304

2021-09-22 15:34 UTC, knae11 reviewed
상당히 많은 부분을 구현해주셨네요! 

여러개 넣고 동작시켜보았어요. 사실 제가 바딘 작업을 거의 안 해서 잘 모르긴 하지만, 사용자라고 생각하고 몇가지 의견 남겨보았어요!ㅎㅎㅎ 혹시 작업 범위를 벗어난 작업이거나 어려운 작업을 요청드린 거라면 알려주세요!ㅎㅎㅎㅎㅎ

2021-09-22 15:34 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +        val receivers = VerticalLayout(H4("수신자"), createReceiverFilter())
수신자 목록이 모집, 평가, 모집상태 하부에 뜨는게 어떨까요?

2021-09-22 15:34 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +                println("title: ${title.value}  receivers: ${this.receivers}  content: ${this.content.value}")
혹~시 제가 해당 print문을 못찾는 걸까요?ㅠㅠㅠ

2021-09-22 15:34 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +            mailBody,
```
VerticalLayout(currentRecipients.apply { setSizeFull() }),
VerticalLayout(uploadFile),
```
### 기존
![image](https://user-images.githubusercontent.com/66905013/134371870-881160cb-c6e7-4b5e-a7af-458267f0e282.png)

### 수정후

![image](https://user-images.githubusercontent.com/66905013/134371801-27e8fe9b-20b5-4b27-9b90-bdf2862a96dd.png)

이렇게 해주면 해당 라인이 맞아져요.ㅎㅎㅎ 이거 VerticalLayout이 들어가게 메소드로 빼서 예쁘게 코드 수정해 주셔도 좋을 듯 싶어요! :)

2021-09-22 15:34 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +            style.set("background-color", "#00B493")
혹..시 초록색 배경은 어떤 이유인가요?ㅎㅎ

2021-09-22 15:34 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +    private val currentRecipients = HorizontalLayout()
![image](https://user-images.githubusercontent.com/66905013/134373332-f1d5937f-0f9a-4a9c-acfe-0a9cf97cd6ee.png)
ㅠㅠㅠㅠ 저 바딘 잘 몰라서 사실 잘 모르는데... 갯수가 많아지면 옆으로 계속 늘어날 것 같은데 이건 괜찮까 싶네요!
단체메일보내면 꽤 많을 듯 싶어서요.
더불어..`x`의 위치도 아래로 변경됩니당!

2021-09-22 15:34 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +    private val currentRecipients = HorizontalLayout()
개별 조회에서 `지원자 조회` 탭을 누르지 않고 test 하고 엔터만 치면 그대로 입력되는데 이것도 괜찮을까요..? 해당하는 이메일을 불러와야 하지 않을까 싶어서요 혹은 엔터 칸을 없애야하지 않을까 싶기도 해요! 로키의 작업범위가 아니라면 알려주세요~ㅎㅎㅎ

2021-09-22 15:34 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +                add(createRecipientComponent(it))
![image](https://user-images.githubusercontent.com/66905013/134374324-7192206c-387e-4b9a-946d-fd8842b5360c.png)
여러개를 추가할 때, 추가되어도 옅은 색으로만 바뀌어서 좀 헷갈리는 것 같아요. 추가가 되면 `추가` -> `삭제`로 변경되거나 색 대비를 더 주어도 좋을 것 같다는 생각이 들어요! 혹시 어려운 작업이라면 반영하지 않으셔도 좋습니다!ㅎㅎㅎ

2021-09-22 17:58 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +            style.set("background-color", "#00B493")
아.... 배민 색을 따온건데.... 👀 
다들 이 색상에 대한 궁금증을 가지시더라구요 😅 
무난한 회색으로 변경하였습니다. 😃

2021-09-22 17:59 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +            mailBody,
현재 대대적인 개편작업 중인데, 때마침 이 부분은 배럴이 코멘트 남겨주신 것과 동일하게 변경했네요! 👍

2021-09-22 18:02 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +                println("title: ${title.value}  receivers: ${this.receivers}  content: ${this.content.value}")
어.... 이 부분은  아직 `emailService`에 지금의 기능에 적합한(?) 메일 전송 기능이 구현되어 있지 않아 비워뒀습니다. 
print문만 두면 오해의 여지가 있을 것 같아 현재는 `todo`로 표시해두었습니다. 

혹시 전송 버튼을 눌러도 콘솔 창에 출력이 안된다는 말씀이신가요?? 🤔

2021-09-22 18:07 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +    private val currentRecipients = HorizontalLayout()
엔터 키를 누르거나 혹은 엔터 버튼을 눌렀을 때, 직접 작성한 이메일이 등록되는 기능은 [이슈](https://github.com/woowacourse/service-apply/issues/304)의 내용 중 일부인 아래의 요구사항 때문에 추가한 기능입니다. 
현재 저희 지원 페이지에 가입되어있는 이메일이 아니더라도 메일을 보낼 수 있도록하기 위함입니다  😃
(물론 이메일양식에 맞지 않는 이메일을 등록한다거나... 등등 여러가지 예외 사항들을 잡으면 좋겠지만... 그 부분까지는 고려하지 못했네요 🥲)

### 요구사항 중 일부
* 메일 주소를 직접 입력하여 특정한다.
    * 테스트 등을 위해 직접 메일주소를 입력하여 발송할 수 있어야 한다.
    * 발송할 메일 주소 입력 UI를 구현한다.
```

2021-09-22 18:26 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +                add(createRecipientComponent(it))
이 부분은 저도 변경해보고 싶었는데... component를 replace 하도록 해보려했는데... 생각한대로 잘 안돼서 지금처럼 Disable로 변경했는데... 음 일단은 지금 방식이 최선이었는데  이 부분은 혹시 추가 버튼 클릭 시에, 삭제 버튼(다른 버튼)으로 변경할 수 있는 방법 아시는 분...의 제보를 받습니다 ... 썸바딘 헬프 유...

2021-09-22 18:55 UTC, Rok93 commented
# 변경사항 

> 피드백 받은 내용을 토대로 변경된 사항 

### `개별 발송`, `그룹 발송`을  하나의 페이지로 구현 
![image](https://user-images.githubusercontent.com/47850258/134400780-20aa72ff-c87e-4a3c-8ee3-9e59b7efe9a7.png)
* 불러오기 (=기존 개별 발송 기능), 그룹 불러오기 (=기존 그룹 발송 기능)
* 각 기능들은 `Dialog`로 구현하였고, 각각 Dialog를 상속받은 컴포넌트 클래스를 만들었습니다. (MailFormView 클래스의 크기가 너무 커져서 분리하였습니다) 

### `보낸사람` 추가 
![image](https://user-images.githubusercontent.com/47850258/134401254-3ce47512-f3a6-4c29-ad8e-0d4df5f048ef.png)

* 보낸 사람은 applicaion-properties의 email 주소로 고정됩니다. (local 환경에서는 EMAIL) 

### `그룹 보내기` 기능 
* 특정 지원, 평가, 평가 상태를 선택하면 아래에 조회된 mailTarget들을 표시한다. 
* `추가` 버튼을 누르면, `받는사람`에 추가된다.

![image](https://user-images.githubusercontent.com/47850258/134401908-fde9c1d7-6b41-482f-ae7a-30fee9f22a79.png)

> 추가 이후
![image](https://user-images.githubusercontent.com/47850258/134402118-381120b8-33d7-44a3-a88a-3a084e431855.png)

### `불러오기` 기능 (= 개별 발송)

* keyword(= 이메일 or 이름) 입력하여 조회  
* 추가하고 싶은 사용자 `추가` 버튼 클릭 
* (이미 추가되어 있는 경우) 삭제하고 싶은 사용자는 `삭제` 버튼 클릭 
* 추가 혹은 삭제가 끝났다면 `적용`버튼 클릭하여 
![image](https://user-images.githubusercontent.com/47850258/134404589-68c610e8-d261-4e28-8468-dc32e4d1a3cb.png)

> `적용 버튼` 클릭 시 화면 
![image](https://user-images.githubusercontent.com/47850258/134404648-009b1c92-0d95-4602-a405-50218ab6ca42.png)

### `업로드 버튼` 본문 하단에 위치하도록 변경 
![image](https://user-images.githubusercontent.com/47850258/134401613-37f0209f-8aff-4e68-9424-ec24e90ec380.png)

### 그 외 
* 업로드 버튼이 모든 파일 타입을 업로드 가능하도록 허용 
* 업로드 최대 허용 용량을 10MB로 제한 (이전에는 default 값)

2021-09-22 18:58 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +    private val currentRecipients = HorizontalLayout()
배럴이 발견하신 문제점... x위치가 아래로 내려가는 문제는 `currentRecipients`를 Div 컴포넌트로 변경하니까 전보다는 나아진 것 같네요 🤔

2021-09-22 21:11 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +                println("title: ${title.value}  receivers: ${this.receivers}  content: ${this.content.value}")
네네ㅠ콘솔에 안 뜨는것 같아서 남겼는데 제가 못찾는거라면 알려주세요ㅎㅎㅎ

2021-09-23 18:38 UTC, Rok93 commented
# 변경사항 

* `받는 사람`을 Grid로 표현하여 스크롤 할 수 있게 변경 
* 추가 된 이메일은 그리드 창의 `삭제버튼`을 통해서만 삭제할 수 있다. 
* `mailTargets` 필드를 MutableSet 컬렉션으로 둬서 중복 요소 제거 (중복 추가X)
* `MailFormView`를 `BindingFormLayout`를 상속받도록 변경 
* EmailTarget 정보로 `이름` 필드를 추가 (기존에는 email 요소만 존재)
* 보낸사람 정보는 `MailProperties`로 가지고와서 지정하도록 변경 
    * 기존 방식: properties의 정보를 `@Value`로 읽어오도록 했음 

![image](https://user-images.githubusercontent.com/47850258/134562513-c20c5c55-cf28-4c19-a337-887da33783a3.png)


## `업로드 버튼`의 사용방법
* Service 기능이 따로 없다보니 테스트를 못해봄..
* upload 객체를 잘 이용하면 될 것 같음 
* Upload 클래스의 `getOutputStream()`을 통해 outputStream을 이용하면 될 것 같다.

![image](https://user-images.githubusercontent.com/47850258/134563413-ed01e0dc-aae6-4946-897a-f22109cda7ff.png)

2021-09-24 03:31 UTC, NewWisdom requested changes
로키 !!!
메일 발송 화면 구현하느라 진짜진짜진짜 수고 많았습니다 ㅠㅠㅠ
밑바닥서부터 구현해야해서 저였어도 정말 막막했을 것 같네요 🥲
어제 이후로 작업 하신 부분 확인했는데 진짜 많이 개선이 되었네요 노고가 보입니다 짱짱 👏
보면서 저도 로컬에서 코드를 좀 고쳐보고 조금이라도 도움이 되고자 
일단 먼저 지금 상황에서의 제 의견을 좀 남겨보았는데,
이게 제 개인적인 의견이고 좋은 방향인지에 대한 명확한 확신이 없으니
오히려 방해가 될 수 있을 것 같다는 생각에 굉장히 조심스럽네요.
제가 남긴 의견들은 읽어보시고 반영하지 않아도 되고 무시하셔도 매우 좋습니다 !!
그냥 참고만 부탁드려요 !! 
혹시 제 코멘트가 이상하거나 도움이 필요하면 편하게 말씀해주세요 ㅎㅎㅎ
화이팅 🔥

2021-09-24 03:31 UTC, NewWisdom commented on src/main/kotlin/apply/ui/admin/mail/GroupMailTargetFormDialog.kt
> +                    }
이것도 개인적인 생각인데, 
만약 다이얼로그 사이즈가 좀 준다면 셀렉트 박스랑 버튼이 같이있어 상단이 꽉차니
버튼 HorizontalLayout을 하단으로 내리는 것은 어떨까라는 생각이 드는데 요건 어떨까요 ??

2021-09-24 03:31 UTC, NewWisdom commented on src/main/kotlin/apply/ui/admin/mail/GroupMailTargetFormDialog.kt
> +            addSortableColumn("이메일", MailTargetResponse::email)
전반적인 그리드에 메일 대상자 이름도 추가했다면 여기에서도 이름 컬럼을 추가하면 어떨까요???

2021-09-24 03:31 UTC, NewWisdom commented on src/main/kotlin/apply/ui/admin/mail/GroupMailTargetFormDialog.kt
> +
바로 호출을 하고 있으니 메서드로 따로 분리하지 않아도 괜찮을 것 같은데 어떠신가요??

2021-09-24 03:31 UTC, NewWisdom commented on src/main/kotlin/apply/ui/admin/mail/GroupMailTargetFormDialog.kt
> +    private val currentMailTargets: VerticalLayout = VerticalLayout(createContent())
```suggestion
    private val currentMailTargetsGrid: Grid<MailTargetResponse> = createMailTargetsGrid()
```
여기를 그리드로 바꾸고,

2021-09-24 03:31 UTC, NewWisdom commented on src/main/kotlin/apply/ui/admin/mail/GroupMailTargetFormDialog.kt
> +                }
```suggestion
                currentMailTargetsGrid.apply {
                    setItems(mailTargetResponses)
                }
```
setItem을 사용해 createContent() 메서드를 제거하는 방법도 있을 것 같은데 이런 방법은 어떨까요 ??

2021-09-24 05:30 UTC, NewWisdom commented on src/main/kotlin/apply/ui/admin/mail/IndividualMailTargetFormDialog.kt
> +    }
앗 그리고 기존에 검색 요소가 그리드보다 튀어나온 부분도 정렬해주면 좋을 것 같아요 !

2021-09-24 05:39 UTC, NewWisdom commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +            createPrimarySmallButton("삭제") {
```suggestion
            createErrorButton("삭제") {
```
여기는 ErrorButton을 쓰면 좋을 것 같네요 ㅎㅎ

2021-09-24 07:02 UTC, Sehwan-Jang reviewed
로키 어제 저녁부터 정말 고생하셨습니다 🔥
고생하신 만큼 코드도 많이 발전된것 같아 기분이 좋네요 ㅎㅎ

하지만 아직 몇군데 불필요하거나 추가되었으면 좋겠는 부분 코멘트 남겼어요!

2021-09-24 07:02 UTC, Sehwan-Jang commented on src/main/kotlin/apply/ui/admin/mail/IndividualMailTargetFormDialog.kt
> +    }
와 마찌... 디테일한 리뷰 🔥
저도 전반적으로 동의합니다 👍
특히 개별 불러오기 창에서 취소하는 버튼은 필요해보여요. 다이얼로그의 크기도 어느정도 통일되면 더 좋을것 같구요!

2021-09-24 12:52 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +    }
저도 불필요하게 감쌀 필요 없다고 생각해요!
마찌가 제안해준 코드에서 조금 더 수정해보면서 변경해볼게요!! 🙏

2021-09-25 03:18 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/IndividualMailTargetFormDialog.kt
> +    }
우어ㅣ..바딘은 마스터했군욬ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 👍

2021-09-25 03:34 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +    private val subject: TextField = TextField("메일 제목")
![image](https://user-images.githubusercontent.com/66905013/134756481-e700c295-7520-4970-ad64-e31ae0779177.png)
메일 제목 칸은 길게 하면 좋을 것 같은데 어떠세요..?ㅎㅎㅎ

2021-09-25 03:37 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +        return createNormalButton("불러오기") {
저도 `메일 검색하기`으로 하는 것이 좀 더 덜 헷갈릴 것 같아요.

2021-09-25 03:39 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +            },
이 부분은 없는 메일을 직접 입력하기 위한 창인 것 같아요!ㅎㅎ

2021-09-25 03:42 UTC, knae11 reviewed
로키 👍 진짜 페이지 구성하느라 고생이 많네요..!!! 화이팅입니다!! 
화면이 깔끔해졌어요!ㅎㅎㅎ 바딘 너무 어렵덴데 로키가 만들어준 내용들 덕분에 편하게 사용될 수 있을 것 같아요!! 진짜 큰 페이지 해주고 계시네요!!

저 바딘..잘 모르지만ㅋㅋㅋㅋㅋ 사용자 측면에서 조금 수정되었으면 좋겠을 의견 몇개 남겨보았어요~ 😄

2021-09-25 05:53 UTC, Sehwan-Jang commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +            },
불러오기를 눌렀을때 떠오르는 다이얼로그에도 검색창이 있거든요~ 그래서 두번이나 검색창이 있을 필욘 없겠다는 생각이었어요 ㅎㅎ

2021-09-25 06:31 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/GroupMailTargetFormDialog.kt
> +
이 부분은 `createItemSelect()`를  필드(=evaluation)에 바로 할당하면  타입 추론을 할 수 없는 문제가 있어서 지금처럼 메서드로 뽑았는데... 혹시 바로 호출할 수 있는 방법이 있을까요 ? 🤔

![image](https://user-images.githubusercontent.com/47850258/134761319-a2e81b92-57a9-428b-bfc5-10f0aa466bdd.png)

2021-09-25 06:50 UTC, NewWisdom commented on src/main/kotlin/apply/ui/admin/mail/GroupMailTargetFormDialog.kt
> +
@Rok93 
```kotlin
    private val evaluation = createItemSelect<Evaluation>("평가")
```
이렇게 타입 명시를 해주면 될거에요 ! ㅎㅎ

2021-09-25 07:28 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/GroupMailTargetFormDialog.kt
> +                }
기존에는 VerticalLayout에 Component(아마 Span 이었던걸로..)를 각각 추가하다 보니 지금처럼 removeAll, add 메서드로 되어있었는데, VerticalLayout으로 감싸지 않고 바로 Grid를 사용한다면 마찌가 제안한대로 변경할 수 있을 것 같아요!

2021-09-25 07:29 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +            createPrimarySmallButton("삭제") {
처음엔 엄청 신경 썻던 부분인데... 어느 순간 별 생각없이 버튼을 만들고 있었네요 🙄

2021-09-25 07:30 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +        val subjectText = VerticalLayout(H3("메일 제목"), subject).apply { setWidthFull() }
아직 헤더의 잔재가... 👀   H3 컴포넌트 삭제했습니다 👍

2021-09-25 07:37 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +            },
아... 이 검색창은 `직접 입력`을 위한 용도라서 그대로 둬야할 것 같아요!

2021-09-25 07:38 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +    private val subject: TextField = TextField("메일 제목")
이 부분은 저도 많이 느꼈던 부분이라 현재 `setWithFull()` 조건을 줬습니다 : )

2021-09-25 07:58 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/GroupMailTargetFormDialog.kt
> +            addSortableColumn("이메일", MailTargetResponse::email)
그렇네요 여기에서도 이름을 추가하면 좋을 것 같아요 😃

2021-09-25 07:59 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/GroupMailTargetFormDialog.kt
> +                    }
가로 폭을 줄이다보니 자연스럽게 버튼들을 하단으로 내리는게 좋을 것 같네요 🤔

2021-09-25 07:59 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/IndividualMailTargetFormDialog.kt
> +    }
취소버튼 추가했습니다 😃

2021-09-30 14:12 UTC, NewWisdom reviewed
로끼 !!!!
와우 진짜 수고 많았습니다 역시 로키 👏👏
화면이 많이 깔끔해졌네요 정말 많은 노고가 보입니다 🥲
코드상으로 확인해보면 좋을 것 같은 부분들을 조금 남겨보았는데,
확인하시고 동의하신다면, 반영해도 좋을 것 같아요 ㅎㅎ
수고 많으셨습니다 짱짱짱짱 🔥🔥

2021-09-30 19:06 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/IndividualMailTargetFormDialog.kt
> +    private fun createRecipientFilter(): Component {
처음에 Recipient로 명칭을 픽스하려고했는데, 여기저기 Target이라는 표현들이 많다보니 저도모르게 혼용하면서 썻던 것 같네요. 
전체적으로 그냥 target 혹은 Recipient가 아닌 mailTarget이라는 용어로 변경했습니다.

2021-09-30 19:07 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/IndividualMailTargetFormDialog.kt
> +    }
에고... 원래 추가 or 삭제 버튼을 생성하게하는 기능인데... 총체적 난국이네요   add가 아닌 edit에 심지어 or가 아닌 and ... ㅋㅋㅋㅋㅋㅋㅋㅋ 대체 무슨 생각을 하면서 만든건지...

2021-09-30 19:07 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/GroupMailTargetFormDialog.kt
> +        }
호잇!

2021-09-30 19:08 UTC, Rok93 commented on src/main/kotlin/support/views/Buttons.kt
> +): Upload {
이 부분을 변경할 생각을 못했네요 🥲    모든 파일 형식을 다 업로드할 수 있어서 `ImageUploadSucceededListener`가 아닌 `UploadSucceededListener`로 변경하였습니다.

2021-09-30 19:08 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +        setWidthFull()
제거했습니다 💪

2021-09-30 19:09 UTC, Rok93 commented on src/main/kotlin/apply/ui/admin/mail/GroupMailTargetFormDialog.kt
> +    private val evaluation = createEvaluationItem()
아... 메서드에 제네릭 타입을 저렇게 명시하면 바로 사용할 수 있는거였군요??  
메서드에 바로 제네릭 타입을 지정할 수 있는지 전혀 몰랐네요 😧

코멘트 반영했습니다 😃

2021-10-04 07:55 UTC, NewWisdom approved these changes

2021-10-04 15:33 UTC, woowahan-pjs approved these changes
고생하셨습니다. 👍

2021-10-04 15:36 UTC, merged