feat(apply): main page UI
woowacourse/service-apply pull request #353
Opened 2021-09-23 15:55 UTC by SunYoungKwon

## 변경사항
- 네이밍
  - `MainHeader` -> `Header`
  - `MainFooter` -> `Footer`
-  `CommonItem`, `ApplicationFormItem`, `RecruitCard`, `BaseItem` 하나로 통합 -> `RecruitmentItem`
- `Box` 컴포넌트가 컨<img src="https://user-images.githubusercontent.com/45230497/134541654-9b7c2ce1-e243-42f5-b5d7-16777ef66fb1.png" alt="Box 컴포넌트 예시" width="400" />

## 구현결과
[지원사이트 메인페이지 디자인 개선](https://user-images.githubusercontent.com/45230497/134539366-98397782-d9da-484d-96a4-a383101009b4.mp4)

2021-09-24 12:27 UTC, jho2301 requested changes
고생하셨습니다!!!

스토리북에서 에러가 나네요. 확인이 필요한 듯합니다.

![image](https://user-images.githubusercontent.com/44419181/134673220-7cf6710a-1d68-47e2-b4a4-42452cab9628.png)

2021-09-24 12:27 UTC, jho2301 commented on frontend/src/App.css
>  }
위에 :root 선택자랑 혼동이 올 수 있을 것 같은데 `app` 정도로 바꾸면 어떨까요??

2021-09-24 12:27 UTC, jho2301 commented on frontend/src/components/Footer/Footer.stories.js
> +  title: "Footer",
component 정도로 카테고리 만들어두면 어떨까요? 최상단에 컴포넌트 개수가 늘어나면 관리하기 어려울 것 같아요
![image](https://user-images.githubusercontent.com/44419181/134672323-9caee565-126c-449d-ae29-5f430253c3a9.png)
Form카테고리처럼 접을 수 있게 될 수 있습니당

2021-09-24 12:27 UTC, jho2301 commented on frontend/src/components/Header/Header.js
> +                >
동작이 체크박스에 가깝지 않나 싶어요. 체크박스로 바꾸면 어떨까요??

2021-09-24 12:27 UTC, jho2301 commented on frontend/src/pages/ApplicantRegister/ApplicantRegister.js
> +                type="text"
`tel`로 바꾸면 좋을 것 같습니다

2021-09-24 17:57 UTC, ecsimsw reviewed
우와!!! 너무 예뻐졌네요 대박입니다.
정말 고생많으셨어요.

아 개인적인 의견으로, 지원하기 페이지에 정렬이 들어가서 진행 중인 모집을 먼저, 또는 종료된 모집을 밑에 보여줘도 좋겠다는 생각도 들었어요.
예외 메시지에 대한 처리가 궁금해서 코멘트로 남겼는데, 아직 진행되지 않은 부분이라면 답변 안주시고 패스해주셔도 됩니다.
화이팅!!

<img width="755" alt="image" src="https://user-images.githubusercontent.com/46060746/134721467-d7ae6011-c475-4488-98d2-ffba21a67bbd.png">

2021-09-24 17:57 UTC, ecsimsw commented on frontend/src/components/Header/Header.module.css
> +  gap: 0.75rem;
사파리에선 gap 적용이 안되는거 같아요.

2021-09-24 17:57 UTC, ecsimsw commented on frontend/src/pages/Login/Login.js
> +        <Form onSubmit={handleSubmit}>
1. 비밀 번호가 틀릴 경우 kotlin.unit으로 에러 메시지가 출력되네요.

2. 로그인 비밀 번호 입력 칸에 `영문, 숫자, 특수문자 포함하여 8자에서 20자 이내로 입력해 주세요.` 메시지를 출력하는 것이 좋을지 의문이네요.

2021-09-24 18:09 UTC, ecsimsw commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.js
> +              placeholder="ex) https://woowacourse.github.io/javable"
2) 저는 왜 이 부분에서 URL 작성을 안하면 제출 버튼 활성화가 안될까요? 뭔가 required 옵션일거라고 생각하고 찾아보니 코드상에선 문제가 없고... 

(URL 미작성 시 버튼 비활성화)
<img width="708" alt="image" src="https://user-images.githubusercontent.com/46060746/134720777-3599ee23-4163-4326-9b71-22738c7d8c9f.png">
(`<button class="Button_button__1B-83" type="submit" disabled="">제출</button>`)

<br>

(URL 작성 시 버튼 활성화)
<img width="707" alt="image" src="https://user-images.githubusercontent.com/46060746/134720796-af52b16c-74dd-4a63-a399-9ae3cbafc62c.png">

2021-09-25 08:37 UTC, SunYoungKwon commented on frontend/src/components/Header/Header.module.css
> +  gap: 0.75rem;
으악 사파리

2021-09-25 08:56 UTC, knae11 commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.js
> +              placeholder="ex) https://woowacourse.github.io/javable"
이거 기존에도 url 작성 안하면 제출이 안 되었어요ㅠㅠㅠ 안 그래도 이거 얘기하려고 했는데 코기가 얘기해 주셨네요!ㅎㅎㅎㅎㅎ 👍

2021-09-25 09:25 UTC, knae11 commented
### 사용테스트 
- 지원페이지가 예뻐졌어요~~~~ 👍 👍 👍 
- 잘 동작합니다!!ㅎㅎㅎㅎ
- 코기가 언급한대로 url 입력을 있다면 넣어도 좋다고 했는데 안 넣으면 제출이 안 됩니다ㅠㅠ(이건 기존에도 이랬어요) 이 부분에서 없어도 제출 가능하게 하면 좋을 듯 싶어요. 
#### 적절한 예외 메세지를 보여줘도 좋을 듯 싶어요!ㅎㅎㅎ
- 로그인과 register가 같이 사용되서 그런지 모르겠지만, 어떤 이유인지 401이 뜨네요.ㅠㅠ 이메일이 중복되는 경우 뜨는 예외 같아요.
![image](https://user-images.githubusercontent.com/66905013/134766206-0a1a5236-9d8c-45c1-9878-412f87c5e7b6.png)

2021-09-25 11:08 UTC, woowapark requested changes
고생 많으셨어요..!!! 👍 
코드에 대한 코멘트들은 각 라인별로 달아두었습니다.      
확인해보시고, 수정 반영하실 부분이 있다면 이어서 반영해주시면 될 것 같아요 :) 

+) 
테스트 하다보니 로그인 후의 MemberIcon이 약간 색이 연해서 + 버튼이라기보다는 정말 아이콘이다 보니,      
클릭할 수 있는 요소라는 걸 인지를 못할 수도 있지 않을까 싶더라구요      
물론 로그인 하고 나서 새로 보이고, 보통 이런 모양은 누르면 사용자 관련 메뉴가 있기는 하지만 혹시나 해서요ㅋㅋ 개인 의견이라 썬 포함 다른 분들은 어떻게 생각하시는 지 궁금합니당       
혹시 좀 더 정보를 주어야 한다면 색을 좀 더 진하게 하거나, 옆에 드롭다운 메뉴에 있는 것 같은 작은 화살표 정도가 있어도 좋지 않을까 싶구요

2021-09-25 12:12 UTC, SunYoungKwon commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.js
> +              placeholder="ex) https://woowacourse.github.io/javable"
> javable -> tecoble :)

코기 디테일 굿👍

2021-09-25 14:41 UTC, SunYoungKwon commented on frontend/src/components/form/Form/Form.js
> -      </footer>
저는 요기가 아주 속이 시원하네요

2021-09-25 14:51 UTC, NewWisdom reviewed
썬장님 진짜 수고 많으셨습니다 👏👏
지원 페이지 너무 예뻐서 저도 당장 지원하고 싶어요 진짜 ...
UI 때문에 이번 우테코 지원이 더 흥하겠네요 ㅎㅎㅎㅎㅎㅎ
앞으로의 작업도 진짜 기대가 됩니다 !
저도 로컬에서 실행시켜보면서 찾은 부분 코멘트로 남겨보았는데,
제가 잘못 알고 남긴 부분이 있을 수 있으니 그런 부분은 가볍게 넘겨주세요 ㅎㅎ 
수고 많으셨습니다 🔥

2021-09-25 14:51 UTC, NewWisdom commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.js
> +              <CheckBox name="agree" label="동의합니다." />
여기가 맞는지 모르겠지만, 체크박스와 관련된 부분이니 여기 남기겠습니다 ㅎㅎㅎ
![image](https://user-images.githubusercontent.com/43840561/134774971-30ad2c2c-9a1e-43e9-97c7-0854384c1f4d.png)
저번 회의에서 체크 박스 부분을 검정색으로 통일하기로 하고 피그마를 수정했던 것 같은데 반영이 안된 것 같아요 !

2021-09-25 14:51 UTC, NewWisdom commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.js
> +                {`임시 저장되었습니다. (${modifiedDateTime})`}
![image](https://user-images.githubusercontent.com/43840561/134775009-289230eb-5c43-44d0-9db6-c855be12fad8.png)
현재 임시저장 시 현재 날짜보다 한달 전으로 나오는데, 혹시 제 문제일까요 아니면 뭔가 오류가 있는걸까요..?

2021-09-25 14:51 UTC, NewWisdom commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.js
> +                {`임시 저장되었습니다. (${modifiedDateTime})`}
또 `초기화` 버튼을 눌렀을 때, 이후 새로고침했을 때 저 임시 저장 문구가 계속 남아있는데, 
이 경우 임시저장 문구를 지워주는 것은 어떠신가요 ?
호옥시 아직 기능이 붙지 않아서 그런거라면 넘어가시면 될 것 같습니다 ㅎㅎ

2021-09-25 15:38 UTC, ecsimsw commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.js
> +                {`임시 저장되었습니다. (${modifiedDateTime})`}
어 이거 날짜 저도 그러더라고요!!!
리뷰 한다는거 깜빡했는데 마찌 감사!!

2021-09-29 00:32 UTC, SunYoungKwon commented on frontend/src/App.css
>  }
좋습니다!

2021-09-29 00:47 UTC, SunYoungKwon commented on frontend/src/components/Header/Header.js
> +                >
좋네요!

2021-09-29 00:47 UTC, SunYoungKwon commented on frontend/src/components/Footer/Footer.stories.js
> +  title: "Footer",
반영완료

2021-09-29 00:49 UTC, SunYoungKwon commented on frontend/src/components/Header/Header.module.css
> +  gap: 0.75rem;
![image](https://user-images.githubusercontent.com/45230497/135184581-0fda2592-d2b3-47c0-9ee1-09d152ddabe1.png)

저는 정상적으로 나오는데, 혹시 사파리 어떤 버전 쓰시는지 알 수 있을까요?

2021-09-29 00:51 UTC, SunYoungKwon commented on frontend/src/components/Header/Header.module.css
> +  gap: 0.75rem;
요 부분은 margin으로 변경하여 적용될 수 있도록 해두었습니다!

2021-09-29 01:06 UTC, SunYoungKwon commented on frontend/src/components/Box/Box.js
> +        { [styles.narrow]: size === "narrow" },
좋습니다! (저도 default 오타 잘 냅니다ㅎㅎㅎ )

2021-09-29 01:25 UTC, SunYoungKwon commented on frontend/src/components/Box/Box.js
> +const Box = ({ title, size, children, className }) => {
`Box` 컴포넌트 이름을 `Container`로 변경했습니다.

`className`의 경우 단순 정렬을 위한 역할과 `Container` 컴포넌트가 하듯 컨텐츠영역의 가로 길이를 제한하는 역할으로 두가지 경우가 나뉘어서, 단순 정렬의 경우 `box`로 가로 길이를 제한하는 경우 `content-wrapper`로 변경해주었습니다.

2021-09-29 01:26 UTC, SunYoungKwon commented on frontend/src/App.css
> +  --nav-z-index: 997;
피그마에서 사용한 색상만 정리하다보니 001까진 안가더라구요ㅋㅋㅋ

2021-09-29 01:27 UTC, SunYoungKwon commented on frontend/src/components/Header/Header.js
> +    if (window.confirm(CONFIRM_MESSAGE.LOGOUT)) {
툴팁으로 한 단계 더 거치기도 하니 confirm까지 하진 않아도 되겠네요!

2021-09-29 01:31 UTC, SunYoungKwon commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.js
> +              <CheckBox name="agree" label="동의합니다." />
요 이슈는 메인페이지 관련이라 여기까지 확인을 안했네요! 이건 간단한 부분이라 반영해두겠습니다ㅎㅎ

2021-09-29 01:37 UTC, SunYoungKwon commented on frontend/src/pages/Login/Login.js
> +          <Link to="/find" className={styles["find-password"]}>
요 부분을 놓쳤네요!

2021-09-29 01:43 UTC, SunYoungKwon commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.js
> +              placeholder="ex) https://woowacourse.github.io/javable"
URL 부분은 슬쩍 봤는데 원인을 바로 못찾아서 시간이 좀 걸릴 수 있을 것 같아요. 해당 페이지 관련 이슈에서 처리하도록 하겠습니다!

2021-09-29 01:44 UTC, SunYoungKwon commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.js
> +                {`임시 저장되었습니다. (${modifiedDateTime})`}
날짜 부분은 해당 페이지 관련 이슈에서 처리하도록 하겠습니다!

2021-09-29 01:57 UTC, SunYoungKwon commented on frontend/src/pages/Recruits/Recruits.js
> +  const goApplicantsNewPage = (recruitmentId) => {
좋아요ㅋㅋㅋ

2021-09-29 02:01 UTC, SunYoungKwon commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.js
> +              <SubmitButton>제출</SubmitButton>
좋습니다!

2021-09-29 02:01 UTC, SunYoungKwon commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.js
> +              <SubmitButton>제출</SubmitButton>
리뷰와 별개로 `SaveButton`이 페이지 컴포넌트 내에서 생성되고 있는데 이런 구조에 문제가 없을까요?

2021-09-29 02:09 UTC, SunYoungKwon commented on frontend/src/pages/Login/Login.js
> +        <Form onSubmit={handleSubmit}>
1. 이 부분은 서버에서 오는 메세지를 그대로 보여주고 있습니다. 아마 비밀번호가 틀렸을 경우 메세지가 따로 설정되어 있지 않나봐요! 이부분은 서버에서 만들어 주셔도 되고 프른트에서 따로 넣어도 됩니다(쉬운 일이라ㅎㅎ). 우선 프론트에서 처리하도록 할게요! 별개로 로그인 및 비밀번호가 틀린경우 메세지를 서로 다르게 주는 것은 좋지 않다고 알고있어요. 메세지만으로도 해당이메일로 가입이 되어있는지 아닌지 정보를 주게 되니까요!

2. 저도 요 메세지는 없어도 될 것 같습니다!

-> 이 부분은 다음 이슈(로그인, 회원가입 UI 개선)에서 처리하도록 할게요! 리뷰 감사해😀

2021-09-29 02:11 UTC, woowapark commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.js
> +              <SubmitButton>제출</SubmitButton>
앗 여기 수정사항에서 잡히지 않아서 못봤는데, 
인풋 리팩토링 PR에서 분리되는 부분일 거 같아요..! (맞지용?)
https://github.com/woowacourse/service-apply/pull/363#discussion_r716372562

2021-09-29 02:50 UTC, SunYoungKwon commented
- 스토리북 오류 해결완료!
- `MemberIcon` 색상 좀 더 진하게 변경, `cursor: poiner` 적용, 아이콘 우측에 화살표 추가
![member-tooltip](https://user-images.githubusercontent.com/45230497/135194800-dc452a85-254d-4894-bd4f-22a98ba9b6ec.gif)
- 모집 시작일을 기준으로 모집 정렬

- 메인페이지와 관련되지 않은 버그들은 해당 페이지 이슈에서 처리하도록 하겠습니다!(각 이슈에 정리 완료 👍)

2021-09-29 03:58 UTC, woowapark approved these changes
변경사항 확인하였습니다, 고생하셨어요~~~! 👍👍 
메인페이지 UI 변경 이외에 버그성 이슈 제보된 것들은 말씀해주신 것처럼 해당 페이지 작업시에 챙겨주시면 될 것 같습니다 :)   

(변경과 별개로 로그인 된 상태의 Header 도 스토리북에 케이스 하나 정도 추가해두면 어떨까요~?)

2021-09-29 13:42 UTC, jho2301 approved these changes
썬생님 수고 많으셨습니다. 반영사항 모두 확인했습니다!

2021-09-29 13:50 UTC, SunYoungKwon commented
@woowahan-pjs 머지요청드립니다~

2021-10-01 02:50 UTC, woowahan-pjs approved these changes
고생하셨습니다. 👍

2021-10-01 02:50 UTC, merged