feat: implement mail history
woowacourse/service-apply pull request #377
Opened 2021-10-07 16:31 UTC by knae11

Closes #306

# 메일관리
- 모집과 비슷한 맥락으로 메일 관리 페이지를 구현
<img width="1432" alt="스크린샷 2021-10-08 오전 1 19 45" src="https://user-images.githubusercontent.com/66905013/136425784-bf96dc01-56bd-44b9-a24c-7cdb8915819d.png">

# 메일 전송
- 받는 사람 수가 나오게 개선
<img width="1396" alt="스크린샷 2021-10-08 오전 1 19 08" src="https://user-images.githubusercontent.com/66905013/136425848-ae6392b5-31ac-4610-a965-66a03275f189.png">

# 메일 이력 조회
- readOnly로 화면에 표시
<img width="1440" alt="스크린샷 2021-10-08 오전 1 20 06" src="https://user-images.githubusercontent.com/66905013/136425992-31816cb1-2d6d-4ec4-a652-935dc6824b18.png">

# 참고
- 이슈에 정리된 내용을 참고해 주세요.
- 메일 성공여부는 표시되지 않음 (AWS에서 확인, 여기에서는 이력만 관리)
- recipients는 이메일 목록을 `,`를 구분자로 저장하여 하나의 문자열로 저장

2021-10-09 15:37 UTC, MyaGya commented
고생하셨습니다! 몇 가지 코멘트를 남겼으니 확인해주시면 감사하겠습니다.

2021-10-09 15:37 UTC, MyaGya reviewed
고생하셨습니다! 몇 가지 코멘트를 남겼으니 확인해주시면 감사하겠습니다.

2021-10-09 15:37 UTC, MyaGya commented on src/main/kotlin/apply/application/UserService.kt
> +        return MailTargetResponse(email = email)
```suggestion
val user = userRepository.findByEmail(email) ?: return MailTargetResponse(email = email)
        return MailTargetResponse(user.name, user.email)
```
이렇게 사용하시는 건 어떨까요?

2021-10-10 04:10 UTC, knae11 commented on src/main/kotlin/apply/application/MailHistoryService.kt
> +class MailHistoryService(
저도 이 부분에 대해서 고민이 되었는데요. `MailService`는 `@Transactional`이 아닌 `@Async`로직을 사용하는 메소드로 구성되어 있더라구요. 같은 서비스에 넣을까하다가 비동기로직과 아닌 로직을 구분하는게 좋을 것 같아서 분리했어요. 

혹시 다른 분들도 의견도 어떤지 궁금해요~ㅎㅎㅎ

2021-10-10 04:13 UTC, knae11 commented on src/main/kotlin/apply/application/MailHistoryService.kt
> +    private val emailHistoryRepository: EmailHistoryRepository
저도 이 부분에 대해서 고민이 되었는데요. 기존 몇몇 구현되어 있는 코드가 `MailSerive` `MailData` 등등 email 대신 mail이라는 키워드를 사용하더라구요. email이라는 내용에 특정하지 않고 좀 더 범용적인 의미로 mail을 사용한 걸까 싶은 생각이 들었어요. 기존 작성되어 있는 코드를 따라가기 위해서 `Mail`이라는 단어를 사용하였어요.

`EmailHistoryRepository`는 제가 수정하면서 놓친 부분이네요. 일단 `MailHistoryRepository`로 수정해놓을게요.

이 또한 다른 분들의 의견도 받아서 용어를 mail이 아닌 email로 통일하고 싶다는 의견이 많다면 반영하겠습니다.

2021-10-10 04:17 UTC, knae11 commented on src/main/kotlin/apply/application/UserService.kt
> +        return MailTargetResponse(email = email)
오 이 부분에 엘비스 연산자를 쓸까 하다가 사용이 미숙해서 고민해보다가 지나간 부분인데 찾아주셨네요! 👍 👍  내용 반영하였습니다.

2021-10-10 08:57 UTC, woowahan-pjs requested changes
고생하셨습니다. 👍 
소소한 피드백을 남겼습니다.

2021-10-10 08:57 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationDtos.kt
> +    val name: String = NO_NAME,
공백으로 채우고 View에서 변경하면 어떨까요? 응용 계층이 View에 의존하는 부분도 사라질 거예요.

2021-10-10 08:57 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/MailHistoryService.kt
> +        }
재사용하지 않는 지역 변수의 수는 최소화하면 어떨까요? `MailData`에 부 생성자를 추가할 수도 있어요.

```suggestion
        return mailHistoryRepository.findAll()
            .map { MailData(it.subject, it.body, it.sender, it.recipients, it.sentTime, it.id) }
```

2021-10-10 08:57 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/UserService.kt
> +    fun findMailTargetByEmail(email: String): MailTargetResponse {
`UserService`에 위치하는 것이 적절할까요?

2021-10-10 08:57 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/mail/MailData.kt
> +    }
아래의 글이 도움 될 거예요.
https://blog.kotlin-academy.com/kotlin-should-i-define-function-or-property-6786951da909

2021-10-10 08:57 UTC, woowahan-pjs commented on src/main/kotlin/apply/domain/mail/MailHistory.kt
> +    val recipients: String,
`AttributeConverter`를 사용하면 어떨까요? 아래의 글이 도움 될 거예요.
https://www.baeldung.com/jpa-attribute-converters

2021-10-10 08:57 UTC, woowahan-pjs commented on src/main/kotlin/apply/domain/mail/MailHistory.kt
> +    id: Long = 0L
```suggestion
    val sentTime: LocalDateTime = LocalDateTime.now(),
    id: Long = 0L
```

2021-10-10 08:57 UTC, woowahan-pjs commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +                this.submitButton.isVisible = false
`BindingFormLayout`을 상속한 'Form'과 페이지인 'View'를 분리하면 어떨까요?
https://github.com/woowacourse/service-apply/pull/337#issuecomment-933597849

2021-10-10 08:57 UTC, woowahan-pjs commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +        }
조회 쿼리가 얼마나 발생할까요?

2021-10-10 08:57 UTC, woowahan-pjs commented on src/main/kotlin/apply/utils/Constants.kt
> +const val DELIMITER = ","
','를 상수로 관리해야 할까요? 상수의 위치와 이름도 불분명해요.

2021-10-10 08:57 UTC, woowahan-pjs commented on src/main/kotlin/support/views/FormLayouts.kt
> +const val DETAIL_VALUE: String = "detail"
예약 발송 등 메일 수정 기능이 추가될 수 있으니 기존 `NEW_VALUE` 및 `EDIT_VALUE`를 사용하면 어떨까요?

2021-10-10 12:55 UTC, knae11 commented on src/main/kotlin/apply/domain/mail/MailHistory.kt
> +    val recipients: String,
오~ 최고최고! 적용하였습니다! 매번 변환작업을 할 필요 없이 타입을 변환해줄 수 있군요!! 👍 👍

2021-10-10 12:55 UTC, knae11 commented on src/main/kotlin/apply/utils/Constants.kt
> +const val DELIMITER = ","
`AttributeConverter`를 사용하면서 없어졌네요!!ㅎㅎㅎ

2021-10-10 12:58 UTC, knae11 commented on src/main/kotlin/apply/application/MailHistoryService.kt
> +        }
이미 부 생성자를 만들어 놨었는데 활용하지 못하고 있었네요! 수정하였습니다~ㅎㅎㅎ

2021-10-10 12:58 UTC, knae11 commented on src/main/kotlin/apply/domain/mail/MailHistory.kt
> +    id: Long = 0L
마지막 id 는 붙이는 컨벤션이군요! 수정하였습니다~

2021-10-10 13:55 UTC, knae11 commented on src/main/kotlin/support/views/FormLayouts.kt
> +const val DETAIL_VALUE: String = "detail"
넵넵! 기존 `NEW_VALUE`와 `EDIT_VALUE`를 사용하는 방식으로 변경하였습니다!

2021-10-10 15:08 UTC, knae11 commented on src/main/kotlin/apply/application/UserService.kt
> +    fun findMailTargetByEmail(email: String): MailTargetResponse {
`MailService` -> `MailSenderService`
`MailHistoryService` -> `MailService`
로 변경하고, 해당 메소드는 `MailService`로 이동하였습니다.

2021-10-10 16:06 UTC, knae11 commented on src/main/kotlin/apply/application/EvaluationDtos.kt
> +    val name: String = NO_NAME,
Cheater와 같은 로직으로 null 가능처리하고 null인 경우 NO_NAME 을 보여주도록 변경하였습니다 :)

2021-10-10 16:08 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +        }
해당 쿼리 `findAllByEmailIn`을 사용하여 1번의 쿼리로 실행하게 변경하였습니다. 하지만 이 경우, 보여줄 때 입력 순서가 아닌 user 에 해당하는 email 끼리 먼저 나오고, `(이름없음)` 이메일이 나오게 됩니다. 오히려 구분되어 있어서 좋을 것 같다는 생각이 들기도 한데 어떨지 모르겠네요ㅎㅎㅎ

2021-10-10 17:28 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailFormView.kt
> +                this.submitButton.isVisible = false
`Form`과 `View`를 분리하여 리팩토링 진행하였습니다 :)

2021-10-10 18:19 UTC, Rok93 requested changes
배럴 Form과 View 분리하시느라 고생많으셨어요 😃👍 
몇몇 의견들 적어놨는데, 동의하시는 부분은 반영해주시면 좋을 것 같아요 👀 
아직 코멘트가 많지 않고 또 제가 보지 못한 새로운 부분들이 많이 나올 수 있다고 생각해서 일단은 Request Changes로 걸어뒀습니다. 다른분들 리뷰가 더 달리면 한번 더 확인하러 오는걸로 하겠습니다 😉

2021-10-10 18:19 UTC, Rok93 commented on src/test/kotlin/apply/ui/api/EvaluationTargetRestControllerTest.kt
> +        } returns listOf(MailTargetResponse("roki@woowacourse.com", "김경록"))
괜히 제 이름 왔다갔다하니까 기분이 묘하네요 😧

2021-10-10 18:19 UTC, Rok93 commented on src/test/kotlin/apply/ui/api/MailHistoryRestControllerTest.kt
> +        }.andExpect {
```suggestion
        mockMvc.get("/api/mails/{mailHistoryId}", mailData.id)
            .andExpect {
                status { isOk }
                content { json(objectMapper.writeValueAsString(ApiResponse.success(mailData))) }
            }
    }

    @Test
    fun `모든 이메일 내역을 조회한다`() {
        val mailDataValues: List<MailData> = listOf(createMailData(), createMailData())
        every { mailService.findAll() } returns mailDataValues

        mockMvc.get("/api/mails")
            .andExpect {
```
content가 따로 없으니 contentType은 생략해도 될 것 같아요 😃

2021-10-10 18:19 UTC, Rok93 commented on src/main/kotlin/apply/domain/mail/MailHistory.kt
> +    @Column(nullable = false)
개인적인 생각이지만 subject랑 sender는 길이 제한을 두는게 어떨까요? 🤔

2021-10-10 22:57 UTC, knae11 commented on src/main/kotlin/apply/domain/mail/MailHistory.kt
> +    @Column(nullable = false)
View 단에서 제한을 두는게 좋다는 의견일까요??? 지금 DB에 값으로 들어갈 때는 varchar(255)로 들어가고 있는데 혹시 이 부분을 명시하는게 좋다는 의견일까요??

2021-10-10 22:59 UTC, knae11 commented on src/test/kotlin/apply/ui/api/EvaluationTargetRestControllerTest.kt
> +        } returns listOf(MailTargetResponse("roki@woowacourse.com", "김경록"))
ㅋㅋㅋㅋㅋㅋㅋ `김로키`로 변경해주었어요 :)

2021-10-10 23:01 UTC, knae11 commented on src/test/kotlin/apply/ui/api/MailHistoryRestControllerTest.kt
> +        }.andExpect {
오!!! 그렇네요. 반영하였습니다~

2021-10-10 23:02 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailView.kt
> +        return ComponentRenderer<Component, MailData> { response ->
기존 다른 코드가 남아있어서 남겨두었었는데 제거했어요 :)

2021-10-10 23:04 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailView.kt
> +        return ComponentRenderer<Component, MailData> { response ->
하면서 참고했던 RecruitmentsView에서도 제거해주었습니다.

2021-10-10 23:13 UTC, knae11 commented on src/main/kotlin/apply/application/mail/MailData.kt
> +    var sender: String = "",
제가 알기로는 validation 어노테이션 때문으로 알고 있어요. reflection을 사용해서 가변으로 만들어 주어야 하는 것으로 알고 있는데.. [validation](https://docs.jboss.org/hibernate/beanvalidation/spec/2.0/api/) 기본 생성자를 통한 reflection을 사용하네요!ㅎㅎ

2021-10-10 23:14 UTC, knae11 commented on src/main/kotlin/apply/application/mail/MailData.kt
> +    var sender: String = "",
혹시 다른 이유라면 알려주세요!ㅎㅎㅎ

2021-10-10 23:32 UTC, knae11 commented on src/main/kotlin/apply/application/mail/MailData.kt
> +    var sender: String = "",
위와 같은 이유인줄 알았는데 아니네요?!ㅎㅎㅎㅎ 실험해보니 아마 `~~Data`는 바딘에서 form과 연결할 때 사용되는데요. 그 값을 받기 위해서 var을 사용하는 듯 해요.

val로 하니 이미 기본 값으로 들어가는데 불변이 되어서 form 안에 입력이 불가능하네요 :)

2021-10-10 23:37 UTC, knae11 commented on src/main/kotlin/apply/domain/mail/MailHistory.kt
> +    @Column(nullable = false)
뷰에서 제한을 두면 좋겠다는 의미일 것 같은데 혹시 제한을 한다면 DB 내부 타입과 같이 `@field:Size(min = 1, max = 255)`로 하는게 좋을까요? 혹은 더 적은 100자 정도로 하는게 좋을까요? 👀

2021-10-11 04:56 UTC, knae11 commented on src/main/kotlin/apply/ui/admin/mail/MailView.kt
> +        return ComponentRenderer<Component, MailData> { response ->
메소드 분리를 통해서 람다 안에 메소드를 호출하면 컴파일러가 데이터 타입을 파악할 수 있어서 해당 데이터 타입이 삭제 가능하고, 아닌 경우에는 데이터 타입이 삭제될 수 없어요.

어떤 부분은 제네릭 타입이 삭제가능하고 아닌 것도 있어서 혼용되는 것보다 음영처리 되더라도 타입을 유지하는 것으로 할게요~ㅎㅎㅎ

2021-10-11 08:25 UTC, NewWisdom commented on src/main/kotlin/apply/ui/api/MailHistoryRestController.kt
> +    fun save(@RequestBody request: MailData): ResponseEntity<Unit> {
현재 마갸의 메일 발송 api랑 겹치는 부분인 것 같아서 해당 path를 
"/api/mail-history" 혹은 "/api/mails/history" 등으로 변경이 필요해보여요 !

2021-10-11 08:53 UTC, ecsimsw requested changes
확인부탁드립니다.

2021-10-11 08:53 UTC, ecsimsw commented on src/main/kotlin/apply/domain/mail/MailHistory.kt
> +    @Column(nullable = false)
Flyway migration script 와 독립적으로 애플리케이션 내부에서도 길이 제한 적는게 좋을 것 같습니다.
migration script에 명시되면, 'sender는 255자 이하다' 라는 조건이 Flyway에 의존적이기 때문입니다. flyway를 제거했을 때도 같은 조건을 주기 위해서요. 
예를 들면 flyway 제거하고 hibernate.ddl-auto: create 했을 때도 같은 조건으로 스키마를 생성할 수 있겠지요.

마찬가지 이유로 @field도 migration script와 동일하게 작성되어야 한다고 생각합니다.
즉 '주'는 migration 스크립트 내용보다, Entity의 @field 선언이 되어야 할 것 같습니다.

2021-10-11 11:09 UTC, knae11 commented on src/main/kotlin/apply/application/MailHistoryService.kt
> +        val emailHistory = mailHistoryRepository.getById(emailHistoryId)
오! 놓쳤네요 반영하였습니다~

2021-10-11 11:18 UTC, knae11 commented on src/main/kotlin/apply/ui/api/MailHistoryRestController.kt
> +    fun save(@RequestBody request: MailData): ResponseEntity<Unit> {
좋습니다~! 마갸부분이랑 겹친다고 하니 mail-history로 변경하겠습니다!

2021-10-11 11:24 UTC, knae11 commented on src/main/kotlin/apply/application/MailHistoryService.kt
> +    }
오!! list 연산도 set으로 바꾸는지 몰랐는데 👍 👍 👍 list 방식으로 수정할게요!ㅎㅎㅎ

2021-10-11 17:09 UTC, ecsimsw requested changes

2021-10-11 23:15 UTC, knae11 commented on src/main/resources/db/migration/V1_10__Add_email_history.sql
> +   default charset = utf8mb4;
확인 부탁드립니다 😄

2021-10-13 12:35 UTC, Sehwan-Jang requested changes
수고하셨습니다! 간단한 리뷰 하나 남겼어요~

2021-10-13 12:35 UTC, Sehwan-Jang commented on src/main/kotlin/apply/ui/admin/mail/MailForm.kt
> +    private val mailTargetGridTitle: Label = Label()
라벨이 footer로 바뀌면서 더이상 필요 없는것 같네요~

2021-10-13 13:17 UTC, NewWisdom approved these changes
굳굳 수고 많으셨습니다 배럴 👏👏👏

2021-10-13 15:16 UTC, ddaaac commented on src/main/kotlin/apply/ui/admin/mail/MailsFormView.kt
> +    }
```suggestion
    override fun setParameter(event: BeforeEvent, @WildcardParameter parameter: String) {
        val result = FORM_URL_PATTERN.find(parameter) ?: return goBack()
        val (id, value) = result.destructured
        if (value == EDIT_VALUE) {
            mailForm.fill(mailHistoryService.getById(id.toLong()))
            this.submitButton.isVisible = false
        }
    }

    private fun goBack() {
        UI.getCurrent().page.history.back() // TODO: 에러 화면을 구현한다.
    }
```

depth가 적을수록 보기 좋다고 생각합니다 ㅎㅎ

2021-10-13 23:43 UTC, merged