feat(term): implement term management view
woowacourse/service-apply pull request #378
Opened 2021-10-08 09:36 UTC by Sehwan-Jang

Close #376 

## 구현 화면
+ 모집 생성 화면의 기수관리 버튼으로 접근
![image](https://user-images.githubusercontent.com/68985748/136533123-b5ed21f8-7ec0-4132-9d5a-8c3d7d8fd89a.png)
+ 기수 관리 화면 및 다이얼로그
![image](https://user-images.githubusercontent.com/68985748/136533284-7b29e2a0-bba1-4c69-8f44-1d7bdc4fb606.png)
![image](https://user-images.githubusercontent.com/68985748/136533407-09f89921-74dc-4e8f-9eb7-11e91a869879.png)
![image](https://user-images.githubusercontent.com/68985748/136533469-f4c3f76c-ea6b-41b2-a2c8-972a1b799eb2.png)

## 특이사항
+ RecruitmentService에 있던 `findAllTermSelectData()` TermService로 이동
+ TermsView에서 돌아가기 버튼 클릭시 다시 모집 생성 창으로 이동
+ 단독 모집은 DB에 존재하는 데이터가 아니고 디폴트 값이기 때문에 수정, 생성 버튼 비활성화
+ BindingIdentityFormLayout 사용
+ 추가되어야할 기능 TODO로 명시

2021-10-10 06:03 UTC, knae11 commented
안녕하세요~ 아론! 뷰와 관련해서 의견 남겨볼게요 😄 

![image](https://user-images.githubusercontent.com/66905013/136684299-62ad26b7-e646-4197-8187-de848adbc180.png)
- 기수 생성 부분을 버튼으로 관리한다면 모집명 생성전에 기수가 있으면 좋을 것 같다는 생각이 드네요. 그 이유는 보통 상부에서부터 칸을 채워나가는데 `기수 관리` 버튼에 들어갔다가 돌아가기로 다시 나오면 작성했던 폼 내용이 다시 초기화기 되어서 다시 입력해야되는 상황이 발생해서 차라리 맨 위로 올리는게 어떨까 하는 의견입니다.

![image](https://user-images.githubusercontent.com/66905013/136684532-1a1cfca5-afa8-4ca7-b707-62da894c6a84.png)
- 이 부분도 placeholder가 아닌 text 자체를 넣어주는건 어떨까요?

2021-10-11 16:02 UTC, ecsimsw commented on src/main/kotlin/apply/ui/admin/term/TermsView.kt
> +                isEnabled = false
버튼을 아예 제거해버려도 괜찮겠네요!! 
어차피 비활성화니 🌝 
(만일 적용하신다면 isVisable이라는 키워드를 👍)

<img width="679" alt="image" src="https://user-images.githubusercontent.com/46060746/136820866-32ac4672-9ee2-415c-a172-b1a38de68954.png">

추가) 리뷰하다가 생각난건데 아니면 아예 관리에선 '단독 모집' 저 라인 자체가 없어지면 어떨까요. 저는 그게 제일 깔끔할 것 같아요.

2021-10-11 16:11 UTC, ecsimsw commented on src/main/kotlin/apply/application/TermService.kt
> +        val terms = listOf(Term.SINGLE) + termRepository.findAll().sortedBy { it.name }
<img width="948" alt="image" src="https://user-images.githubusercontent.com/46060746/136821728-2219ca6c-a49f-4f65-ad2d-7f978603ebbf.png">

기수 조회 정렬 방법이 이름이라 10기부턴 다시 올라오네요. 
정렬 방법에 대한 리뷰를 달려고 했는데, '우테코 1기, 2기, 3기', '우테켐 3기 4기' 등등 10기보다 기수에 이름이 들어가는 경우가 더 유의미할 것 같아 패스합니다.

확인 차 댓글 남겼어요!!

2021-10-13 13:28 UTC, MyaGya approved these changes
확인했습니다! 고생하셨어요.

2022-06-26 15:04 UTC, woowahan-pjs requested changes
아직 구현해야 할 부분을 구현하고 UI를 개선하면 좋을 것 같아요.

2022-07-06 11:16 UTC, kth990303 reviewed
직접 실행하면서 동작 돌아가는 거 확인했습니다!
코틀린으로 UI까지 구현할 수 있다는 것에 감탄했습니다...

코드 보면서 많이 배웠고, 간단한 코멘트만 남겨봤습니다! 😄

2022-07-06 11:16 UTC, kth990303 commented on src/main/kotlin/apply/ui/admin/term/TermsView.kt
> +    private fun createEditButton(term: TermResponse): Button {
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/57135043/177537190-123fc037-405d-4869-ad7e-b07025d9fa69.png">
개인적으로는 수정, 삭제 버튼이 오른쪽 (빨간색 박스친 부분)에 있으면 더 이쁠 것 같은데 어떤가요?

2022-07-07 04:11 UTC, woowahan-pjs approved these changes
고생하셨습니다. 👍

2022-07-07 04:12 UTC, merged