feat(apply): separate users and administrators for http api
woowacourse/service-apply pull request #388
Opened 2021-10-11 13:04 UTC by woowahan-pjs

Resolves #275

2021-10-11 15:12 UTC, knae11 requested changes
RestControllerTest로 인증관련 모킹이 분리되서 다른 컨트롤러에서 사용하기 좋네요!! 작은 의견 남겨봅니다.

2021-10-11 15:12 UTC, knae11 commented on src/test/kotlin/apply/ui/api/CheaterRestControllerTest.kt
> +            header(HttpHeaders.AUTHORIZATION, "Bearer valid_token")
UserFixture에 

```kotlin
const val VALID_TOKEN: String = "SOME_VALID_TOKEN"
```
이 정의되어 있는데, 이걸 valid_token 으로 바꾸고 
```kotlin
const val BEARER_VALID_TOKEN: String = "Bearer valid_token"
```
부분을 추가해주고 상수로 작성해는건 어떻게 생각하세요??

중복해서 작성되는 부분이 있는것 같아 의견 제시해봅니다.

2021-10-11 15:13 UTC, ecsimsw commented on src/main/kotlin/apply/ui/api/EvaluationRestController.kt
> +    }
프로젝트 전반적으로 메서드 순서가 바뀌었는데 그 이유가 궁금하네요.
스타일 배우고 싶어 커멘트 남깁니다.

2021-10-11 15:30 UTC, ecsimsw commented on src/test/kotlin/apply/ui/api/RestControllerTest.kt
> +        every { administratorService.isAdministrator(any()) } returns true
👍👍
저는 RestControllerTest로 빼서 너무 깔끔한 것 같아요.
ControllerTest에서 확인하고 싶은 부분이 명확해져서 좋았습니다.

2021-10-12 06:16 UTC, Sehwan-Jang commented on src/main/kotlin/apply/security/LoginUserResolver.kt
> +        requireAdministrator(parameter, email)
메소드 명만 봤을 때 무조건 관리자 인지를 확인할 것 같은 느낌을 받았어요 
`checkAdministratorIfRequired` 와 같이 수정한다면 하위 메서드에서 분기를 탄다고 생각할 수 있을 것 같은데 어떠신가요?

2021-10-12 06:52 UTC, NewWisdom requested changes
수고하셨습니다 짱짱 👏👏
관리자 api 분리를 어노테이션으로 관리할 수도 있네요.
코드보면서 많이 배워갑니다 !!
보면서 몇가지 코멘트 남겨보았는데 확인 부탁드려요 ㅎㅎ

2021-10-12 06:52 UTC, NewWisdom commented on src/test/kotlin/apply/ui/api/RestControllerTest.kt
> +        every { administratorService.isAdministrator(any()) } returns true
이건 그냥 궁금해서 남기는 코멘트인데요,
현재 모두 isAdministrator를 true로 주어 관리자 권한으로 api들을 테스트하고 있는데 
컨트롤러 테스트에서는 관리자 api임을 드러내지 않아도 괜찮은가요 ?
회원 api는 해당 값을 false로 재정의 혹은 
기본이 false, 관리자 api에서 재정의로 관리자 권한 api를 명시하는게 좋지 않을까 하는데
또 요청 응답을 확인하는데 일일히 재정의하면서 구분지을 필요가 있을까라는 생각도 드네요.
생각해보다가 제이슨의 의도가 궁금해서 한번 남겨봅니다 ㅎㅎ

2021-10-12 06:52 UTC, NewWisdom commented on src/test/kotlin/apply/ui/api/CheaterRestControllerTest.kt
>          every { cheaterService.deleteById(cheatedUser.id) } just Runs
몇몇 모킹에서만 any()를 쓰도록 변경했는데, 이렇게 값을 명시하는 로직들은 다른 이유가 있는 걸까요 ?
범위가 넓어서라면 추후에 작업해나가도 좋을 것 같습니다 !

2021-10-21 11:57 UTC, knae11 approved these changes
확인했습니다. 👍

2021-10-21 13:00 UTC, merged