feat(apply): add empty state ui
woowacourse/service-apply pull request #577
Opened 2022-07-25 07:22 UTC by soyi47

2022-07-25 15:02 UTC, woowapark requested changes
- 메세지 외에 디자인도 모두 변경 예정일까요?      
   다시보니 폰트 사이즈가 지나치게 큰 게 아닐까 싶어 확인차 코멘트 다시 남겨봅니다~     
   기존에 <RecruitmentItem> 의 제목 텍스트 크기 정도로도 충분하지 않을까 싶은데 어떠신가요?  
- `<RecruitmentItem>` 리팩토링 외에 리스트 컴포넌트 분리정도는 여기에서 추가로 해봐도 괜찮지 않을까요? `recruitement &&` 부터 시작하는 분기 처리가 이미 꽤 복잡해보여서요 🤔 목요일 전에 마무리가 안되실 것 같다면 3.0.0으로 넘기셔도 되고요.      

새마음 새뜻으로 PR 딴 김에 한번 추가로 확인 부탁드릴게요! 🙏

2022-07-28 00:40 UTC, woowahan-pjs requested changes
용어에 대한 의견을 남겼습니다.

2022-07-28 00:40 UTC, woowahan-pjs commented on frontend/src/pages/Recruits/Recruits.js
> +              <div className={styles["empty-state-box"]}>해당하는 공고가 존재하지 않습니다.</div>
'모집'이 아닌 '공고'라고 한 이유가 있을까요? 아래의 글이 도움 될 거예요.
https://github.com/woowacourse/service-apply/wiki/용어-사전

2022-07-28 00:54 UTC, woowapark commented on frontend/src/pages/Recruits/Recruits.js
> +              <div className={styles["empty-state-box"]}>해당하는 공고가 존재하지 않습니다.</div>
오 논의할 때 저도 있었는데, 안그래도 기존에 프로젝트에서 쓰던 용어는 아니어서 의견을 여쭤보려 했었어요.       
(모집 예정 / 모집 중 / 모집 종료 상태에) 해당하는 '모집'이 없습니다 라고 하니 조금 어색한 것 같아서 🤔       
이후 개선하게 된다면 '모집 예정인 ㅇㅇ이 없습니다', '모집 중인 ㅇㅇ이 없습니다', '모집 종료된 ㅇㅇ이 없습니다' 형태로 메시지를 각각 구체적으로 보여주면 좋을 것 같아서요.       
요런 문장을 고려해보자면 많이 사용되는 '모집 공고'라는 단어가 있으니 '공고'로 써보면 어떨까 하였는데요.          
기존에 사용하던 용어가 아니어서 혼란스러울까요?

2022-07-28 01:06 UTC, soyi47 commented
@woowapark

#### 1. 메인페이지 수정 방향
메인 페이지 수정 방향 관련해서 아래와 같은 의견들이 정리되었는데요.
  - 메인 페이지의 nav 탭(전체, 모집예정, 모집 중, 모집 종료)을 구분해야하나? 줄이자.
    - 모집 중, 모집 예정은 합쳐서 기간 순으로 정렬하고
    - 모집 종료를 없애자
  - 모집의 구분이 더 뚜렷하고 명확하면 좋겠다.

위 의견들을 바탕으로 3.0.0 시작하면서 피그마 작업을 같이 해봐야 변경 범위가 확실해질 것 같습니다.
 

#### 2. 텍스트 크기
제목 텍스트 크기 정도라면 어느 제목을 말씀하시는 걸까요? 
전체/모집 예정 ... 같은 nav 탭 제목을 말씀하시는 걸까요? 아니면 '지원하기' 같은 홈페이지 제목을 말씀하시는 걸까요?

#### 3. 리스트 컴포넌트 분리
리스트 컴포넌트 분리 3.0.0에서 진행하겠습니다.

2022-07-28 01:11 UTC, soyi47 commented on frontend/src/pages/Recruits/Recruits.js
> +              <div className={styles["empty-state-box"]}>해당하는 공고가 존재하지 않습니다.</div>
메인 페이지 UI 관련해서 논의하기로, 탭의 수를 줄이자는 의견이 많아서 지금 문구를 정해두어도 금방 수정될 것이라 판단했습니다.
그래서 우선 모든 탭에 공통으로 적용할 수 있는 문구를 고민했고요.
여러 채용 사이트에서 많이 사용하는 '모집 공고'라는 표현을 가져와봤습니다.

'공고'라는 표현 대신 '모집'이라는 표현을 사용한다면 아래와 같이 수정해볼 수도 있을 것 같아요.

- 진행 중인 모집이 없습니다.
- 진행 예정인 모집이 없습니다.
- 진행 완료된 모집이 없습니다.

2022-07-28 01:26 UTC, KangYunHo1221 approved these changes

2022-07-28 01:27 UTC, KangYunHo1221 approved these changes
고생하셨습니다 :)

2022-07-28 01:36 UTC, hwangstar156 approved these changes

2022-07-28 01:36 UTC, hwangstar156 commented on frontend/src/pages/Recruits/Recruits.js
> +              <div className={styles["empty-state-box"]}>해당하는 공고가 존재하지 않습니다.</div>
저도 '모집 예정인 ㅇㅇ이 없습니다', '모집 중인 ㅇㅇ이 없습니다', '모집 종료된 ㅇㅇ이 없습니다' 부분이 좋은 것 같습니다..!

2022-07-28 01:50 UTC, woowahan-pjs commented on frontend/src/pages/Recruits/Recruits.js
> +              <div className={styles["empty-state-box"]}>해당하는 공고가 존재하지 않습니다.</div>
#382 로 이어지겠네요. 참고로 서버는 아래와 같은 문구를 사용합니다.

- 지원 불가능한 모집입니다.
- 모집 중인 모집은 삭제할 수 없습니다.
- 모집 중인 모집은 삭제할 수 없다.

2022-07-28 03:08 UTC, woowapark commented on frontend/src/pages/Recruits/Recruits.js
> +              <div className={styles["empty-state-box"]}>해당하는 공고가 존재하지 않습니다.</div>
음 서버에서 요렇게 사용하고 있다면 일관되게 맞추는 게 좋을 것 같은데요.      
#382 같은 이슈가 이미 있다면 바꾸는 경우 이 이슈에서 프론트-백엔드 모두 맞춰서 바꾸고,      
이번 PR에서는 '해당하는 모집이 없습니다'로 하면 어떨까요?

2022-07-28 03:09 UTC, woowapark commented
@soyi47 
제목 텍스트 크기는 'nav 탭 제목' 폰트 사이즈 이야기였습니다 🙂

2022-07-28 04:47 UTC, soyi47 commented on frontend/src/pages/Recruits/Recruits.js
> +              <div className={styles["empty-state-box"]}>해당하는 공고가 존재하지 않습니다.</div>
@woowahan-pjs @woowapark 
좋습니다. 이번 PR에서는 '해당하는 모집이 없습니다.'로 변경하면 될까요?

2022-07-28 12:20 UTC, woowahan-pjs commented on frontend/src/pages/Recruits/Recruits.js
> +              <div className={styles["empty-state-box"]}>해당하는 공고가 존재하지 않습니다.</div>
좋아요!

2022-07-28 12:21 UTC, thenewpark commented on frontend/src/pages/Recruits/Recruits.js
> +              <div className={styles["empty-state-box"]}>해당하는 공고가 존재하지 않습니다.</div>
좋아요!(2)

2022-07-28 12:22 UTC, woowapark commented on frontend/src/pages/Recruits/Recruits.js
> +              <div className={styles["empty-state-box"]}>해당하는 공고가 존재하지 않습니다.</div>
좋아요!(2)

2022-07-29 01:34 UTC, soyi47 commented on frontend/src/pages/Recruits/Recruits.js
> +              <div className={styles["empty-state-box"]}>해당하는 공고가 존재하지 않습니다.</div>
@woowahan-pjs @woowapark

1. 안내 메시지를 수정했고 https://github.com/woowacourse/service-apply/pull/577/commits/57dad3083a48a28d8b3119f2e385175909fdfd27
2. 폰트 사이즈도 변경했습니다~ https://github.com/woowacourse/service-apply/pull/577/commits/140e6a3e84b0d55c689cf4386330bef2d32480d1

2022-07-29 03:07 UTC, woowapark approved these changes
고생하셨습니다~! 👏 
![스크린샷 2022-07-29 오후 12 00 11](https://user-images.githubusercontent.com/81607552/181674727-dd0a16a5-23ad-4fb2-9b41-28dd98d180ab.png)

2022-07-29 03:07 UTC, woowapark commented on frontend/src/pages/Recruits/Recruits.module.css
> +
작은 스크린에서 크기 조정될 때도 `.tab-item` 과 맞춰주기 위함이라면        
요렇게 같이 써도 좋을 것 같네요 🙂
```css 
.tab-item, .empty-state-box {
    font-size: 0.875rem;
}
```

2022-07-29 04:41 UTC, soyi47 commented on frontend/src/pages/Recruits/Recruits.module.css
> +
앗 그러네요, 수정했습니다! https://github.com/woowacourse/service-apply/pull/577/commits/9ef178efc8c67dec4d1b7386a452ef3c959aeb68

2022-08-01 04:15 UTC, woowapark commented
@woowahan-pjs  
확인 후 머지 부탁드립니다~! 🙏

2022-08-01 04:27 UTC, woowahan-pjs approved these changes
고생하셨습니다. 👍

2022-08-01 04:36 UTC, merged