feat: apply filtering UI, floating-button, and change global background-color
woowacourse/service-apply pull request #610
Opened 2022-08-27 12:06 UTC by hwangstar156

Resolves #601 

## 해결하려는 문제가 무엇인가요?

- 현재 지원플랫폼에 존재하지 않는 문의하기 기능을 floating-button을 추가한다.
- global background color를 변경한다.
- 코스별로 필터링할수 있는 탭바 UI를 추가한다.

## 어떻게 해결했나요?

수정전
<img width="1790" alt="스크린샷 2022-08-27 오후 8 49 17" src="https://user-images.githubusercontent.com/85891751/187028891-e0303230-226e-4f31-a3da-39e16f59f0e1.png">

수정후
<img width="1792" alt="스크린샷 2022-08-27 오후 8 13 46" src="https://user-images.githubusercontent.com/85891751/187028907-118caea9-b50c-4ccd-a57a-8e1d08d62aec.png">
<img width="1789" alt="스크린샷 2022-08-27 오후 8 13 59" src="https://user-images.githubusercontent.com/85891751/187028908-90542742-4167-4f28-bc9e-42595bc3d08a.png">
<img width="296" alt="스크린샷 2022-08-27 오후 8 14 20" src="https://user-images.githubusercontent.com/85891751/187028910-5431e317-d03b-459b-9122-1f24fcd54a55.png">

## 어떤 부분에 집중하여 리뷰하여야 할까요?

component에서 typescript를 이용할때 props의 타입을 interface혹은 인자에 인라인으로 줄때의 기준을 어떻게 할지에 대해서 여러분들의 의견이 궁금합니다!

디자인을 인프런의 문의하기를 바탕으로 임의로 해보았는데 디자인에 대한 의견이 궁금합니다!

필터링할수 있는 탭바에서 모바일일때 현재 없애는것만 구현하였는데 모바일에서 UI를 어떻게 할지 의견 부탁드립니다!

<img width="1205" alt="스크린샷 2022-08-27 오후 9 03 36" src="https://user-images.githubusercontent.com/85891751/187029404-575bc428-95ff-4b5e-bead-3f00bd34b3ab.png">
추가적으로 react-icons 사용했을때 cra에서 자동으로 tree-shaking을 해줘서 성능상 큰문제가 없는것 확인했습니다!

## RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)
c: 웬만하면 반영해 주세요. (Comment)
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2022-08-29 17:19 UTC, SunYoungKwon commented on frontend/src/constants/tab.js
> +  WOOWA_TECH_CAMP_PRO: "우아한 테크캠프 프로",
'우아한테크코스' 전부 붙여서 쓰는것으로 알고있습니다. 나머지도 띄어쓰기 확인해보면 좋겠어요!

2022-08-29 17:19 UTC, SunYoungKwon commented on frontend/src/pages/Recruits/Recruits.js
> +          ))}
`map`을 사용했는데, `key`가 없어요

2022-08-29 17:19 UTC, SunYoungKwon commented on frontend/src/pages/Recruits/Recruits.module.css
> +  }
모바일에선 탭을 안보여주나요? 
모바일에서 이미 탭이 선택된 특정 주소로 접근하면 어떻게되나요?

2022-08-29 17:22 UTC, SunYoungKwon commented
안녕하세요! 3기 썬이에요.

RCA 룰이 있지만, 일하다보면 적절한 타이밍에 Approve 누르러 올 수 없을것 같아 Comment로 남겨요.
리뷰 확인해보시고 필요에따라 반영해주세요

근로 화이팅!

2022-08-29 18:39 UTC, lokba requested changes
자스민~ 반갑습니다. 🥷
방학인데도 개발 하신다고 고생 많으셨습니다.
리뷰가 늦어진 점 이해 부탁드립니다. 
코드 하나하나 살펴보면서, 제 의견을 적어봤는데 답변 부탁드립니다.

> component에서 typescript를 이용할때 props의 타입을 interface혹은 인자에 인라인으로 줄때의 기준을 어떻게 할지에 대해서 여러분들의 의견이 궁금합니다!

비녀 PR에도 남겼지만, 해당 컨벤션에 대해서는 다같이 모여서 애기를 나눠봐야 할 것 같습니다. 


> 디자인을 인프런의 문의하기를 바탕으로 임의로 해보았는데 디자인에 대한 의견이 궁금합니다!

디자인 아주 취향저격입니다. 자스민 때문에, 문의 많이 들어올 것 같네요.

> 필터링할수 있는 탭바에서 모바일일때 현재 없애는것만 구현하였는데 모바일에서 UI를 어떻게 할지 의견 부탁드립니다!

저는 기존 형태로 가져갔으면 합니다. 모바일인 경우, 아래에 width를 적절하게 조절하면 될 것 같아 보입니다. 
```css
.course-tab-list {
  display: flex;
  width: 60%;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 1rem;
}
```

2022-08-29 18:39 UTC, lokba commented on frontend/src/color.css
> +  --dark-black: #000;
r : 비녀에게 남긴 피드백이랑 동일한 상황이라서 링크 남깁니다. [관련 링크](https://github.com/woowacourse/service-apply/pull/609#discussion_r957509232)

2022-08-29 18:39 UTC, lokba commented on frontend/src/components/@common/TabItem/TabItem.module.css
> +.checked {
r : 피그마 상에는 hover시 font-weight 디자인을 주고 있는데요. 확인 부탁드리겠습니다.

2022-08-29 18:39 UTC, lokba commented on frontend/src/components/@common/TabItem/TabItem.tsx
> +interface TabItemProps {
a : interface로 분리해서 타입을 선언하는 것이 깔끔해 보이네요.

2022-08-29 18:39 UTC, lokba commented on frontend/src/components/@common/TabItem/TabItem.tsx
> +      className={classNames(styles["tab-item-wrapper"], { [styles["checked"]]: checked })}
c : 현재 상태에 따른 활성화 유무에 따른 props 네이밍이 제각각이네요.

비녀(Indicator) : disabled
우디(Indicator 제안) : active
자스민(TabItem) : checked

저는 활성화 유무에 관련된 네이밍을 통일화 했으면 합니다. 저의 개인적인 취향은 active입니다. 

### 여러분 어떻게 생각하시나요? 🤔

2022-08-29 18:39 UTC, lokba commented on frontend/src/components/FloatingButton/FloatingButton.module.css
> +  position: fixed;
r : css 코드 작성에 대한 컨벤션이 없어 통일성이 없는 상태입니다만, 최소한 관련된 속성끼리 묶어놓는 것이 좋을 것 같습니다. 

예시 1) position, bottom, right
예시 2) display, gap, align-items

2022-08-29 18:39 UTC, lokba commented on frontend/src/components/FloatingButton/FloatingButton.module.css
> +    display: none;
모바일 버전 디자인 깔끔하게 이쁘네요. 👍

2022-08-29 18:39 UTC, lokba commented on frontend/src/components/FloatingButton/FloatingButton.tsx
> +    <a href="https://pf.kakao.com/_budWj" className={styles["floating-wrapper"]}>
r : Footer에 있는 아이콘(깃헙, 유튜브, 인스타)의 경우 `target="_blank"` 속성 값을 부여하고 있습니다. 플로팅 버튼 또한 동일하게 가져가면 좋을 것 같습니다.

2022-08-29 18:39 UTC, lokba commented on frontend/src/pages/Recruits/Recruits.js
> +  const [courseStatus, setCourseStatus] = useState("전체");
```suggestion
  const [courseTabStatus, setCourseTabStatus] = useState("전체");
```

r : 상수명(COURSE_TAB_LIST)라는 점에서, 네이밍을 조금 더 명시적으로 가져가는 것은 어떨까요?

2022-08-29 18:48 UTC, lokba requested changes

2022-08-29 18:48 UTC, lokba commented on frontend/src/components/FloatingButton/FloatingButton.tsx
> +    <a href="https://pf.kakao.com/_budWj" className={styles["floating-wrapper"]}>
r : 소피아 PR이 merge 된 후에, 카카오 문의하기 url을 `constants/url.ts`로 관리해주세요!!

2022-08-30 09:51 UTC, KangYunHo1221 requested changes
아따 마 고생하셨습니다.
방학이지만 열심히 해주셨네요.
디자인 겁나게 이쁘네요 전 만족합니다 ㅋㅋㅋ

코멘트 남겼으니 확인 부탁드립니다. 좀 늦었네요 죄송합니다

2022-08-30 09:51 UTC, KangYunHo1221 commented on frontend/src/components/@common/TabItem/TabItem.tsx
> +      className={classNames(styles["tab-item-wrapper"], { [styles["checked"]]: checked })}
저는 우선은 이전에 작업 돼 있는 코드가 아마 disabled로 돼 있었던 걸로 기억합니다.
active도 좋아보이네요

2022-08-30 09:51 UTC, KangYunHo1221 commented on frontend/src/components/FloatingButton/FloatingButton.module.css
> +  position: fixed;
동의합니다. 관련해서 컨벤션을 정하는게 좋을 것 같긴 하네요

2022-08-30 09:51 UTC, KangYunHo1221 commented on frontend/src/pages/Recruits/Recruits.module.css
> +  }
모바일에서도 탭을 보여줘야 할 것 같은데 다들 어떻게 생각하시나요?

2022-08-30 09:51 UTC, KangYunHo1221 commented on frontend/src/pages/Recruits/Recruits.js
> +        <div className={styles["course-tab-list"]}>
r:
figma에 보면 Course-Tab-List만 존재하고 이전에 있던 tab-list는 삭제하는 걸로 보입니다.
확인하고 수정부탁드립니다.
이걸 삭제하게 되면 밑에 모바일 화면에서 course-tab이 display:none으로 돼 있는 코멘트도 해결 가능하지 않을까 싶네요. tab-list 대신 course-tab을 보여주면 될 것 같습니다.

2022-09-01 02:30 UTC, soyi47 requested changes
자스민~ 작업하느라 고생하셨습니다. 
피그마와 다르거나 UI 깨지는 부분 위주로 확인하여 리뷰 남겼습니다.

### 확인하고 싶은 점
- 모집 필터링 관련해서, UI 작업만 하고 '모집 제목'에 따른 필터링 기능 자체는 이번 작업에서 제외되는 게 맞나요?

<br >

### 질문에 대한 답변
> component에서 typescript를 이용할때 props의 타입을 interface혹은 인자에 인라인으로 줄때의 기준을 어떻게 할지에 대해서 여러분들의 의견이 궁금합니다!

록바 의견대로 다같이 한번 논의해보면 좋을 것 같아요. 
저는 주로 props의 타입을 줄 때는 인라인으로 주기보다는 type이나 interface로 작성해서 지정했습니다.

> 디자인을 인프런의 문의하기를 바탕으로 임의로 해보았는데 디자인에 대한 의견이 궁금합니다!

좋습니다. 모바일 디자인 분기 지점에 대한 코멘트만 한번 확인해주세요. 👍 

> 필터링할수 있는 탭바에서 모바일일때 현재 없애는것만 구현하였는데 모바일에서 UI를 어떻게 할지 의견 부탁드립니다!

코멘트 남겨뒀습니다.

2022-09-01 02:30 UTC, soyi47 commented on frontend/src/pages/Recruits/Recruits.module.css
> +  }
r: 모바일에서도 탭을 보여줘야 한다고 생각합니다.
모바일에서는 코스 탭 리스트의 컨텐츠가 깨지지 않는 최소한의 너비를 주고 가로 스크롤을 주는 방식도 괜찮을 것 같아요.

2022-09-01 02:30 UTC, soyi47 commented on frontend/src/components/FloatingButton/FloatingButton.module.css
> +}
r: 다른 파일들을 봤을 때는, 모바일 버전이 적용되는 조건은 `max-width: 513px`로 확인했습니다.
모바일 버전 분기 조건을 `max-width: 513px`으로 변경해주세요.

(여러 파일을 보니 512px, 513px을 혼용해서 사용하고 있네요. 이 부분은 한번 다같이 정리가 필요할 것 같아요.)

2022-09-01 05:35 UTC, lokba commented on frontend/src/pages/Recruits/Recruits.module.css
> +  }
저는 아래 링크에 의견 남겼습니다. 
https://github.com/woowacourse/service-apply/pull/610#pullrequestreview-1089151018

2022-09-01 05:40 UTC, lokba commented on frontend/src/components/@common/TabItem/TabItem.tsx
> +      className={classNames(styles["tab-item-wrapper"], { [styles["checked"]]: checked })}
@soyi47 

좋은 의견 감사합니다.

> 예를 들어 Indicator의 경우 '클릭이 가능한가'라는 점에서 상태가 결정되고
현재 StatusIndicator의 경우 `button` 태그가 아닌, `p or span`태그로 구성되어있습니다. 
그렇기에 Indicator의 경우 `클릭`에 따른 상태 결정은 아닌 것으로 보이네요.

>각 컴포넌트 별로 더 적합한 네이밍이 있다면 그 이름을 사용하는 것을 우선으로 하고, 꼭 통일을 목표로 맞추지는 않았으면 좋겠다. 
소피아의 의견도 맞는 것 같습니다! 이것도 회의시간에 애기해보시죠

2022-09-01 05:46 UTC, lokba commented on frontend/src/components/FloatingButton/FloatingButton.module.css
> +}
오호라 섬세한 리뷰 감사합니다!

2022-09-01 08:28 UTC, hwangstar156 commented on frontend/src/constants/tab.js
> +  WOOWA_TECH_CAMP_PRO: "우아한 테크캠프 프로",
넵 수정했습니다!

2022-09-01 16:39 UTC, woowapark requested changes
기존에 논의되는 것 외에 추가로 확인해볼 부분들에 대해서만 코멘트 남겨보았습니다 🙂 
한번 같이 확인 부탁드릴게요~!       
작업 고생 많으셨습니다! 👍

2022-09-01 16:39 UTC, woowapark commented on frontend/src/components/@common/TabItem/TabItem.tsx
> +      className={classNames(styles["tab-item-wrapper"], { [styles["checked"]]: checked })}
a:       
개인적으로 가능하면 자주 사용되는 '기본 상태'에 대해서는 최소한의 props만 지정해서 사용할 수 있게 해주는 편이 좋다고 생각하는데요! 🙂 휴먼 에러도 방지할 수 있고, 기본 상태와 아닌 상태(추가 옵션이 필요한 상태)에 대한 구분이나, 사용하는 입장에서의 편의성도 조금 더 높다고 생각합니다.          
네이밍에서 일관성에 대해 이야기해본다면 논의에서 '기본 상태일 때에도 props 지정이 필요한 이름일지' 에 대해서도 함께 고려해보면 어떨까요?

2022-09-01 16:39 UTC, woowapark commented on frontend/src/components/FloatingButton/FloatingButton.module.css
> +  position: fixed;
c: CSS에도 css lint나 stylelint를 적용해봐도 좋을 것 같네요 🙂 컨벤션과 관련해 자동화할 수 있는 부분은 최대한 알아서 이루어질 수 있게 하는 방법을 찾아봐주시면 좋을 것 같아요!

2022-09-01 16:39 UTC, woowapark commented on frontend/src/components/FloatingButton/FloatingButton.tsx
> +        <RiKakaoTalkFill color="#ffe812" size={30} />
r: 색상은 하얀색으로 두어도 괜찮을 것 같은데 어떠신가요?      
- 이미 아이콘과 텍스트로 충분히 정보 전달이 되고 있고 
- 서비스에서 주로 사용되는 색상 톤과 꽤 다르다보니 버튼으로 시선이 많이 가게 되는 것 같습니다. 문의하기가 눈에 띄어야 하기는 하지만, 이미 플로팅 버튼이라는 UI 자체로 인지하는 데에는 문제가 없는 것 같아, 실제로 지원할 모집 아이템들보다 시선이 갈 필요는 없을 것 같아요

2022-09-01 16:39 UTC, woowapark commented on frontend/src/components/FloatingButton/FloatingButton.tsx
> +const FloatingButton = () => {
r: '카카오 문의하기'에 대한 여러 구체적인 정보들이 들어가있는 상태인데, 이름이 그에 비해 너무 일반적인 건 아닐까요? 플로팅 버튼을 재사용할 곳이 없다면 좀 더 구체적으로 문의하기를 위한 플로팅 버튼이라는 게 이름에 드러나도 괜찮을 것 같은데 어떠신가요?

2022-09-01 16:39 UTC, woowapark commented on frontend/src/constants/tab.js
> +  WOOWA_TECH_CAMP_PRO: "우아한 테크캠프 프로",
자스민 혹시 수정하신 사항이 커밋되지 않은 걸까요?-?     
아직 띄어쓰기가 그대로 남아있어 여쭤봅니다~

2022-09-01 16:39 UTC, woowapark commented on frontend/src/pages/Recruits/Recruits.js
> +  const [courseStatus, setCourseStatus] = useState("전체");
r: 이미 상수화 해둔 부분이니 기본값도 상수를 활용하면 어떨까요~?

2022-09-01 16:54 UTC, hwangstar156 commented on frontend/src/constants/tab.js
> +  WOOWA_TECH_CAMP_PRO: "우아한 테크캠프 프로",
아직 push를 안하고 commit만 하고 있어서 그런것 같습니다! 곧 push 하겠습니다!

2022-09-01 16:57 UTC, hwangstar156 commented on frontend/src/pages/Recruits/Recruits.js
> +          ))}
미처 인지하지 못했네요! 수정하였습니다!

2022-09-01 17:02 UTC, hwangstar156 commented on frontend/src/color.css
> +  --dark-black: #000;
확인했습니다! 일단은 `--dark-black`을 컨벤션에 맞춰 `--black-004`로 변경하였습니다. 록바의 의견은 공원의 코멘트대로 다음 이슈에서 이 숫자들을 어떻게 논의할지 따로 해보는것이 좋을것 같습니다.

2022-09-01 17:06 UTC, hwangstar156 commented on frontend/src/components/@common/TabItem/TabItem.module.css
> +.checked {
피그마의 hover 디자인을 확인 하지 못했었네요.. 수정했습니다!

2022-09-01 17:15 UTC, hwangstar156 commented on frontend/src/components/FloatingButton/FloatingButton.module.css
> +  position: fixed;
저도 록바 의견에 동의합니다. 따로 어떻게 묶을것이고 순서는 어떻게 할지 묶은것 끼리 한칸 띄울지 등등의 컨벤션은 한번 같이 정하면 좋을것 같습니다.

- position 관련
- display 관련
- width, height
- color, backgroundcolor
- font
- etc

일단은 이렇게 묶어서 수정하였습니다!

2022-09-01 17:18 UTC, hwangstar156 commented on frontend/src/components/FloatingButton/FloatingButton.tsx
> +    <a href="https://pf.kakao.com/_budWj" className={styles["floating-wrapper"]}>
역시 록바.. 미처 보지못한 부분까지 캐치해주셨네요👍. 수정하였습니다! 추후 소피아 pr이 머지된후 url 상수화까지 진행하겠습니다!

2022-09-01 17:19 UTC, hwangstar156 commented on frontend/src/pages/Recruits/Recruits.js
> +  const [courseStatus, setCourseStatus] = useState("전체");
수정했습니다! 훨씬 의미적으로 명확하니 좋네요.

2022-09-01 17:26 UTC, hwangstar156 commented on frontend/src/components/FloatingButton/FloatingButton.module.css
> +}
<img width="290" alt="스크린샷 2022-09-02 오전 2 24 24" src="https://user-images.githubusercontent.com/85891751/187975328-fd74a557-43b4-4a22-a297-309af21bf3da.png">

pc-main-width가 800이여서 max를 800으로 설정했었는데 밑의 narrow를 보지 못했네요. 수정하였습니다! 또 512, 513 되있는것은 root에 되어있는 값대로 512로 맞춰도 될것 같습니다!

2022-09-01 17:27 UTC, hwangstar156 commented on frontend/src/pages/Recruits/Recruits.js
> +  const [courseStatus, setCourseStatus] = useState("전체");
`COURSE_TAB.ALL.label`을 이용하여서 수정하였습니다!

2022-09-01 17:30 UTC, hwangstar156 commented on frontend/src/components/FloatingButton/FloatingButton.tsx
> +        <RiKakaoTalkFill color="#ffe812" size={30} />
<img width="1790" alt="스크린샷 2022-09-02 오전 2 28 42" src="https://user-images.githubusercontent.com/85891751/187976219-b609c09b-ec06-429c-802f-503114477d4b.png">

직접 적용을 해보니 카카오 원색보다 흰색이 훨씬 어울리는것 같습니다. 확실히 기존꺼와 서비스의 주요 톤과 꽤 달라서 플로팅 버튼에만 눈이 가는것 같은데 서비스톤과 맞춰주니 확실히 자연스러운 이미지로 보이는것 같습니다!

2022-09-01 17:38 UTC, hwangstar156 commented on frontend/src/components/FloatingButton/FloatingButton.tsx
> +const FloatingButton = () => {
공용 컴포넌트가 아니여서 일부러 common밖에 뺏는데 이름은 굉장히 공용 컴포넌트처럼 되버렸네요.. `InquiryFloatingButton`과 `QuestionFloatingButton` 둘중 고민하다가 좀더 의미에 맞는것 같은 `InquiryFloatingButton`로 네이밍 변경하였습니다!

2022-09-01 17:38 UTC, hwangstar156 commented on frontend/src/components/@common/TabItem/TabItem.module.css
> +}
수정했습니다!

2022-09-01 17:50 UTC, lokba commented on frontend/src/components/FloatingButton/FloatingButton.tsx
> +const FloatingButton = () => {
공원...피드백 좋네요.. 한수 배우고 갑니다.

2022-09-01 18:01 UTC, hwangstar156 commented on frontend/src/pages/Recruits/Recruits.module.css
> +
space-between option을 사용하느라고 width를 제한해버렸네요.. 좋은 피드백 감사합니다!

2022-09-01 18:02 UTC, hwangstar156 commented
![ezgif com-gif-maker (10)](https://user-images.githubusercontent.com/85891751/187982196-4c79ffb9-0ea6-4616-a9c6-47d97d0f1b48.gif)

이번에 새로 추가한 코스별 탭의 모바일 버전입니다. 디자인 한번 봐주시면 감사하겠습니다!

2022-09-01 18:02 UTC, hwangstar156 commented on frontend/src/pages/Recruits/Recruits.js
> +        <div className={styles["course-tab-list"]}>
모바일 버전 디자인에 반영하여 수정하였습니다😎

2022-09-01 18:29 UTC, lokba commented on frontend/src/components/FloatingButton/FloatingButton.module.css
> +  position: fixed;
현재 프로젝트에서 layout과 paint에 관련된 css를 나눠서 하고 있는데, 저는 괜찮더라고요.

예시
```css
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 1rem;
  padding: 7px 12px;
  border: none;
  border-radius: 12px;
  
  background-color: ${({ theme }) => theme.colors.pink_200};
  color: ${({ theme }) => theme.colors.white_50};
```

2022-09-02 04:02 UTC, hwangstar156 commented
@soyi47 

>모집 필터링 관련해서, UI 작업만 하고 '모집 제목'에 따른 필터링 기능 자체는 이번 작업에서 제외되는 게 맞나요?

넵! 모집에 따른 필터링 기능은 백엔드와 논의후 해야될것 같습니다!

2022-09-07 06:40 UTC, soyi47 requested changes
자스민~ 리뷰 반영 확인하러 왔습니다!
잘 수정해주신 거 확인했고요. 👍

지난 회의에 논의한 대로 
1. 모집 아이템 필터링 로직 추가
2. 필터링 탭 디자인 개선

작업 후 리뷰 재요청 부탁드립니다~

### 추가로 확인 필요한 부분
- Footer가 영역만 잡히고 안 보이는 상황인데 작업 편의를 위해 임시로 해두신 걸까요? 한번 확인부탁드려요~
![image](https://user-images.githubusercontent.com/71116429/188805765-44b4f98a-169d-42d3-af91-d6419ccd23e6.png)

2022-09-11 04:55 UTC, lokba commented
@hwangstar156 

자스민~ 타입스크립트 부분은 코드 컨벤션 맞춰서 수정해야 할 것 같네요 :)
수정한 후에 코드 다시 보겠습니다!!

2022-09-14 04:13 UTC, soyi47 requested changes
안녕하세요, 자스민!

새벽 시간 빠르게 작업해주시느라 고생 많으셨습니다. 👍👍👍
오류와 수정 필요한 부분들이 있어 Request changes 남깁니다.
확인해보시고 답변과 수정 작업 부탁드려요!

2022-09-14 04:13 UTC, soyi47 commented on frontend/src/pages/Recruits/Recruits.js
>    );
r: 아래와 같이 필터링이 제대로 동작하지 않습니다. 

![image](https://user-images.githubusercontent.com/71116429/190057340-d3e07dc2-b4a4-40b9-ac7f-8229ccb7363b.png)

제가 파악하기로는 아래 부분들에 문제가 있는 것 같아요.
- 탭 선택 상태를 유지하기 위해 URLSearchParam에 status를 관리하려고 한 것 같네요. 하지만 course-tab item 선택했을 때 searchParams status를 업데이트하는 로직이 없습니다.
- selectedTab의 업데이트가 없어서, filteredRecruitment도 업데이트 되지 않습니다.

우선 filteredRecruitment의 useMemo 의존성 배열에 selectedTab 대신 courseTabStatus 상태를 넣어주면 필터링이 동작하는 것으로 보입니다. 로컬에서는 그렇게 수정해서 다른 부분 오류 없는지 테스트해보고 있는데 참고해서 수정해주세요.

해당 부분 오류 맞는지 확인해보시고 URLSearchParam 업데이트 로직 추가와 함께 수정해주시면 좋겠습니다.

2022-09-14 04:13 UTC, soyi47 commented on frontend/src/pages/Recruits/Recruits.js
> +      return sortedRecruitmentItem.filter(recruitmentItem => recruitmentItem.title.includes(courseTabStatus));
r: 
아래와 같이 '우아한테크캠프' 목록에 '우아한테크캠프 프로' 모집 아이템도 포함되는 방식으로 보입니다.
제외 시켜야 할 것 같아요.

![image](https://user-images.githubusercontent.com/71116429/190056868-e61cfbc0-a961-4490-8e5c-a4b8eda3690c.png)

2022-09-14 04:13 UTC, soyi47 commented on frontend/src/constants/tab.js
> +  },
r: 실제 모집에서는 아래와 같이 '우아한테크캠프 Pro'라는 이름을 사용하고 있어요. 
COURSE_TAB에서 도 같은 이름으로 사용하는 게 좋겠습니다.

![image](https://user-images.githubusercontent.com/71116429/190057708-0ae19c05-6faf-4ed0-838d-9e7e6afa7779.png)

2022-09-14 05:58 UTC, hwangstar156 commented on frontend/src/pages/Recruits/Recruits.js
>    );
useMemo의 dependency array에 courseTabStatus를 넣어서 작동하도록 수정하였습니다! selectTab은 위의 전체, 모집예정, 모집중, 모집 종료를 관리하는 탭이여서 의존성배열을 대체하는게 아니라 selectTab, courseTabStatus모두 넣어주어야 합니다!

2022-09-14 06:01 UTC, hwangstar156 commented on frontend/src/pages/Recruits/Recruits.js
> +      return sortedRecruitmentItem.filter(recruitmentItem => recruitmentItem.title.includes(courseTabStatus));
확인했습니다! 이부분에 대해서는 약간의 고민이 필요할것 같은데 지금은 이렇게 구현하였습니다!
- 전체일 경우 -> 바로 recruitment를 return함
- 우아한테크코스일 경우 -> 우아한테크코스가 들어가기만 한다면 return함
- 우아한테크캠프, 우아한테크캠프 PRO -> 뒤의 기수부분을 제외하고 현재 courseTabStatus와 코스명(우아한테크캠프, 우아한테크캠프 PRO)와 완전히 일치한다면 return

2022-09-14 06:02 UTC, hwangstar156 commented on frontend/src/constants/tab.js
> +  },
PRO로 수정하였습니다!

2022-09-14 07:59 UTC, soyi47 commented on frontend/src/constants/tab.js
> +  },
PRO 말고 Pro! 로 수정해주시죠

2022-09-14 08:52 UTC, lokba requested changes
자스민~ 바쁘신 와중에 수정하신다고 고생많으십니다.

1. nav 영역 삭제 필요

```javascript
// Recruits.js 
<nav className={styles.tab}>
      <ul className={styles["tab-list"]}>
            ...
      </ul>
</nav>
```

```css
// Recruits.module.css
.recruitment-list-box {
  width: var(--pc-main-width);
  /* margin: 3.625rem auto 0; */
}
```

바쁘실까봐, 코드도 첨삭하였습니다. Recruits.js에 nav 영역 삭제한 후 `.recruitment-list-box`영역에서 margin 값 삭제하면 될 것 같네요. 

2. 모바일 버전에서 `코스 별 탭 메뉴`가 보이지 않네요. 


해당 문제 해결된 후에, 한번 더 리뷰하도록 하겠습니다.

2022-09-14 15:26 UTC, hwangstar156 commented
@lokba 

수정했었던 부분인데 local에서만 적용됬던것 같네요! 다시 수정하였습니다!

2022-09-14 16:34 UTC, KangYunHo1221 commented on frontend/src/pages/Recruits/Recruits.js
> +      return sortedRecruitmentItem.filter(recruitmentItem => recruitmentItem.title.includes(courseTabStatus));
요거는 시간을 좀 들여서 나중에 백엔드랑도 말해보면 좋겠네요.
제 생각에는 현재는 작동에 문제가 없으니 후일을 도모하더라도, course의 종류에 대한 정보를 api가 제공해주는게 맞지 않나 생각이 들어요

2022-09-14 16:54 UTC, KangYunHo1221 requested changes
늦은시간에 작업하느라 고생이 많습니다 자스민... 우리 힘내보아요

코멘트 남겼습니다! 확인해 주세요 :)

+번외)
필수는 아니지만..
모바일에선 이쁜데
<img width="281" alt="image" src="https://user-images.githubusercontent.com/72348351/190215433-4a44e9de-708e-46e3-95a0-ccabfa64a702.png">

desktop에선 안이쁠지도..?
<img width="340" alt="image" src="https://user-images.githubusercontent.com/72348351/190215596-049a78ef-1e68-4976-af02-45c0266b825f.png">

2022-09-14 16:54 UTC, KangYunHo1221 commented on frontend/src/constants/tab.js
> +];
여기부분 ts로 록바, 우디가 진행한 파일인데 머지가 안돼서 스밍꺼에는 js로 돼 있군요...
ts로 변경해서 진행하는건 어떨까요?
ts 마이그레이션 된 다른 ts파일처럼 as const 써주면 label, name도 알 수 있어서 좋을 것 같습니다.

2022-09-17 15:08 UTC, soyi47 requested changes
- eol 에러 해결된 것 확인했습니다. 👍
- @lokba 록바가 남겨준 리뷰 아직 반영 안 되었네요. 데스크탑 사이즈에서도 nav 영역이 제거되어야 할 것 같은데요. 모바일 사이즈에서 display: none으로만 보이지 않도록 해두었네요. 다시 확인 부탁드립니다.
- develop으로 rebase도 해주세요~

2022-09-19 09:53 UTC, hwangstar156 commented
@soyi47 

desktop 버전에서도 navBar 삭제하였습니다!

2022-09-19 09:54 UTC, hwangstar156 commented on frontend/src/constants/tab.js
> +];
록바, 우디가 머지되고나서 같이 고치는게 좋을것 같습니다😊

2022-09-19 09:54 UTC, KangYunHo1221 approved these changes
자스민 UI와 코드 오프라인으로 같이 확인했습니다.
고생하셨어요 JS민

2022-09-19 11:35 UTC, soyi47 requested changes
리뷰 반영 확인했습니다~
그런데 develop 브랜치를 머지하면서 충돌 생긴 부분들이 정리가 덜 된 것 같아요.
이대로 머지되면 안 될 것 같아서 리뷰 남겨요!

2022-09-19 11:35 UTC, soyi47 commented on frontend/yarn.lock
> +>>>>>>> 055192f510f0c4534f9b93cabe0e78f12d1bfbb6
r: develop을 머지하면서 코드 정리가 덜 된 것 같아요.
여기 외에도 kotilin 폴터의 파일들도 file changes에 섞였는데요.
확인이 필요할 것 같습니다.

2022-09-20 06:13 UTC, greenblues1190 requested changes
고생하셨어요! 배경색 변경 리뷰 달았습니다.

2022-09-20 06:13 UTC, greenblues1190 commented on frontend/src/App.css
> +  background: var(--light-blue);
r: 이번 메인 페이지 외 나머지 UI/UX 변경 논의에서 나온 배경색 변경 적용하면 좋을 것 같습니다!

https://github.com/woowacourse/service-apply/issues/629

2022-09-20 06:47 UTC, lokba approved these changes
수정사항 모두 확인했습니다. 
고생하셨습니다. 자스민~ 😎

2022-09-20 08:13 UTC, greenblues1190 approved these changes
수고하셨습니다 👍

2022-09-20 08:25 UTC, woowapark requested changes
prettierrc, react-app-env.d.ts 파일 요 PR에서 추가된 게 맞는지 한번 확인해주세요~~~

2022-09-20 08:25 UTC, woowapark commented on frontend/src/react-app-env.d.ts
> +/// <reference types="react-scripts" />
@hwangstar156 
요거 이 PR에서 추가된 게 맞나요 ?-? 
prettierrc랑 같이 확인 부탁드릴게요!

2022-09-22 07:25 UTC, hwangstar156 commented on frontend/src/App.css
> +  background: var(--light-blue);
수정했습니다! 😊

2022-09-22 08:39 UTC, hwangstar156 commented on frontend/src/react-app-env.d.ts
> +/// <reference types="react-scripts" />
넵 확인해보니까 첫번째 커밋에서 `react-app-env.d.ts`가 들어갔고 window로 바꿔서 작업했을때 preettierrc가 auto로 변경된것 같네요!

rebase 하는 과정에서  `react-app-env.d.ts`는 제거했습니다! 혹시 prettierrc는 auto로 바꾼다고 했던것 같은데 다시 lf로 바꾸는것이 맞을까요?

2022-09-22 08:42 UTC, hwangstar156 commented
@lokba 

소피아 pr 머지되어서 카카오 문의하기 url 상수화 하여 관리하였습니다!

2022-09-27 10:38 UTC, woowapark requested changes
- @hwangstar156  RecruitmentItem에서 사용하지 않는 props만 한번 더 확인 부탁드릴게요~!  
- @soyi47 아래 부분은 전체 스타일 맞추는 작업 진행하실 때 한번 더 검토해주실 수 있을까요?
  - 모바일 환경에서 탭 아이템이 선택되었을 때 영역과 스크롤바가 겹쳐서 다소 어색해보일 수 있을 것 같아요. 스크롤되는 영역의 높이를 파란색 영역의 높이와 일치시키는 등의 확인이 필요해보입니다.
  <img width="427" alt="tab-height" src="https://user-images.githubusercontent.com/81607552/192504122-b5d84bdb-3f5d-4e0a-ab80-fce907e42ca3.png">

2022-09-27 10:38 UTC, woowapark commented on frontend/src/pages/Recruits/Recruits.js
> +  }, [recruitment, selectedTab, courseTabStatus]);
a: 페이지 레벨에 두기에는 다소 복잡한 로직이 아닌가 싶네요 🤔 정렬도 한번 들어가고, 백엔드 대응 없이 프론트에서 임의로 처리하기로 하면서 파싱도 생각보다 여러 케이스로 이루어지고요. 훅으로 따로 빼는 등의 리팩터링을 고려해보아도 좋을 것 같아요. @soyi47 이후 작업 진행하실 때 한번 검토해주실 수 있을까요?

2022-09-27 10:38 UTC, woowapark commented on frontend/src/pages/Recruits/Recruits.js
> +                  buttonLabel={BUTTON_LABEL[recruitment.status]}
r: `isButtonDisabled`, `buttonLabel` 모두 사용하지 않는 props로 보이는데 맞을까요? 확인 부탁드릴게요 🙏

2022-09-27 10:49 UTC, hwangstar156 commented on frontend/src/pages/Recruits/Recruits.js
> +                  buttonLabel={BUTTON_LABEL[recruitment.status]}
develop을 복사하고 commit을 옮기는 작업중에 충돌나는 부분을 최신것이 아닌 옛날걸로 덮어버린것 같네요. 사용하지 않는 props들은 모두 제거 했습니다.

2022-09-27 15:56 UTC, soyi47 approved these changes
스밍~ 충돌 없는 거 확인했습니다! 고생했어요!

2022-09-27 15:56 UTC, soyi47 commented on frontend/src/pages/Recruits/Recruits.js
> +  }, [recruitment, selectedTab, courseTabStatus]);
@woowapark 
바로 위의 리뷰 코멘트와 함께 확인했습니다! 👍

1. filteredRecruitment useMemo 리팩토링
2. 메인 페이지 필터링 스크롤과 겹치지 않도록 필터링 탭 영역 높이 조절

메인 페이지 소개 문구 작업할 때, 위 두 항목도 함께 검토하겠습니다.

2022-09-28 07:08 UTC, woowapark requested changes
@hwangstar156 color 스타일 규칙 중복 하나 추가로 확인 부탁드릴게요~

2022-09-28 07:08 UTC, woowapark commented on frontend/src/components/form/CheckBox/CheckBox.module.css
>    color: var(--white);
r: color가 두 번 선언된 게 맞나요?-?

2022-09-28 07:18 UTC, hwangstar156 commented on frontend/src/components/form/CheckBox/CheckBox.module.css
>    color: var(--white);
캐치하지 못했네요.. 어떻게 수정했는진 모르겠지만 background가 color로 바껴서 들어간것 같네요;; 수정하였습니다!

2022-09-28 08:46 UTC, woowapark approved these changes
고생하셨습니다~👏👏👏

2022-09-29 01:40 UTC, woowahan-pjs approved these changes
고생하셨습니다. 👍

2022-09-29 01:54 UTC, merged