refactor: migrate modules in api layer to typescript
woowacourse/service-apply pull request #612
Opened 2022-08-28 13:51 UTC by greenblues1190

2022-08-29 17:33 UTC, SunYoungKwon approved these changes
TS 전환 화이팅~

2022-08-29 17:33 UTC, SunYoungKwon commented on frontend/src/pages/MyApplication/MyApplication.js
> +import { fetchMyApplicationForms } from "../../api/applicationForms";
👍 (저게 왜...application-forms 였을까요...?...ㅎ)

2022-08-30 04:27 UTC, hwangstar156 requested changes
안녕하세요 우디, 록바! 방학때 이정도 퀄리티의 pr 고생하셨습니다! 크게 리뷰할 부분이 없을 정도로 좋네요. 수고하셨습니다!

## type alias vs interface

이번에 type alias에 다양한 기능이 추가되었다고 하는데 어떤 기능들이 추가되어서 interface를 대체할수 있다고 했는데 나중에 중복되는 타입이 생기면 extends 대신 intersection을 이용하여 처리하는건가요? 아직까지는 선언병합은 이용하지 않을것 같지만 type alias 하나로 모든것을 대체할수 있을까는 의문이네요!🙃

참고로 저는 개인적으로 intersection이나 union을 쓰거나 mapped type, generic등을 이용하여 어떠한 타입을 새로 만들때 type alias를 이용하고 일반적인 경우에는 interface를 사용해요!

2022-08-30 04:27 UTC, hwangstar156 commented on frontend/types/domains/recruitments.ts
> +  endDateTime: string;
r: startDateTime과 endDateTime모두 yyyy-mm-ddThh:mm 형식으로 오는것 같던데 typescript의 template literal type을 이용해서 바꿔볼수 있지 않을까요?
```suggestion
  startDateTime: `${number}-${number}-${number}T${number}:${number}`;
  endDateTime: `${number}-${number}-${number}T${number}:${number}`;
```

이런식으로 사용하면 그냥 string보다 조금 더 제한될것 같네요😎

2022-08-30 04:27 UTC, hwangstar156 commented on frontend/types/api.ts
> +  email: string;
이 타입도 string에서 `${string}@${string}` 으로 좀 더 제한할수 있을것 같네요.

2022-08-30 04:27 UTC, hwangstar156 commented on frontend/types/api.ts
> +};
a: request, response 타입을 나누어서 관리하는 거 좋네요👍👍

2022-08-30 04:27 UTC, hwangstar156 commented on frontend/types/domains/applicationForms.ts
> +  modifiedDateTime: string;
c: 변경된 시간을 받아오는것 같은데 변경을 아직 안했을때는 어떤 값이 넘어오나요? 이것도 string | null 타입아닐까요?

2022-08-30 04:27 UTC, hwangstar156 commented on frontend/types/api.ts
> +};
c: interface를 이용하면 extends로도 구현할수 있을것 같네요!

2022-08-30 08:39 UTC, KangYunHo1221 commented on frontend/types/domains/recruitments.ts
> +  endDateTime: string;
오 이거 좋네요!

2022-08-30 09:34 UTC, KangYunHo1221 approved these changes
고생하셨습니다 :)
다들 방학 때도 파이팅 하시는군요!!
저는 특별히 수정해야할 건 없을 것 같고, 자스민이 달아준 코멘트 정도만 적용하면 좋을 것 같네요.

2022-08-30 09:34 UTC, KangYunHo1221 commented on frontend/types/api.ts
> +};
그러네요 interface로도 되겠군요
저는 User 를 정의해놓고 id만 제거해서 쓰는 현재 방식도 좋은 것 같습니다!

2022-08-30 09:34 UTC, KangYunHo1221 commented on frontend/src/api/applicationForms.ts
> +import * as T from "../../types/api";
a:
질문이 있는데요, 
1. 저희 타입을 쓰는 곳에서 정의하기로 하지 않았나요?? types 파일을 분리하기로 했었는지 헷갈려서 여쭙습니다 ㅠㅠ
2. 만약 분리해서 쓴다면 import * as T 의 컨벤션으로 맞춰서 사용하면 될까요?

2022-09-01 05:10 UTC, soyi47 requested changes
우디, 록바 고생하셨습니다. 깔끔하게 작업 잘 해주신 것 같아요!
소소하게 코멘트 남겼고요. 오타인 것 같은 부분이 있는데, 한번 확인 부탁 드립니다.

> type alias와 interface의 혼용보다는, type alias 단 하나로 관리를 하고 싶어 모든 타입을 type alias로 선언하였습니다.

저는 type alias만 사용했을 때도 원하는 타입 작성에 불편함이 없었어요. 그런 점에서는 제안해주신대로 type alias 하나로 관리하는 것도 괜찮을 것 같아요. 
다만 제가 모르는 부분들이 있을 것 같아서 다른 분들 의견 들어보면서 저도 조금 더 알아보겠습니다.

> 타입 네이밍 시 용어 사전 참고, types 폴더 구조
잘 작업해주신 것 같아요. 좋습니다. 👍

2022-09-01 08:36 UTC, lokba commented on frontend/types/domains/recruitments.ts
> +  poition: number;
감사합니다. 오타 맞습니다! 

![스크린샷 2022-09-01 오후 5 35 07](https://user-images.githubusercontent.com/19251499/187870272-e6036452-864c-4876-9fae-1e0531406430.png)

2022-09-01 12:42 UTC, lokba commented on frontend/types/domains/recruitments.ts
> +  endDateTime: string;
@soyi47 
소피아~ 상세하게 예시코드까지 작성해주셔서 감사합니다. 

이에 대해서 고민을 해보고 내린 저의 생각입니다. 
예시코드는 타입스크립트를 이용해서 유효성 검사까지 하는 것이라고 생각하는데요. 

저는 두 가지 정도의 이유로 반대합니다. 

- 타입스크립트의 역할
저는 타입스크립트의 역할이 유효성 검사까지라고 생각하지 않습니다. 유효성 검사는 자바스크립트를 이용해서 하는 것이 맞지 않을까 싶네요.

- 컴파일 에러의 이유를 정확히 파악하지 못한다. 
컴파일 에러가 났을 시에, 년월일에서 어떤 값으로 인해서 컴파일 에러가 떴는지 알 수 없고 에러에 대한 상세한 메세지를 처리할 수 없습니다. 

이에 대해서는 어떻게 생각하시나요? 모두의 생각이 궁금하긴 하네요. 

template literal types 관련 아티클 : https://toss.tech/article/template-literal-types
소피아 예시 코디 관련 아티클 : https://blog.logrocket.com/handing-date-strings-typescript/

2022-09-01 12:44 UTC, lokba commented on frontend/types/api.ts
> +  email: string;
좋은 피드백 감사합니다.

2022-09-01 12:45 UTC, lokba commented on frontend/types/api.ts
> +};
interface와 type alias에 대한 기준은 금주 회의때 애기해봅시다.

2022-09-01 13:43 UTC, jho2301 commented on frontend/src/api/applicationForms.ts
> +import * as T from "../../types/api";
api 스키마는 api에서 정의하는게 더 좋아보이긴하네용
관련있는 코드는 가까운 곳에 두는게 좋더라구요

2022-09-01 13:46 UTC, jho2301 commented on frontend/src/api/applicationForms.ts
> +const COMMON_PATH = "/api/application-forms";
3기의 잔재 같습니다만 ㅋㅋ 요거 그냥 하드코딩해도 되지않을까 싶어요
`${COMMON_PATH}/me` 이렇게 읽게 되는데 
`/application-forms/me` 이렇게 읽어야 맥락 이해가 더 편한 것 같네유. 상수화해서 얻을 수 있는 이득도 크진 않은것같구요

2022-09-01 13:49 UTC, jho2301 commented on frontend/src/api/recruitments.ts
> +  axios.get<T.FetchItemsResponseData>(`${COMMON_PATH}/${recruitmentId}/items`);
어떤 아이템인지 네이밍 구체화되면 좋을것같아요

2022-09-01 13:54 UTC, jho2301 commented on frontend/types/api.ts
> +export type FetchVerifyAuthenticationCodeResponseData = never;
never타입이 적절한지 궁금합니당

2022-09-01 14:00 UTC, jho2301 commented on frontend/src/api/applicationForms.ts
> +  axios.post<T.CreateFormResponseData>(COMMON_PATH, { recruitmentId }, headers({ token }));
현재는 api fetcher들이 axios응답을 단순 반환하고 있는데, 프로그램에서 사용할 수 있는 타입의 데이터로 변환하는 역할도 가져가면 어떨지 제안드려봐요! 
ex) date string -> Date

2022-09-01 14:10 UTC, jho2301 commented on frontend/types/domains/recruitments.ts
> +  endDateTime: string;
api응답데이터는 컴파일타임에 검증할 수 없어서요 록바 의견에 공감합니당

2022-09-01 14:17 UTC, jho2301 commented on frontend/types/domains/recruitments.ts
> +  endDateTime: string;
+@ 조금만 더 첨언하면 요 논의는 ts가 런타임에 역할을 할 수 있는지 이야기 되면 좋겠어용

2022-09-01 14:19 UTC, jho2301 commented on frontend/types/domains/recruitments.ts
> +  endDateTime: string;
Date로 관리되어야할것같아요~

2022-09-01 14:20 UTC, jho2301 commented on frontend/types/domains/recruitments.ts
> +  endDateTime: string;
요기도 그냥 Date로 관리하는게 어떤지 싶네요 ㅋㅋ

2022-09-01 14:22 UTC, jho2301 commented on frontend/src/api/applicationForms.ts
> +  axios.post<T.CreateFormResponseData>(COMMON_PATH, { recruitmentId }, headers({ token }));
https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/

2022-09-01 14:25 UTC, jho2301 commented on frontend/types/api.ts
> +};
과거에는 기능의 차이가 있었다지만, 요즘은 스타일의 차이가 아닌가 싶네유

2022-09-01 15:22 UTC, soyi47 commented on frontend/types/domains/recruitments.ts
> +  endDateTime: string;
@lokba 
록바~ 다시 생각해볼 부분들 제시해주셔서 감사합니다. 👍

제가 '날짜 형식은 어떻게 타이핑 할 수 있을까'에만 집중했던 것 같아요.

말씀하신 부분들을 고려한다면 아래와 같은 방식이 될 것 같습니다.
1. 해당 타입을 string 수준으로만 제한하고
2. 런타임에 유효한 날짜 형식인지, Date로 관리할 수 있는지 확인

그러면 궁금한 부분이 있는데요.

해당 타입은 domain 폴더에 정의되어 있습니다. 
**같은 domain 폴더의 User의 birthday는 type을 Date**로 주고 있고요.
그런 부분들을 고려했을 때는, 어떤 타입을 주는 게 맞다고 생각하시나요?
(저는 domain으로 분류된 타입이라면 date time에 맞게 제한하는 좋을 것 같습니다.)

아마도 기존 로직에 맞춰 타입을 주면서 User의 birthday와 타입이 달라졌을 것 같은데요.
날짜 형식의 값에 대한 상황을 한번 정리하고 가면 좋을 것 같습니다. 👍

2022-09-01 18:38 UTC, hwangstar156 commented on frontend/src/api/applicationForms.ts
> +import * as T from "../../types/api";
저는 공용적으로 사용되는 타입의 경우 전역의 types 폴더를 나눠서 관리하고 특정 폴더내에서만 사용될 타입이면 그 폴더내에 선언하긴합니다. 이거에 대해서도 같이 논의해보면 좋을것 같습니다!

2022-09-01 18:46 UTC, hwangstar156 commented on frontend/types/api.ts
> +export type FetchVerifyAuthenticationCodeResponseData = never;
값을 반환하지 않는다면 never보다는 void가 맞다는 생각이 드네요.

2022-09-02 07:21 UTC, lokba commented on frontend/types/domains/recruitments.ts
> +  poition: number;
수정하였습니다.  7b98a6a

2022-09-02 07:22 UTC, lokba commented on frontend/src/api/recruitments.ts
> +  axios.get<T.FetchItemsResponseData>(`${COMMON_PATH}/${recruitmentId}/items`);
`fetchItems` -> `fetchRecruitmentItems` 수정하였습니다. fd85f5f

2022-09-02 07:43 UTC, woowapark commented on frontend/src/api/api.ts
> +    return Promise.resolve({ data: response.data["body"] || null });
c: 
- 오프라인에서 말했던 것처럼 응답이 없는 경우에 빈 객체를 채워줄 필요는 없을 것 같아요     
- 응답이 아예 없는 경우의 리턴 타입은 `Promise<void>`가 맞지 않을까 싶은데 어떠신가요? 🙂

2022-09-11 05:01 UTC, lokba commented on frontend/types/domains/applicationForms.ts
> +  modifiedDateTime: string;
백엔드와 확인해본 결과, 변경을 하지 않았을 경우에도 `createdDateTime`와 동일한 값이 전달되더라고요. 즉 string 타입이 옵니다!

2022-09-11 10:05 UTC, lokba commented on frontend/types/api.ts
> +  email: string;
2d869c7 수정했습니다!

2022-09-11 10:07 UTC, lokba commented on frontend/src/api/applicationForms.ts
> +import * as T from "../../types/api";
api 파일내에서 타입을 선언하는 방향으로 수정했습니다. 119a7ef

2022-09-11 10:07 UTC, lokba commented on frontend/src/api/applicationForms.ts
> +const COMMON_PATH = "/api/application-forms";
수정했습니다! dcc7e9b

2022-09-11 10:10 UTC, lokba commented on frontend/src/api/applicationForms.ts
> +  axios.post<T.CreateFormResponseData>(COMMON_PATH, { recruitmentId }, headers({ token }));
> 현재는 api fetcher들이 axios응답을 단순 반환하고 있는데, 프로그램에서 사용할 수 있는 타입의 데이터로 파싱하는 역할도 가져가면 어떨지 제안드려봐요!

동의합니다. 해당 이슈에서 data string -> Date를 변환하기에는 작업이 크다고 판단하여 따로 이슈를 생성하여 수정하도록 하겠습니다.

2022-09-11 10:11 UTC, greenblues1190 commented on frontend/src/api/api.ts
> +    return Promise.resolve({ data: response.data["body"] || null });
말씀하신대로 응답이 없는 경우 null보다 리턴을 하지않는게 적절한 것 같네요. 인터셉터에서 `response.data` 객체가 `body` 프로퍼티를 가진 경우 data를 가진 객체, 아닌 경우 `void`를 resolve했습니다.

```typescript
// lib.es2015.promise.d.ts
resolve(): Promise<void>;
resolve<T>(value: T | PromiseLike<T>): Promise<T>;
```

34840af

2022-09-11 10:12 UTC, lokba commented on frontend/types/domains/recruitments.ts
> +  endDateTime: string;
@soyi47 
날짜 관련한 의견은 해당 코멘트에 남겼습니다! https://github.com/woowacourse/service-apply/pull/612#discussion_r967798867

2022-09-11 10:14 UTC, lokba commented on frontend/types/domains/recruitments.ts
> +  endDateTime: string;
@hwangstar156 
피드백 주신 방향대로 수정하였습니다. 2d869c7 
추후에 날짜와 관련된 값(startDateTime...)들은 Date 타입으로 수정될 것으로 보입니다.

2022-09-11 10:16 UTC, lokba commented on frontend/types/api.ts
> +export type FetchVerifyAuthenticationCodeResponseData = never;
수정했습니다. 34840af

2022-09-11 11:04 UTC, KangYunHo1221 approved these changes

2022-09-11 11:04 UTC, KangYunHo1221 commented on frontend/src/api/applicationForms.ts
> +>;
수정한것 잘 봤습니다 록바!!
approve하면서 궁금한 게 하나있는데요
어떤 곳에서 에서는 recruitmentId: number 이고 어떤 곳에서 recruitmentId: string인가요??

2022-09-12 13:23 UTC, soyi47 approved these changes
록바, 우디~ 고생하셨습니다. 깔끔하게 잘 작업해주셨네요! 👍

Date 타입 관련 코멘트도 잘 확인했고요.
보다 보니 다른 이슈로 작업 진행해볼 부분이 보여서 코멘트 남겨뒀습니다.
수정 요청은 없어요.  Approve 하겠습니다~ 👍👍👍

2022-09-12 13:23 UTC, soyi47 commented on frontend/src/api/applicationForms.ts
> +export type CreateFormResponseData = ResponseDataWithMessage<ApplicationForm>;
a: 이번 PR 말고, 나중에 리팩토링하면 좋을 것 같아서 코멘트 남겨둡니다.

recruitementId를 url의 location.search에서 가져오면서 null일 수 있는 것 같은데, null인 경우에 api 요청 보내는 일을 막는 방어 코드가 없어서 `string | null` 타입이 된 것 같네요.
 잘못된 요청을 보내는 상황을 막을 수 있도록, null인 경우를 확인하고 recruitmentId의 값이 있을 때만 요청을 보내도록 확인하는 로직을 추가하면 좋을 것 같아요.

다음에 같이 논의해봐요~

2022-09-13 12:35 UTC, lokba commented on frontend/src/api/applicationForms.ts
> +>;
우선, `recruitmentId`의 타입이 number인 경우에는 responseData입니다. string인 경우에는 requestData인데요.

`recruitmentId: string`인 경우의 코드를 들이다보면 아래와 같은 코드가 있습니다.
```javascript
const { recruitmentId = null } = parseQuery(location.search);
```

recruitmentId가 없을 경우 null이 반환되고, 있을 경우 string 형식으로 주게 됩니다.

2022-09-13 12:37 UTC, lokba commented on frontend/src/api/applicationForms.ts
> +export type CreateFormResponseData = ResponseDataWithMessage<ApplicationForm>;
확인이요~!

2022-09-13 12:45 UTC, lokba commented on frontend/src/api/recruitments.ts
> +export type PostAssignmentResponseData = ResponseDataWithMessage<Assignment>;
으흠..위 코멘트와 연관있는 피드백이군요. 통일성있게 recruitmentId가 null일때 API 요청을 하지 않도록 하는 게 좋겠네요. 

```javascript
// AssignmentSubmit.js
  useEffect(() => {
    if (!recruitmentId || !currentMission) {
      navigate(PATH.RECRUITS, { replace: true });
      return;
    }
    ...
  }, []);
```

결론은 AssignmentSubmit 파일에서는 recruitmentId가 null인 경우를 처리했지만, 
ApplicationRegister 파일에서는 처리하지 않았습니다. 그 때문에 `requestType`에서 recruitmentId의 타입이 `string | null`이 되었네요.

2022-09-19 12:44 UTC, woowapark approved these changes
고생하셨습니다 👏👏👏 
- PR 코멘트에서 언급되었던 리팩토링 포인트나 사용해보면서 불편하게 느껴지는 타입들은 조금씩 고쳐나가면 될 것 같아요.
- 자동 채점 기능 PR에서 api 사용하는 부분이나 domain/ 하위의 타입들을 요 PR 머지 후에 맞춰서 수정해야 할 수 있어보이네요 🤔 @hwangstar156 @KangYunHo1221     
- 대부분 타입과 관련된 수정이기는 하지만 api 호출을 하는 모든 영역을 건드리고 있어 머지 전에 테스트를 한번 해보면 좋을 것 같은데요, 런타임에서 오류가 생기는 부분은 없는지 수정한 영역과 관련된 기능들을 한번 일괄 테스트 해주실 수 있을까요? @lokba @greenblues1190

2022-09-19 13:42 UTC, hwangstar156 approved these changes
고생하셨습니다 록바,우디!! approve 진행하겠습니다!

2022-09-20 08:28 UTC, lokba commented
@woowapark 일괄 테스트 결과 이상 없습니다.

2022-09-26 05:34 UTC, woowahan-pjs approved these changes
고생하셨습니다. 👍

2022-09-30 05:35 UTC, merged