feat(apply): change common styles for the entire page.
woowacourse/service-apply pull request #645
Opened 2022-09-25 15:49 UTC by soyi47

Resolves #629 

# 해결하려는 문제가 무엇인가요?

- 메인 페이지와 다른 페이지의 공통 스타일을 맞춘다.

# 어떻게 해결했나요?

### Container의 border 제거
- 적용 대상: 전체 페이지

### Container의 title 정렬 방식 변경
- Container에 `titleAlign` prop을 추가하여 해당 prop 값에 따라 `h2` 태그의 className을 다르게 주는 방식으로 구현했습니다. prop의 default 값은 'center'로 줬습니다.
- 좌측 정렬 대상 페이지: 지원서 작성 페이지, 내 지원 현황 페이지, 과제 제출 페이지, 회원가입 페이지
- 중앙 정렬 대상 페이지: 로그인 페이지, 마이 페이지, 내 정보 수정 페이지, 비밀번호 변경 페이지

# 어떤 부분에 집중하여 리뷰해야 할까요?
- 질문) 타이틀 폰트 사이즈는 피그마와 다른 상황입니다. border와 title 정렬에 대해서만 기존에 논의되어서 border와 title 정렬에 대해서만 작업했는데요. 기존 타이틀 폰트 사이즈를 유지할 것인지, 피그마에 적용된 사이즈로 변경할 것인지 논의가 필요합니다. 
- 타이틀 정렬을 적용하는 다른 방식이 있다면 제안해주세요.
- 피그마와 다른 부분이 없는지 함께 확인해주세요. 
    (참고 - 배경색 변경은 #601 이슈에서 함께 진행합니다.)

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2022-09-28 05:14 UTC, lokba requested changes
안녕하세요. 소피아!

>질문) 타이틀 폰트 사이즈는 피그마와 다른 상황입니다. border와 title 정렬에 대해서만 기존에 논의되어서 border와 title 정렬에 대해서만 작업했는데요. 기존 타이틀 폰트 사이즈를 유지할 것인지, 피그마에 적용된 사이즈로 변경할 것인지 논의가 필요합니다.

피그마에 적용된 사이즈로 가면 될 것 같습니다. 2rem으로 가니, 시원시원하니 좋더라고요. 

수정하시고 다시 request 부탁드릴게요! 🥷

2022-09-28 05:14 UTC, lokba commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.js
> +      <Container title="지원서 작성" titleAlign="left">
r : 
```jsx
Container.propTypes = {
  ...
  titleAlign: PropTypes.oneOf(["center", "start", "end"]),
  ...
};
```

소피아가 작성한 코드로 유추했을 때는, "start"가 맞겠네요.

2022-09-28 05:14 UTC, lokba commented on frontend/src/components/@common/Container/Container.js
> +  CENTER: "center",
c : 추가적으로 궁금사항입니다. 왜 `left center right`가 아닌 `start center end`로 정하셨는지 궁금합니다. 

추가적으로, Material UI에서 제공해주는 Typography 컴포넌트에서 align(props)로 올 수 있는 값은 `left center right`이긴 하네요.

[Typography 링크](https://mui.com/material-ui/api/typography/)

2022-09-28 05:14 UTC, lokba commented on frontend/src/components/@common/Container/Container.js
> +  titleAlign: "center",
c : `titleAlign`에 대해서는 defaultProps와 Object default value 두 가지 모두 사용하셨는데, 하나만 사용해도 괜찮지 않을까요?

2022-09-28 12:22 UTC, soyi47 commented on frontend/src/components/@common/Container/Container.js
> +  titleAlign: "center",
기존 작업에서 defaultProps를 사용하고 있어서, 여기서도 defaultProps를 사용하도록 수정했습니다. https://github.com/woowacourse/service-apply/pull/645/commits/368b41ac149f30fb1a631b3b516f4b95cc9a5f3e

2022-09-28 12:23 UTC, soyi47 commented on frontend/src/pages/SignUp/SignUp.js
> +    <Container title="회원가입" size={CONTAINER_SIZE.NARROW} titleAlign="left">
수정 완료~ https://github.com/woowacourse/service-apply/pull/645/commits/a6d50d2c688316b7e9ab393902a4f789f733b390

2022-09-28 12:24 UTC, soyi47 commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.js
> +      <Container title="지원서 작성" titleAlign="left">
오 제가 왜,,, 저렇게 적었을까요..? 찾아줘서 고마워요!

2022-09-28 12:33 UTC, soyi47 commented on frontend/src/components/@common/Container/Container.js
> +  CENTER: "center",
`left center right`로 변경했습니다.

특별한 이유는 없고 start, center, end가 편해서 습관적으로 사용하고 있었어요.
`start - end`, `left - right` 차이는 direction 속성에 따라 방향이 달라지는가에 있는데요.
1. direction이 ltr인 상황이라 구현 상 차이는 없고,
2. 좌측 정렬, 혹은 우측 정렬이라는 의미를 강조하고자 

left, right로 다시 정리해봤어요. https://github.com/woowacourse/service-apply/pull/645/commits/e85acf9e0fa8f05f25c86056441102e4ab8e0592

2022-09-29 12:41 UTC, woowapark requested changes
r: https://github.com/woowacourse/service-apply/pull/646#pullrequestreview-1125049275 요 PR에서와 마찬가지로 타이틀 상하 여백이 피그마랑 좀 다르지 않나 싶은데 맞을까요..?      
한번 확인 부탁드려요! + 코드 라인 코멘트 하나만 남겨두었습니당

2022-10-02 05:34 UTC, soyi47 commented on frontend/src/components/@common/Container/Container.js
> +const Container = ({ title, titleAlign, size, children, className, ...props }) => {
1. 좋습니다~ TITLE_ALIGN 상수화했습니다. https://github.com/woowacourse/service-apply/pull/645/commits/87df2bb04385109a9da9532b195a3bec3c15040e

2. 여백 관련해서 추가 반영했습니다. https://github.com/woowacourse/service-apply/pull/645/commits/87df2bb04385109a9da9532b195a3bec3c15040e
사실 여백 관련해서는 논의된 부분이 없었는데요. 피그마의 마이 페이지, 내 정보 수정, 비밀번호 수정의 경우 Container padding이나 타이틀 상하단 여백이 정리가 덜 되어 있어서 타이틀 아래 3rem(48px)로 margin 주도록 작업했습니다. 피그마에도 반영해뒀습니다. 외에 다른 페이지들은 Container padding 상하 2rem(32px), 1.25rem(20px)로 정리했습니다.

2022-10-03 17:56 UTC, lokba requested changes
코멘트 한번 확인 부탁드립니다.

2022-10-03 17:56 UTC, lokba commented on frontend/src/components/@common/Container/Container.js
> +  CENTER: "center",
c : 음...체리픽 과정을 거쳐서 그런지 해당 커밋 내역을 확인할 수 없네요. 한번 새로 갱신 부탁드려요.

2022-10-03 17:56 UTC, lokba commented on frontend/src/pages/MyApplication/MyApplication.js
> +import { fetchMyApplicationForms } from "../../api/application-forms";
r : 
```suggestion
import { fetchMyApplicationForms } from "../../api/applicationForms";
```

소피아가 직접 수정하신 건가요? 아마 #612 번이 머지된 후에 최신 상태로 업데이트를 안하신 것 같네요.

2022-10-03 17:56 UTC, lokba commented on frontend/src/pages/MyPage/MyPage.module.css
> +  margin: 3.5rem 0 0;
r : 
```suggestion
  margin-top: 3.5rem;
```

2022-10-04 17:12 UTC, soyi47 commented on frontend/src/pages/MyPage/MyPage.module.css
> +  margin: 3.5rem 0 0;
반영 완료! https://github.com/woowacourse/service-apply/pull/645/commits/d066a0f585cb5227aad1f1f92beb6eba2a746472

2022-10-04 17:13 UTC, soyi47 commented on frontend/src/pages/MyApplication/MyApplication.js
> +import { fetchMyApplicationForms } from "../../api/application-forms";
최신 develop 가져오면서 conflict 정리를 잘못했던 것 같아요. 수정했습니다. 찾아줘서 고마워요! https://github.com/woowacourse/service-apply/pull/645/commits/d066a0f585cb5227aad1f1f92beb6eba2a746472

2022-10-05 10:30 UTC, soyi47 commented on frontend/src/components/@common/Container/Container.js
> +  CENTER: "center",
오프라인으로 커밋 확인했습니다.

2022-10-05 11:25 UTC, greenblues1190 approved these changes
고생하셨습니다 👍

2022-10-05 13:32 UTC, lokba approved these changes
수정사항 확인했습니다. 고생하셨어요 👍

2022-10-05 13:54 UTC, woowapark requested changes
수정사항 확인하였습니다~    
스타일 중복인 부분 하나만 소소하게 추가로 확인 부탁드려요 🙂      
실행해서 Figma와도 한번 다시 확인해보았는데 간격이나 크기에서 조금씩 궁금한 부분이 있어, 내일 오프라인으로 잠시 여쭤보겠습니다 🙏

2022-10-05 13:54 UTC, woowapark commented on frontend/src/components/@common/Container/Container.js
> +  titleAlign: "center",
a: https://github.com/woowacourse/service-apply/pull/644 에서 defaultProps를 일괄 제거한 것으로 알고 있어요.  
기존 코드와의 스타일 정리도 해당 PR에서 될 예정이니 현재 PR에서 추가로 수정할 필요는 없을 것 같습니다.
@lokba 이 PR을 먼저 머지하게 될 것 같은데, 컨플릭트 나는 부분 없을지 머지 후에 한번 확인 부탁드릴게요! 🙏

2022-10-05 13:54 UTC, woowapark commented on frontend/src/components/@common/Container/Container.module.css
>    background-color: var(--white);
r: 소피아 수정사항은 아니긴 하지만...`background`와 `background-color` 스타일 규칙이 중복인 것 같습니다 🙂 발견한 김에 수정하면 어떨까요~

2022-10-05 14:09 UTC, lokba commented
> 이 PR을 먼저 머지하게 될 것 같은데, 컨플릭트 나는 부분 없을지 머지 후에 한번 확인 부탁드릴게요! 🙏
@woowapark 넵 알겠습니다. 완벽하게 처리하겠습니다. :)

2022-10-06 08:48 UTC, soyi47 commented on frontend/src/components/@common/Container/Container.js
> +  titleAlign: "center",
어느 PR이 먼저 머지될지 몰라서 우선 넣어뒀어요.
록바가 먼저 머지된다면 이후에 다시 확인하겠습니다.

2022-10-06 08:52 UTC, soyi47 commented on frontend/src/components/@common/Container/Container.module.css
>    background-color: var(--white);
그러네요~ 수정했습니다! https://github.com/woowacourse/service-apply/pull/645/commits/280e020096c1e362d4135a8bb81dc1391958d1c2

2022-10-07 09:15 UTC, woowapark approved these changes
고생하셨습니다~👏👏👏👏👏

2022-10-08 08:30 UTC, woowahan-pjs approved these changes
고생하셨습니다. 👍

2022-10-08 08:31 UTC, merged