feat: update assignment note length
woowacourse/service-apply pull request #647
Opened 2022-09-26 03:57 UTC by soyi47

Resolves: #615

플래닝포커 : 1(2시간) <-> 걸린 시간 (2시간)

# 해결하려는 문제가 무엇인가요?
- 과제 진행 소감의 최대 글자 수를 늘린다.

# 어떻게 해결했나요?
- 과제 진행 소감의 최대 글자 수를 1,000자에서 5,000자로 변경했습니다.
- 과제 진행 소감은 현재 입력 중인 글자 수 노출되지 않도록 수정했습니다. 지원서의 경우 입력 중인 글자 수가 보여야 합니다. MessageTextArea에 showValueLength prop을 추가하여 해당 prop이 true일 때 입력 중인 글자 수가 보이도록 했습니다. 
- 최대 글자 수 이상으로 붙여 넣는 경우, 잘려서 입력되는 기능은 이미 구현되어 있어서 따로 추가 작업은 없었습니다.

# 어떤 부분에 집중하여 리뷰해야 할까요?
- 놓친 설정이 있다면 지적해주세요.

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2022-09-28 07:04 UTC, lokba requested changes
소피아+케이~ 협업 진행하시느라 수고 많으셨습니다. 

#### 클라이언트

![스크린샷 2022-09-28 오후 3 59 33](https://user-images.githubusercontent.com/19251499/192710070-8ab6ea87-5d12-4316-8c7e-c97bb32dcfc1.png)

- 해당 PR에서는 경고창 문구에 대한 작업은 벗어나는 것으로 판단하셔서 작업 안하신 걸까요? 

#### API

![스크린샷 2022-09-28 오후 3 59 20](https://user-images.githubusercontent.com/19251499/192710022-1c951918-4ec1-4797-9721-be004561a5a0.png)

- error message가 수정이 되지 않은 것 같은데, 한번 확인 부탁드립니다.

2022-09-28 07:36 UTC, lokba commented on frontend/src/constants/form.ts
> +  NOTE_MAX_LENGTH: 5000,
a : `NOTE`라는 단어를 처음 봤네요. 혹시 모르는 분이 계실까봐 공유해드립니다.

`NOTE`라는 용어는 현재 Assignment와 관련된 폴더에서만 사용되며, `과제 진행 소감`을 의미하는 것으로 추정됩니다.

2022-09-28 12:35 UTC, soyi47 commented on frontend/src/constants/form.ts
> +  NOTE_MAX_LENGTH: 5000,
저도 작업하면서 같은 의미로 파악했어요. 👍

2022-09-28 14:12 UTC, soyi47 commented on frontend/src/components/@common/MessageTextarea/MessageTextarea.js
> +  showValueLength,
여기 네이밍에 대해서는 저도 아쉬움이 있습니다. 😥
우선 'value의 length를 보여준다'는 내용이 이름에서 그대로 드러나는 게 명확하다고 생각해서 `showValueLength`라고 네이밍 했었고요.

1. 록바 의견을 고려하면 저는 `showCount` 정도가 괜찮다는 생각이고,
2. 'show'라는 동사 표현이 들어가는 게 맞을까? 괜찮은걸까,,, 하는 고민도 있습니다.

prop 네이밍은 @greenblues1190 @woowapark 의견까지 들어보고 반영해볼게요!

2022-09-29 02:34 UTC, SuyeonChoi requested changes
안녕하세요 소피아, 케이!
처음에 소피아가 모두 작업하신 줄 알고 놀랐는데 케이랑 함께 하신 결과물이였군요!
두 분 모두 수고하셨습니다👏👏
소소한 리뷰 남기고 갑니다!🐾

2022-09-29 02:34 UTC, SuyeonChoi commented on src/main/kotlin/apply/domain/assignment/Assignment.kt
> +    @Column(length = 5000)
```suggestion
    @Column(nullable = false, length = 5000)
```
r: 코틀린의 타입도 non-nullable이고, sql문에서도 `not null`이 있으니 설정을 추가하는게 좋겠습니다!😊

2022-09-29 02:34 UTC, SuyeonChoi commented on src/main/kotlin/apply/config/DatabaseInitializer.kt
> +                maximumLength = 5000,
a: config의 파일도 꼼꼼하게 처리해주셨네요!👍

2022-09-29 02:53 UTC, SuyeonChoi commented on src/main/resources/db/migration/V3_3__Assignment_note_longer.sql
> +    modify note varchar(5000) not null;
r: `#588` PR에 이미 V3_3을 이미 사용중이라 다른 버전으로 사용하는게 좋을거 같아요!🤓🤓

2022-09-29 04:30 UTC, kth990303 commented on src/main/kotlin/apply/domain/assignment/Assignment.kt
> +    @Column(length = 5000)
예리한 지적 감사합니다.
note는 빈칸이어도 제출을 할 수 있어야 되는 것 같더라고요. sql문에 `not null`을 제거했습니다.

2022-09-29 04:31 UTC, kth990303 commented on src/main/resources/db/migration/V3_3__Assignment_note_longer.sql
> +    modify note varchar(5000) not null;
아니 이게 있을줄 몰랐네요 ㅋㅋ
`V3_4`로 수정하였습니다

2022-10-01 06:56 UTC, soyi47 commented
@lokba @woowapark 
록바가 피드백 주신 에러 메시지 관련 피드백은 아래 길이 제한 동작 테스트와 함께 재확인했습니다.

#### 과제 소감 길이 제한 동작 테스트
- [x] 과제 소감 TextArea에 직접 입력했을 때 최대 글자 수로 잘려서 입력되는가?
- [x] 과제 소감 TextArea에 복사 붙여넣기 했을 때 최대 글자 수로 잘려서 입력되는가?
- [x] 어떤 이유로 과제 제출 요청이 갔을 때, 제출할 수 없도록 처리되어 있는가?
     (길이 제한을 없애고 제출 요청하여 테스트 진행)
    ![image](https://user-images.githubusercontent.com/71116429/193396601-cc8b1695-cde2-4109-83b9-bc8b4bca2cfc.png)

2022-10-01 06:56 UTC, soyi47 commented
#### 과제 소감 길이 제한 동작 테스트
- [x] 과제 소감 TextArea에 직접 입력했을 때 최대 글자 수로 잘려서 입력되는가?
- [x] 과제 소감 TextArea에 복사 붙여넣기 했을 때 최대 글자 수로 잘려서 입력되는가?
- [x] 어떤 이유로 과제 제출 요청이 갔을 때, 제출할 수 없도록 처리되어 있는가?
     (길이 제한을 없애고 제출 요청하여 테스트 진행)
    ![image](https://user-images.githubusercontent.com/71116429/193396601-cc8b1695-cde2-4109-83b9-bc8b4bca2cfc.png)

2022-10-01 07:09 UTC, soyi47 commented on frontend/src/components/@common/Textarea/Textarea.js
>      onChange(event);
@woowapark @lokba @greenblues1190 
최대 글자 수 초과 입력 후 과제 제출 시 n자 이상 입력 불가능하다는 alert를 띄우기로 한 것으로 알고 있습니다.
그런데 이미 최대 글자 수로 입력이 제한되도록 구현된 상태이기 때문에, '제출 시'에 글자 수에 대한 alert를 띄우는 일은 불필요한 상황으로 보입니다.

따라서 최대 글자 수 이상의 입력을 제한함과 동시에 '최대 n자까지 입력 가능합니다.'라는 안내 문구를 띄우도록 해봤습니다. (안내 없이 입력을 제한해버리니 좀 어색하게 느껴지더라고요.)

해당 안내 문구는 인자로 maxLength를 받아 문자열을 반환하도록 만들었고, 그러다보니 다른 constants와 다른 형태여서 우선 constants 하위가 아닌 Textarea에 작성해두었는데요.
이 부분 괜찮은지, 혹은 contants 하위로 옮기는 게 좋을지 다른 분들 의견 궁금합니다.

2022-10-02 10:11 UTC, greenblues1190 reviewed
안녕하세요 소피아! 꼼꼼하게 정리해주셨군요.
공유해주신 부분에 대해서 의견남겼습니다.

a: 혹시 시간 남으시면 `Textarea`와 `MessageTextarea` 타입스크립트 전환, 아니면 스토리북 코드도 한번 만져주시면 좋을 것 같아요. 스토리북 코드에 onChange 바인딩이 없어서 에러가 발생하네요. 확인해보니 이번 PR이전부터 존재하는 문제입니다.

2022-10-02 10:11 UTC, greenblues1190 commented on frontend/src/components/@common/Textarea/Textarea.js
>      onChange(event);
a: 저는 alert가 없을 때 어색하게 느껴지지는 않네요. 

> 이 부분 괜찮은지, 혹은 contants 하위로 옮기는 게 좋을지 다른 분들 의견 궁금합니다.

템플릿 함수여도 constants로 옮기는게 맞을 것 같아요.

2022-10-02 11:12 UTC, cjlee38 requested changes
안녕하세요 소피아 & 케이 ~ 프론트를 잘 모르다보니 백엔드만 리뷰했습니다.

바뀐 내용이 많지 않아 트집 잡을거 없나 한참을 찾아보다 겨우 하나 찾았네요 ㅋㅋ 확인하시고 적절히 수정 부탁드리겠습니다~

2022-10-02 11:12 UTC, cjlee38 commented on src/main/kotlin/apply/application/AssignmentDtos.kt
>      @field:NotBlank
r: note가 빈칸이어도 된다면 `@field:NotBlank` 와는 상충되지 않을까요 ? 이 부분 다시 한번 확인해서 통일해주세요 ~

2022-10-03 18:20 UTC, lokba requested changes

2022-10-03 18:20 UTC, lokba commented on frontend/src/components/@common/Textarea/Textarea.js
>      onChange(event);
> 최대 글자 수 초과 입력 후 과제 제출 시 n자 이상 입력 불가능하다는 alert를 띄우기로 한 것으로 알고 있습니다.

저는 잘 기억이 안나네요. 화요일 회의때 애기해봐요!! `MAX_LENGTH_VALIDATION_MESSAGE`의 위치는 우디 생각과 같습니다.

2022-10-03 18:20 UTC, lokba commented on frontend/src/components/@common/MessageTextarea/MessageTextarea.js
> +  showValueLength,
```tsx
// components/form/BirthField.js
<DatePicker
  ...
  showYearDropdown
  showMonthDropdown
  ...
/>
```

DatePicker 컴포넌트로 보았을 때, `showCount`가 괜찮아 보이네요.

2022-10-04 02:46 UTC, kth990303 commented on src/main/kotlin/apply/application/AssignmentDtos.kt
>      @field:NotBlank
예리한 지적 감사합니다 👍 한번 제이슨과 얘기해볼게요

2022-10-05 10:51 UTC, soyi47 commented on frontend/src/components/@common/MessageTextarea/MessageTextarea.js
> +  showValueLength,
`showCount`로 수정했습니다. https://github.com/woowacourse/service-apply/pull/647/commits/95eec36b3d7a0f59e55965bcc05d9a67397ec236

2022-10-05 10:55 UTC, soyi47 commented on frontend/src/components/@common/Textarea/Textarea.js
>      onChange(event);
alert로 최대 글자 수 필요한지 @woowapark 공원 확인 받은 후 constants로 옮기겠습니다.

2022-10-05 13:33 UTC, woowapark requested changes
alert 띄우는 시점에 대해서만 한번 다시 의견 부탁드려요! 🙂

2022-10-05 13:33 UTC, woowapark commented on frontend/src/components/@common/MessageTextarea/MessageTextarea.js
> +        {showCount && maxLength && maxLength > 0 && (
c: 의미들이 워낙 분명하고 짧아서 이해하는데 어려움은 없지만, 그래도 여러 조건이 중첩해서 있는 경우에는 좀 더 명확한 의미 부여와 가독성을 위해 위해 별도의 변수 등으로 조건을 한번 따로 이름지어주어도 좋을 것 같아요. 단순 의견이라 comment로만 남깁니다 :) 
```js 
// 예를 들면..? 
const shouldShowCount = showCount && maxLength && maxLength > 0;
```

2022-10-05 13:33 UTC, woowapark commented on frontend/src/components/@common/Textarea/Textarea.js
>      onChange(event);
r: 
- 최대 글자 수가 보이는 상황이라면 alert이 아예 없어도 어색하지 않을 것 같고, 보이지 않는 상황이라면 alert으로 한번 알려주면 좋을 것 같네요 🙂 현재 상황에서는 보여주는 쪽으로 통일해서 맞추는 지금 방식대로도 크게 이견 없습니다. 
- 다만 체감하기에는 비슷하더라도 alert을 먼저 띄우고 -> 글자수를 자르는 게 흐름상 좀 더 자연스럽게 느껴지는데 어떠신가요? 🤔

2022-10-07 06:32 UTC, soyi47 commented on frontend/src/components/@common/Textarea/Textarea.js
>      onChange(event);
@woowapark 
작성한 글자 수 그대로 보여주고 -> alert 띄우고 -> 글자 수 잘라서 보여주기
이렇게 맞을까요?

2022-10-08 07:41 UTC, soyi47 commented on frontend/src/components/@common/MessageTextarea/MessageTextarea.js
> +        {showCount && maxLength && maxLength > 0 && (
조건을 변수로 분리해봤습니다~ https://github.com/woowacourse/service-apply/pull/647/commits/c9edc3c6782fb5a55b2a29e79d2535efb65911cf

2022-10-08 08:30 UTC, summerlunaa approved these changes
5000자로 늘리고 빈칸을 받지 않기로 변경한 부분 확인했습니다! 
프론트와 함께하는 PR은 또 색다르네요 ㅎㅎ 소피아 케이 둘 다 수고하셨습니다💙

2022-10-08 08:30 UTC, summerlunaa commented on src/main/kotlin/apply/domain/assignment/Assignment.kt
> +    @Column(nullable = false, length = 5000)
a: `nullable = false` 👍

2022-10-08 08:30 UTC, summerlunaa commented on src/main/kotlin/apply/application/AssignmentDtos.kt
>      @field:NotBlank
a: 빈칸을 허용하지 않는 것으로 통일되었군요! 좋습니다.

2022-10-08 16:02 UTC, woowapark approved these changes
고생하셨습니다~👏👏👏👏👏

2022-10-09 02:50 UTC, woowahan-pjs commented on src/main/kotlin/apply/config/DatabaseInitializer.kt
> +                maximumLength = 5000,
자세히 보니 바꿀 필요가 없는데 한 번에 다 바꾸려다가 실수로 바꾼 거 같아요!

2022-10-09 02:53 UTC, kth990303 commented on src/main/kotlin/apply/config/DatabaseInitializer.kt
> +                maximumLength = 5000,
더미데이터는 1000으로 유지하는 방향으로 낮에 수정하겠습니다~!

2022-10-09 04:44 UTC, kth990303 commented on src/main/kotlin/apply/config/DatabaseInitializer.kt
> +                maximumLength = 5000,
@woowahan-pjs 반영했습니다 확인부탁드려요!

2022-10-09 08:12 UTC, cjlee38 approved these changes
수고하셨습니다 ! 👍

2022-10-10 03:02 UTC, lokba approved these changes
수고하셨습니다. 특이사항 없네요.
Approve 진행하겠습니다. 👏

2022-10-10 03:25 UTC, SuyeonChoi approved these changes
리뷰 반영하시느라 모두 수고하셨습니다👏👏

2022-10-10 03:32 UTC, greenblues1190 reviewed
수고하셨습니다 :DD

2022-10-10 03:32 UTC, greenblues1190 approved these changes

2022-10-10 09:35 UTC, woowahan-pjs approved these changes
고생하셨습니다. 👍

2022-10-10 10:24 UTC, merged