feat: implement administrators 'update'
woowacourse/service-apply pull request #653
Opened 2022-10-06 13:26 UTC by kth990303

Resolves: #604 

플래닝포커 : 2(4시간) <-> 걸린 시간 (4시간)

# 해결하려는 문제가 무엇인가요?
- 관리자를 한 번 저장하면 그 이후로 관리자명이나 관리자 비밀번호를 수정할 수 없었습니다.

# 어떻게 해결했나요?
- 관리자명과 비밀번호를 수정할 수 있는 API를 구현했습니다.
- 관리자를 생성 및 수정하면 반영된 해당 계정으로 로그인할 수 있도록 수정했습니다.

# 어떤 부분에 집중하여 리뷰해야 할까요?
- 메서드명, 변수명 등 네이밍이 기존 컨벤션과 부합하지 않는 부분이 있다면 지적해주세요.
- 놓친 테스트, 설정이 있다면 지적해주세요.
- 현재 바딘으로 구현된 `관리자명`, `관리자 사용자명`을 한글로 입력할 경우, 다음 입력폼에 의도치 않게 현재 입력폼에 입력한 마지막 글자가  바로 들어가는 듯합니다. 바딘 쪽 코드에 혹시 문제가 있는지 확인부탁드립니다.

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2022-10-07 03:12 UTC, woowahan-pjs requested changes
고생하셨습니다. 👍 
기존 코드를 보고 분석하는 연습을 많이 하시면 앞으로 많은 도움이 될 거예요.

2022-10-07 03:12 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/AdministratorService.kt
> +
c: 불필요한 공백으로 보여요.

2022-10-07 03:12 UTC, woowahan-pjs commented on src/main/kotlin/apply/ui/admin/administrator/AdministratorCreateForm.kt
> +class AdministratorCreateForm :
r: 생성과 수정을 분리할 이유가 없다고 봅니다. 기존 코드를 참고하고 사용자명과 같은 변경할 수 없는 부분을 읽기 전용으로 변경하면 어떨까요?

2022-10-07 03:12 UTC, woowahan-pjs commented on src/main/kotlin/apply/ui/admin/administrator/AdministratorsView.kt
> +        return HorizontalLayout(H1("관리자 계정 관리")).apply {
r: 그때 결정했던 것들이 반영되지 않았네요.

2022-10-07 03:12 UTC, woowahan-pjs commented on src/main/kotlin/apply/ui/admin/administrator/AdministratorsView.kt
> +            addSortableColumn("관리자 ID", AdministratorResponse::username)
r: 그때 결정했던 것들이 반영되지 않았네요.

2022-10-07 03:12 UTC, woowahan-pjs commented on src/test/kotlin/apply/AdministratorFixtures.kt
> +    confirmPassword: String = "abcd12345"
c: 기존 코드를 많이 보고 분석해 보시기 바랍니다.

```suggestion
    name: String = ADMINISTRATOR_NAME,
    password: String = ADMINISTRATOR_PASSWORD,
    confirmPassword: String = ADMINISTRATOR_PASSWORD
```

2022-10-07 03:12 UTC, woowahan-pjs commented on src/test/kotlin/apply/domain/administrator/AdministratorTest.kt
> +        }
r: 범위 지정 함수를 꼭 사용해야 할까요?

```suggestion
        val administrator = createAdministrator("케이", "kth990303", "1234")
        administrator.update(name = "케이케이", password = "12345")
```

2022-10-07 03:12 UTC, woowahan-pjs commented on src/test/kotlin/apply/domain/administrator/AdministratorTest.kt
> +            administrator.username shouldBe "kth990303"
c: 이 단언문은 어떤 의미를 지니나요?

2022-10-09 04:49 UTC, kth990303 commented on src/test/kotlin/apply/AdministratorFixtures.kt
> +    confirmPassword: String = "abcd12345"
update fixture 부분도 `ADMINISTRATOR_NAME`, `ADMINISTRATOR_PASSWORD`로 할 경우, 테스트 코드를 작성할 때 정말 변경이 제대로 된 것인지 확인하기 어렵다고 생각됩니다. (변경 전과 변경 후가 동일한 값으로 지정되어 항상 테스트가 통과할 것 같다는 생각입니다.) 이런 이유로 위와 같이 작성했는데 제이슨 생각은 어떤가요?

2022-10-09 04:56 UTC, kth990303 commented on src/test/kotlin/apply/domain/administrator/AdministratorTest.kt
> +        }
코멘트대로 변경했습니다!
다만 궁금한 점이, 어떠한 때에 scope function을 사용하고 어떠한 때에 사용하지 않는지 잘 모르겠습니다.

`ApplicationFormTest`에서 `지원서를 수정한다`의 테스트 코드는 scope function을 사용하지 않아도 됨에도 불구하고 scope function을 사용하여 update를 한 후에 assertSoftly로 테스트가 진행됐으며, `포트폴리오 없이 지원서를 수정한다`의 테스트 코드는 제이슨이 코멘트 남겨주신대로 scope function을 사용하지 않고 테스트가 진행됐더라구요.
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/57135043/194738781-db2762df-dd5c-483b-b97d-08a0506536df.png">

혹시 test code에서 scope function을 사용하는 기준이 따로 있는지 궁금합니다!

2022-10-09 04:57 UTC, kth990303 commented on src/test/kotlin/apply/domain/administrator/AdministratorTest.kt
> +            administrator.username shouldBe "kth990303"
값이 제대로 변경됐는지 체크하기 위해 추가해보았습니다!

2022-10-09 05:02 UTC, kth990303 commented on src/main/kotlin/apply/ui/admin/administrator/AdministratorsView.kt
> +        return HorizontalLayout(H1("관리자 계정 관리")).apply {
`관리자 계정`으로 수정하겠습니다

2022-10-09 05:03 UTC, kth990303 commented on src/main/kotlin/apply/ui/admin/administrator/AdministratorsView.kt
> +            addSortableColumn("관리자 ID", AdministratorResponse::username)
`관리자 사용자명`으로 수정하겠습니다 ㅜㅜ

2022-10-09 07:11 UTC, kth990303 commented on src/main/kotlin/apply/ui/admin/administrator/AdministratorCreateForm.kt
> +class AdministratorCreateForm :
동의합니다. 수정했습니다~

2022-10-09 08:03 UTC, kth990303 commented on src/test/kotlin/apply/AdministratorFixtures.kt
> +    confirmPassword: String = "abcd12345"
다른 방법으로 수정해봤는데 확인 부탁드립니다!

2022-10-10 12:51 UTC, kbsat requested changes
고생하셨습니다 케이😀
전반적으로 잘 짜주셔서 남길 말이 크게는 없네요~
save 내 로직이 수정된 것 같은데 update에 대한 테스트도 진행해주면 좋을 것 같아요~!

2022-10-10 12:51 UTC, kbsat commented on src/test/kotlin/apply/application/AdministratorServiceTest.kt
> +                }
a : `exactly = 1` 을 넣으신 이유가 있을까요?

2022-10-10 12:51 UTC, kbsat commented on src/test/kotlin/apply/application/AdministratorServiceTest.kt
> +
r: requestId = 0 일 때의 save 테스트(update가 되는 경우)를 추가해주세요! 😊

2022-10-10 13:26 UTC, kth990303 commented on src/main/kotlin/apply/domain/administrator/Administrator.kt
> +    var name: String,
관리자 이름: `name`, 관리자 id(사용자명): `username`인데 이름짓기가 어렵더라고요.
id로 하기엔 primary key의 id 느낌이 강해서 고민 끝에 위와 같이 결정했습니다 😭

2022-10-10 13:27 UTC, kth990303 commented on src/test/kotlin/apply/application/AdministratorServiceTest.kt
> +
추가했습니다

2022-10-11 04:04 UTC, kbsat approved these changes
테스트 코드 추가된 것 확인했습니다~! 💯
저는 이만 Approve 해도 될 것 같네요 👍

2022-10-11 14:11 UTC, woowahan-pjs approved these changes
고생하셨습니다. 👍

2022-10-11 14:13 UTC, merged