feat(judgment): implement the function to apply and retrieve judgment results
woowacourse/service-apply pull request #657
Opened 2022-10-10 14:02 UTC by summerlunaa

Resolves #637, resolves #638 

# 해결하려는 문제가 무엇인가요?

1. (관리자) 전체 채점 기능 추가
2. (관리자) 자동 채점 단건 결과 조회 기능
3. (지원자) 자동 채점 단건 결과 조회 기능 추가
4. 본 자동 채점 결과를 평가에 반영 추가
5. '내 과제 조회'시 응답에 자동 채점 결과를 추가.
6. Github API 요청 예외 발생 시 예외 메세지가 그대로 전달되는 문제.

# 어떻게 해결했나요?

1. (관리자) 전체 채점 기능
   - 반복문을 통해 모든 과제 제출물에 대한 자동 채점을 요청합니다.
   - 클래스를 분리하여 매 요청마다 트랜잭션을 열고 닫도록 처리하였습니다.
      - Judgment에서 발행하는`Event`를 기반으로 자동 채점 API을 요청합니다.
   - 반복문 도중 발생하는 예외로 인해 전체 채점이 중단되지 않도록 `runCatching()`을 이용하였습니다.
2. (관리자) 자동 채점 단건 결과 조회 기능
   - 평가대상자의 ID 값을 기반으로 **마지막** 채점 기록을 반환합니다.
   - 과제, 자동 채점 항목, 과제 제출물이 존재하지 않거나 자동 채점을 요청한 적이 없는 경우 `null`을 반환합니다.
3. (지원자) 자동 채점 단건 결과 조회 기능
   - 지원자 ID와 과제 ID 값을 기반으로 **마지막** 채점 기록을 반환합니다.
   - 제출한 과제 제출물이 존재하지 않거나 자동 채점을 요청한 적이 없는 경우 `null`을 반환합니다.
4. 본 자동 채점 결과를 평가에 반영
   - 본 자동 채점 결과(성공, 실패, 취소)시 평가 항목 점수에 반영합니다. (기존에는 `judgment`에 저장만 했습니다.)
   - 재채점 요청시 기존 점수를 초기화합니다.
5. '내 과제 조회'시 응답에 자동 채점 결과를 추가.
   - 기존 Mission Response DTO에 자동 채점 결과에 대한 정보를 덧붙여 반환합니다.
   - 지원자 ID와 평가 ID 값을 기반으로 **마지막** 채점 기록을 반환합니다.
   - **과제가 자동 채점의 대상이 아니라면** `runnable`을 false로 지정합니다.
   - 제출한 과제 제출물이 존재하지 않거나 자동 채점을 요청한 적이 없는 경우 `null`을 반환합니다.
6. Github API 요청 시 발생하는 예외 처리.
   - Github API 요청 시 4XX 혹은 5XX 응답을 받는 경우 예외가 발생하는 부분을 처리하였습니다.

# 어떤 부분에 집중하여 리뷰해야 할까요?

- 자동 채점 요청부터 채점 결과 반영까지의 흐름 상, 고려하지 못한 논리적 오류가 있는 부분이 있다면 알려주세요.
- 전체 자동 채점 요청 시, 트랜잭션과 관련하여 개선할 수 있는 방법이 있다면 알려주세요.
- 테스트 이름이 적절하지 않은 부분이 있다면 알려주세요.

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2022-10-11 15:57 UTC, ddaaac reviewed
안녕하세요~

기능이 정말 많이 추가되었네요. 채점 쪽 로직은 잘 몰라서 몇가지 스타일에 대한 코멘트와 질문 하나 남겼습니다.

확인 부탁드려요!

2022-10-11 15:57 UTC, ddaaac commented on src/main/kotlin/apply/application/JudgmentService.kt
> +            runCatching { judge(mission, assignment, JudgmentType.REAL) }
runCatching으로 예외를 삼키는 이유가 있을까요? [링크](https://medium.com/codex/effective-java-dont-ignore-exceptions-5f08a9edcc0b)

2022-10-11 15:57 UTC, ddaaac commented on src/main/kotlin/apply/application/JudgmentService.kt
> +    fun judgeAll(missionId: Long) {
제가 트랜잭션과 이벤트에 대한 이해도가 높지 않아서 이 부분에 대해서 질문이 하고 싶어요.
[이 글](https://sabarada.tistory.com/188)을 보면 트랜잭션 없이는 이벤트가 발생하지 않는다고 하는데, 이 메서드에서는 정상적으로 발생하는지 궁금합니다. (아니면 이벤트를 발생시키지 않는 게 의도인가요?)
또, 이를 확인할 수 있는 테스트가 있으면 좋을 것 같아요. 현재는 mocking된 서비스 테스트만 있어서 잘 작동하는지 한 눈에 확인할 방법이 없네요 :)

2022-10-11 15:57 UTC, ddaaac commented on src/main/kotlin/apply/application/JudgmentService.kt
> +        return judgment?.let { LastJudgmentResponse(assignment.pullRequestUrl, judgment.lastRecord) }
```suggestion
        return judgment?.let { LastJudgmentResponse(assignment.pullRequestUrl, it.lastRecord) }
```

개인적으로는 if 문을 활용하는 게 더 보기 좋다고 생각하긴 하는데, 여기 코드 스타일이 있을테니 팀원분들과 잘 논의해서 정하시면 될 것 같습니다!

2022-10-11 15:57 UTC, ddaaac commented on src/main/kotlin/apply/ui/api/MissionRestController.kt
> +        val judgmentResponses = missionResponses.associateBy({ it }, { judgmentService.findExample(user.id, it.id) })
```suggestion
        val judgmentResponses = missionResponses.associateWith { judgmentService.findExample(user.id, it.id) }
```

2022-10-11 23:23 UTC, cjlee38 commented on src/main/kotlin/apply/application/JudgmentService.kt
> +            runCatching { judge(mission, assignment, JudgmentType.REAL) }
우선 전체 채점 로직은 배포 이후 리팩토링이 예정되어 있다는 점 양지바랍니다! 

전체 채점을 실행하면 모든 지원자의 과제 제출물을 하나씩 채점 요청을 전송하게 되는데요. 중간에 불가피한 예외가 발생해서 (e.g. 깃허브에서 API가 실패하는 경우) 모든 지원자의 채점에 대해 롤백되는 경우를 방지하기 위함입니다.

2022-10-11 23:26 UTC, cjlee38 commented on src/main/kotlin/apply/application/JudgmentService.kt
> +    fun judgeAll(missionId: Long) {
`트랜잭션 없이는 이벤트가 발생하지 않는 것` 은 맞습니다. `judgeAll` 메소드에서는 트랜잭션을 걸어주지 않고 있구요. 하지만 `judgmentRepository#save` 메소드 호출시 트랜잭션을 얻고, 저장 로직을 수행한 뒤 트랜잭션이 종료되기 때문에 이 때 이벤트가 발생하게 됩니다.

`judgeAll` 에서 트랜잭션을 걸게 될 경우 모든 지원자를 채점하는 동안 트랜잭션을 계속 물고 있기 때문에 해당 케이스를 피하고자 이와 같은 구성이 나왔습니다 ㅎㅎ;

2022-10-11 23:27 UTC, cjlee38 commented on src/main/kotlin/apply/application/JudgmentService.kt
> +        return judgment?.let { LastJudgmentResponse(assignment.pullRequestUrl, judgment.lastRecord) }
☺️ 논의 후 반영하겠습니다 ~

2022-10-11 23:27 UTC, cjlee38 commented on src/main/kotlin/apply/ui/api/MissionRestController.kt
> +        val judgmentResponses = missionResponses.associateBy({ it }, { judgmentService.findExample(user.id, it.id) })
👍👍👍 감사합니다!

2022-10-12 02:20 UTC, woowahan-neo requested changes
고생 많으셨습니다!

2022-10-12 02:20 UTC, woowahan-neo commented on src/main/kotlin/apply/application/JudgmentService.kt
> +    fun judgeAll(missionId: Long) {
r: 한 미션에 채점해야 할 제출물이 3000개가 있다고 가정하면 얼마나 걸릴지 예상해보면 좋을 것 같아요.
대략 한 요청이 `100ms` 걸린다고 가정하면 `5분`이 걸릴 것 같은데요.
5분 동안 클라이언트가 대기하지 않고 커넥션을 끊는다면 처음부터 다시 동작하는 문제가 생길 것 같습니다.
추후 리팩토링 하더라도 최소한 `@Async` 키워드로 비동기 메서드 처리는 해줘야 할 것 같네요!

2022-10-12 03:01 UTC, summerlunaa commented on src/main/kotlin/apply/application/JudgmentService.kt
> +        return judgment?.let { LastJudgmentResponse(assignment.pullRequestUrl, judgment.lastRecord) }
it으로 수정했습니다. 감사합니다!

2022-10-12 03:49 UTC, cjlee38 commented on src/main/kotlin/apply/application/JudgmentService.kt
> +    fun judgeAll(missionId: Long) {
그렇네요. 비동기 처리 후 `@TransactionalEventListener`가 동작하는것까지 확인했습니다.

2022-10-13 13:10 UTC, MyaGya approved these changes
고생 많으셨습니다! RCA 룰이 저희때도 있었는지가 가물가물하긴 한데 아무튼 해당 룰대로 굳이 수정이 필요할 것 같지는 않고 확인해주셨으면 하는 부분이 있어 글 하나 남깁니다 고생 많으셨어요

2022-10-13 13:10 UTC, MyaGya commented on src/test/kotlin/apply/application/JudgmentIntegrationTest.kt
> +        When("해당 커밋의 자동 채점이 성공하면") {
다른 테스트는 when(~를 실행하면) then(그에 따른 결과(저장 성공 실패 등)) 으로 이어지는데요 여기와 219번줄은 테스트가 when 단계에서 성공했다고 가정하고 있는 것 같아요
조금 어색하게 보이는데요 "해당 커밋의 자동 채점이 실패하면" 의 경우는 고려하지 않아도 괜찮을까요?

2022-10-13 15:11 UTC, cjlee38 commented on src/test/kotlin/apply/application/JudgmentIntegrationTest.kt
> +        When("해당 커밋의 자동 채점이 성공하면") {
지원플랫폼의 자동 채점 기능은 지원 플랫폼 자체적으로 수행하지 않고, 외부 API(채점 전용 AWS Lambda) 를 활용합니다. 이 때, 중간에 AWS SQS를 두어 채점 요청 API 를 보낸 뒤 응답 값으로 채점 결과를 곧바로 수신하지 않습니다.(채점하는데 시간이 꽤 걸려서요) 즉, 채점 결과에 대해 별도 API호출을 통해 전달받는 흐름입니다. 

이미 아시겠지만, Given 절에는 '기존에 주어진 상황'을, When 절에는 '수행하고자 하는 행위'를, Then 절에는 '행위에 따른 결과 검증' 으로 이루어지는데요. 따라서 "채점이 성공했다" 라는 말을 풀어서 이야기하면 "AWS Lambda에서 채점이 성공적으로 수행되었고, 이에 따른 지원 플랫폼의 성공 API를 요청했다" 가 됩니다. DisplayName이 이를 자세히 설명하지 않는 이유는 예상하신대로 어플리케이션에서 외부 API에 의존하는지에 대해 관심을 갖지 않는 context를 반영한 결과이구요.

하지만 말씀주신대로 "예제 자동 채점"에 대한 실패 여부에 대해서는 인수테스트가 작성되어 있지 않기 때문에 이부분은 추가하도록 하겠습니다! 좋은 피드백 감사드립니다 ☺️

2022-10-14 01:30 UTC, woowahan-neo approved these changes
고생 많으셨습니다!

2022-10-14 01:30 UTC, woowahan-neo commented on src/main/kotlin/apply/application/JudgmentService.kt
> +        val commit = assignmentArchive.getLastCommit(assignment.pullRequestUrl, mission.period.endDateTime)
```suggestion
        val commit = assignmentArchive.getLastCommit(assignment.pullRequestUrl, mission.period.endDateTime)
        var judgment = judgmentRepository.findByAssignmentIdAndType(assignment.id, judgmentType)
            ?: judgmentRepository.save(Judgment(assignment.id, judgmentType))
```

a: 케이스는 적겠지만 불필요한 엔티티 생성을 최소화하기 위해 순서를 변경 할 수 있겠네요 ㅎㅎ

2022-10-14 01:30 UTC, woowahan-neo commented on src/main/kotlin/apply/infra/github/GitHubClient.kt
> +            ?: throw IllegalArgumentException("올바른 형식의 Pull Request URL이어야 합니다")
```suggestion
            ?: throw IllegalArgumentException("올바른 형식의 Pull Request URL이어야 합니다.")
```

c: 마침표가 빠졌네요!

2022-10-14 01:47 UTC, kth990303 approved these changes
로직 짜는 과정 정말 어려웠을 것 같은데 수고하셨어요!
이제 자동채점이 된다~~

2022-10-14 01:47 UTC, kth990303 commented on src/test/kotlin/apply/infra/github/GitHubClientTest.kt
> +    }
a: 테스트가 추가된 것 좋네요! 👍

2022-10-14 01:47 UTC, kth990303 commented on src/main/kotlin/apply/infra/github/GitHubClient.kt
> +            ?: throw IllegalArgumentException("올바른 형식의 Pull Request URL이어야 합니다")
c: 아래처럼 바꿔도 좋을 것 같아요!
```suggestion
            ?: throw IllegalArgumentException("올바른 형식의 Pull Request URL이어야 합니다. pullRequestUrl: $pullRequestUrl")
```

2022-10-14 01:47 UTC, kth990303 commented on src/main/kotlin/apply/application/GradingService.kt
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
a: 이건 궁금한건데 전파레벨을 `REQUIRES_NEW`로 변경해준 이유가 궁금해요!
5분이 지나도 해당 트랜잭션은 진행되게 하기 위해서인가요?

2022-10-14 01:53 UTC, MyaGya commented on src/test/kotlin/apply/application/JudgmentIntegrationTest.kt
> +        When("해당 커밋의 자동 채점이 성공하면") {
답변 감사합니다
해당 리뷰를 할 때에는 채점 로직을 외부 API를 활용하는 지에 대해서는 몰랐었는데요 외부 API에 의존하지 않는지에 대해 context를 가지고 있다면 테스트에서 확실하게 에러가 발생하는 케이스에 대해서 짚어 두어야 하는게 좋습니다!
외부 API는 테스트 과정에서 단순히 로직에 따른 성공 / 실패를 떠나서 해당 서버의 상태에 따라서 간헐적인 연결 불량이 일어나는 경우, 보안 정책이 적용 되어 있다면 토큰이나 IP 설정이 되어있는지 등 로직과 관련 없는 오류도 많이 발생할 수 있기 때문에 처음 해당 코드를 유지보수하기 위해서 접하는 사람은 실패 원인에 대해서 헤매는 경우가 많이 발생합니다.
때문에 외부 API측에서 충분히 오류 원인을 제공하여 사용하는 측에서 핸들링 하는데에 제약이 없도록 하는 편이 유지보수 측면에서 깔끔한 코드가 되지 않을까 싶어요

고생 많으셨습니다!

2022-10-14 02:39 UTC, kbsat approved these changes
안녕하세요! 파리! 로직이 많이 복잡했을 것 같은데 고생많으셨네요.
이번 코드 보면서 트랜잭션, 이벤트 에 대해서 공부해봐야겠어요 😉
저도 케이처럼 `REQUIRED_NEW` 를 설정하게 된 배경이 궁금해요~! 한번 알려주시면 좋을 것 같아요
Repository에 인자이름이 오탈자가 있는 것 같아서 해당 부분 리뷰남겼어요!

2022-10-14 05:25 UTC, SuyeonChoi approved these changes
차리 파랑 마지막까지 수고가 많으셨습니다!👏👏
궁금한 점 하나 질문하고 갑니다,,,
답변 기다리겠습니다👀👀

2022-10-14 05:25 UTC, SuyeonChoi commented on src/main/kotlin/apply/domain/judgment/Judgment.kt
> +    @OneToMany(cascade = [CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE], fetch = FetchType.EAGER)
a: 혹시 FetchType을 왜 `EAGER`로 설정했는지 알 수 있을까요?

2022-10-14 05:42 UTC, merged