feat(apply): change so that clicking Recruit doesn't create an application
woowacourse/service-apply pull request #708
Opened 2023-08-10 06:58 UTC by woowahan-cron

Resolves #477 

# 해결하려는 문제가 무엇인가요?

- 메인페이지에 모집 항목을 최초로 클릭하여 진입하더라도 "임시 저장되었습니다" 문구가 뜨고 실제로 지원서가 서버에서 생성됩니다.

# 어떻게 해결했나요?

- 적는 중...

# 어떤 부분에 집중하여 리뷰해야 할까요?

- API 문서에서 "최종 지원서 조회" 항목 "실패" 문구를 붙여야 할지...

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2023-08-11 02:11 UTC, woowahan-cron commented on frontend/src/api/applicationForms.ts
> +export type FetchFormRequest = RequestWithToken<{ recruitmentId: number | null }>;
recruitmentId의 값을 어떤 타입으로 가지고 있을지에 관해서 논의가 필요할 수도 있습니다.
리액트 내에서도 어떤 타입은 recruitmentId가 string으로 정의되어 있고 나머지는 number로 정의되어 있어서 혼선이 있었습니다.
일단 서버에서 받아 온 타입 그대로 number로 설정해 두겠습니다.

2023-08-11 02:11 UTC, woowahan-cron commented on frontend/src/components/MyApplicationItem/MyApplicationFormItem/MyApplicationFormItem.tsx
> -          status: PARAM.APPLICATION_FORM_STATUS.EDIT,
지원서 조회 API를 이용해서 생성/삭제 여부를 알 수 있어서 이 상태는 굳이 넘길 필요가 없어 보였어요.
또한, `/`, `/recruits`에서 `/application-forms`페이지로 진입할 때 넘겨 받는 state에 대한 의존성이 있어 페이지 직접 접근 시 오류가 발생하는 문제가 있었습니다. 이것을 최소화하려는 시도를 해봤습니다.

2023-08-11 02:11 UTC, woowahan-cron commented on frontend/src/constants/application.ts
> +};
`frontend/src/hooks/useApplicationRegisterFormFetching.ts`에서 키 값을 상수화해서 사용해 보면 좋겠다는 생각이 들어서 const assertion을 사용했어요. 적절한지 검토 부탁드릴게요

2023-08-11 02:11 UTC, woowahan-cron commented on frontend/src/constants/path.ts
> +  APPLICATION_FORM: "/application-forms",
지원서 조회 API로 new/edit을 구별할 수 있어 라우팅에서 이와 관련된 키워드는 모두 삭제했습니다.

2023-08-11 02:11 UTC, woowahan-cron commented on frontend/src/hooks/useApplicationRegisterFormWriting.ts
> +const upsertAnswers = async ({
지원서 생성, 수정 API를 하나의 공통함수로 묶어볼 수 있었습니다

2023-08-11 02:11 UTC, woowahan-cron commented on frontend/src/hooks/useRecruitList.ts
> +  );
지원 가능여부에 대한 조건을 가능한 한 아래와 같이 우선순위를 정해 모집 가능 여부를 설정했습니다.

1. 관리자가 모집 시작/중지를 누른 상태
2. 모집 종료된 상태인지
3. 모집 기간이 지났는지

2023-08-11 02:11 UTC, woowahan-cron commented on frontend/src/pages/ApplicationRegister/ApplicationRegister.tsx
> +  });
나중에 이 두 가지의 훅에 대한 의존성을 해결해야 할 것 같아요 ㅠㅠ
합치자니 너무 많고 복잡하고, 분리하자니 애매한 면이 있어 보이기도 합니다.
일단 기존의 것대로 아래와 같이 구성해봤습니다.

1. useApplicationRegisterForm은 입력 양식에 관한 훅 작성
2. useApplicationRegisterFormUpserting은 입력한 내용을 서버에 API를 요청하는 훅

2023-08-11 02:11 UTC, woowahan-cron commented on frontend/src/pages/AssignmentSubmit/AssignmentSubmit.js
> +      if (status === PARAM.ASSIGNMENT_STATUS.EDIT) {
불필요한 상태를 정리하다가 다른 곳에서 오타가 발견되어 이것도 수정해 둡니다 (이곳은 과제 제출에 관한 곳이에요)

2023-08-14 08:20 UTC, woowapark requested changes
크론 안녕하세요~! 먼저, 첫 번째 PR을 축하드려요! 🎉
백엔드부터 프론트엔드까지 함께 확인하면서 작업해주시느라 정말 고생 많으셨습니다~! 👏👏👏👏👏     

코멘트 남겨주신 부분들과 함께 코드 라인에서의 리뷰를 먼저 남길까 하다가 
아직 프로뎍션 배포 일정까지는 여유가 있기도 하고, 이 이슈와 PR은 지플폼에서의 작업 방식과 단위를 맞춰가기 위한 목적도 있으니 요런 것들을 먼저 같이 이야기해 보면 좋을 것 같아 코멘트로 남겨둡니다.   
의견은 코멘트로 남겨주셔도 좋고, 수요일에 오프라인에서 같이 이야기 나눠도 좋습니다!      
세부적인 코드들은 이야기 나눈 뒤에 추가로 더 볼게요!      

### 1 이슈와 PR 단위

부득이한 경우가 아니라면, 하나의 PR에서는 하나의 이슈에 해당하는 수정 사항만 포함되도록 하는 것을 작업 단위로 제안해 드리고 싶은데요! 현재 PR에서 다루는 범위가 여러 이슈에 걸쳐있는 게 아닌가 싶어요. 

나중에 이 PR을 보거나, 머지된 후에 이 PR이 하나의 커밋으로 squash되어 히스토리에 들어가는 만큼 히스토리에서 이 PR에 해당하는 커밋 하나를 보았을 때 여러 이슈가 한번에 해결되어 있으면 헷갈릴 때가 있더라고요. 
예를 들어, 아래 2가지 항목에 대한 작업 내역을 분리해보면 어떨까요? 

- 중간에 같이 이슈 논의를 하였을 때 [[‘임시저장 문구 노출 조건 수정’은 별개의 이슈로 보는 게 어떨지](https://github.com/woowacourse/service-apply/issues/477#issuecomment-1651044727)](https://github.com/woowacourse/service-apply/issues/477#issuecomment-1651044727) 논의했던 것 같아요. 이 PR에는 백엔드 수정 사항도 같이 있는만큼, API 수정과 함께 수정해야 하는 플로우 수정에 대한 코드만 남기고 요 문구 노출 조건을 수정하는 것은 별개의 이슈를 생성하고 PR도 따로 만들면 어떨까요? PR 제목에 이슈 요약도 잘 남겨주셨는데, 이후에 이 제목을 보았을 때는 ‘모집 아이템을 클릭했을 때 지원서를 생성하지 않도록’ 수정한 PR이구나~하게 될 테니 요런 세부적인 문구 수정이 여기에서 같이 되었을 거라고 찾기 쉽지 않을 것 같아요.
- 타입스크립트로 바꾸는 것은 너무 좋지만..! 위와 마찬가지로 이것도 별개의 이슈 및 PR에서 진행하면 어떨까요? 파일 확장자 자체가 바뀌는 작업이다 보니, 수정사항에서 파일 전체가 diff로 잡히고 있어 이 이슈만을 위해 수정된 코드가 무엇인지 빠르게 파악하기 어려울 수 있을 것 같습니다. 직접 작업하는 입장에서는 다소 번거롭게 느껴질 수는 있지만, 가능하면 ‘ㅇㅇ을 타입스트립트 전환’하는 것도 하나의 독립적인 이슈로 만들고 분리해서 작업하는 PR이 있다면 해당 PR에서는 타입스크립트와 관련한 부분에 대해서면 집중해서 리뷰하고 의견도 주고받을 수 있을 것 같아요.

### 2 테스트 대상이 되는 수정된 버전의 기능 명세

실제로 사용자가 사용하는 플로우 자체가 변경되는 feature 이슈이니, 이 PR의 수정 사항과 관련해서 같이 동작을 확인해야 하는 기능 명세의 최종본을 함께 기록해두면 어떨까요?             
(구체적인 코드 수정 사항에 대한 설명과 별개로, 기능 명세의 AS-IS & TO-BE)

- 이 PR에서 어떤 기능이 어떻게 변경되었는지를 나중에 파악하기 쉽고
- 로컬에 받아서 기능 동작을 확인할 때도 어떤 플로우를 집중적으로 테스트해보아야 하는지를 명확하게 할 수 있어서 ‘코드’에 대한 리뷰 뿐만 아니라 실제로 ‘기능’ 동작에 문제가 없는지 같이 검증하기에 좋습니다.
- 이후에 테스트 코드로 보강할 때도 테스트 명세 단위로 활용할 수 있거나, 프로덕션 배포 나갈 때 최종적으로 확인해야 하는 기능 명세가 무엇인지에 대해 정리해둔다는 의미도 있고요.

### 3 기능과 리팩터링

1번과 유사한데, 기능 추가와 리팩터링도 가능하면 별개의 작업으로 진행하는 것이 더 명확할 것 같아요. 기능 구현을 위해 꼭 수정이 필요한 부분들은 feature 개발에서 같이 수정하고, 기능 자체는 그대로 유지하지만 코드 레벨에서의 리팩터링이 필요한 부분들은 가능하면 refactor 이슈를 따로 만들어서 진행하는 것이 이후에 히스토리를 더 빠르고 명확하게 파악할 수 있지 않을까 싶습니당. 
예를 들면 요런 부분들은 이 PR에서 구체적으로 더 논의하기보다는, 리팩터링 이슈로 분리해서 추가로 작업할 대상으로 볼 수 있는 이슈들이 될 것 같아요. 이 외에도 직접 작업해보시면서 리팩터링이 필요해 보이는 데? 싶은 부분들이 있으셨다면 그런 부분들을 이슈로 제안해 주셔도 좋고요. 

- 리뷰 포인트에 남겨주신 import문 정리
    - 어떤 부분에 대한 정리가 필요해 보이는지와 함께 남겨주시면 별도 이슈로 볼 수 있을 것 같아요!
- 코드 내 TODO 주석으로 남겨주신 부분
    - 주석으로 작성하기보다는 이슈로 만들어두면 어떨까요?
    - +) TODO 주석 외에도 주석으로 남아있는 부분들이 있는데 혹시 의도해서 남겨두신 부분들일까용?

2023-08-16 00:28 UTC, woowahan-cron commented
공원, 안녕하세요✋🏻. 리뷰어로 align해주셔서 감사합니다.

먼저, 말씀해 주신 부분과 관련되어 업무 방식을 맞춰가면 좋겠다는 생각에 동의하는데요!
저도 이 이슈를 진행하면서 건드려야 할 부분들은 별개의 이슈로 진행하면 어떨까 싶다가도 코드 수정이 몇 줄 안 되는 이슈를 만들면서까지 행정적인 절차를 거치면서 얻는 효용성이 더 클까? 하는 고민이 있었어요. 그래서 일단 관련 있는 작업끼리 묶어서 진행하고 리뷰를 거치면서 합의해 나가는 과정이 의미가 있겠다는 생각이 들더라구요.

## 1. 이슈 작업과 PR의 작업 단위

저도 개인적으로 이 이슈에는 관련된 작업만 있는 것이 더 바람직하다고 느끼고 있습니다. 말씀해 주신 대로 다음달 말 정도로 예상되는 프로덕션 배포 일정상으로는 아직 시간이 많이 남아 있어 보이지만, 계산해 보면 실질적으로 많은 일을 할 수 있을지에 관한 고민이 들었습니다.

지원플랫폼 업무만 하더라도 해당 이슈 말고도 공원 주도 이슈가 있으신 것으로 압니다. 저 또한, 공원이 주도하여 작업하신 부분을 리뷰하면서 기능 전체의 흐름과 업무를 파악하는 저의 시간도 필요할 것이라고 예상했습니다. 또한, 레벨4를 위한 커리큘럼 준비 및 피드백, 브랜딩 근로, 지원플랫폼 이외의 선발과 관련된 회의와 업무, 기타 팀내 회의를 고려한다면 현실적으로 여러 개의 이슈를 쪼개서 리뷰 작업을 하는 절차를 만드는 것이 과연 기한을 지키며 모두 프로덕션 배포를 완수할 수 있을까?에 대한 의문이 들었어요. 이슈 작업을 잘게 쪼개어 이후 작업을 용이하게 하는 것은 매우 바람직하지만, 이슈 등록과 정리, 코드 리뷰 요청, 요청까지 걸리는 데 걸리는 시간, 리뷰에 대한 내용을 수정하는 데 드는 시간 등 외부적인 요인을 고려한다면요. 이제 막 작업을 착수하게 된 저로서는 현실적으로 어렵지 않을까? 하는 두려움이 스며들더라구요. 하지만, 공원은 이전부터 지원 플랫폼 작업을 진행하셨으니까 이전 경험을 토대로 제게 조언을 주신다면 작업 내용을 조정해 볼 수 있을 것 같아요!

## 2. 버전의  기능 명세

좋습니다! 함께 기록할 수 있는 시간도 잡아서 히스토리를 명시하면 좋을 것 같아요!

## 3. 기능(feature)과 리팩터링(refactor)

작업을 어떻게 분리할지는 오프라인으로 만나서 이야기를 하고 진행해 보는 것이 좋을 것 같아요!

- 리뷰 포인트에 남겨주신 import문 정리와 TODO 주석
   - PR에 등록된 diff코드를 기반으로 리뷰를 진행하면서 별도의 이슈가 필요한지 함께 검토한 뒤 이슈로 등록하고 싶었습니다! 이 부분과 관련되어 작업하다가 파생되는 이슈를 등록하는 방식에 관해서도 함께 이야기를 나누면 좋겠습니다! 
 
그럼. 오프라인에서 뵙겠습니다 🙇‍♂️

2023-08-16 07:11 UTC, woowahan-cron commented
## 논의 결과

아래의 5가지 작업 단위에 따라 이슈를 분할하고 작업을 진행하여 PR을 업로드하기로 하였습니다.
PR을 업로드하는 순서는 1->2->3,4->5로 진행하려고 합니다. (혹시 변동사항이 있으면 사전에 공유할게요!)
해당 PR은 작업 방식과 단위를 맞추기 위한 의사소통을 기록으로서 CLOSE하여 남겨두고 새로운 PR에서 새로운 마음가짐으로 다시 작업 진행하겠습니다 🏃🏼‍♂️

1. [fix: 지원하기 페이지에서 지원서가 작성되었는지 확인하도록 수정](https://github.com/woowacourse/service-apply/pull/708/commits/df84cbb4c0d699837e37dea069b19b97fc0eaec6)
2. ['임시 저장되었습니다 문구 노출 조건 수정'](https://github.com/woowacourse/service-apply/issues/477#issuecomment-1651044727)에 관련된 부분은 별도의 이슈로 분리
3. 리팩터링 작업을 제외한 타입스크립트 마이그레이션 작업 진행
4. 리팩터링 작업 진행
5. 라우팅 경로 개선과 URL 직접 입력 시 페이지가 로드되지 않는 현상 수정

2023-08-16 07:11 UTC, closed without merging