feat(evaluation item): implement evaluation item
woowacourse/service-apply pull request #78
Opened 2020-09-16 03:46 UTC by toneyparky

resolve: #77 

구현상의 특별한 이슈는 없습니다.
관리 화면 바딘 뷰는 제작하지 않았습니다.
머지되는 대로 24를 진행하겠습니다.
추가적으로 이 커밋과 제이슨의 생성뷰가 머지될 경우에 #17 도 구현이 가능합니다.

2020-09-16 06:35 UTC, dks301 approved these changes
코틀린 잘 배우고 갑니다 토니 👍 
간단한 피드백 남겼으니 확인해주세요 :)

2020-09-16 06:35 UTC, dks301 commented on src/main/kotlin/apply/ui/api/EvaluationRestController.kt
> +    fun findItemsByID(@PathVariable("id") evaluationId: Long): ResponseEntity<List<EvaluationItem>> {
통일 성을 위해서 Id는 어떨까요?
`findItemsById()`

2020-09-16 06:35 UTC, dks301 commented on src/test/kotlin/apply/domain/evaluationitem/EvaluationItemRepositoryTest.kt
> +            { assertThat(results).usingElementComparatorOnFields("id").isNotNull() }
모든 field가 `nullable=false` 니 `assertThat(results).isNotNull() `로 충분하지 않을까요??
id만 따로 `usingElementComparatorOnFields()`를 사용한 이유가 있나요??

2020-09-16 07:11 UTC, ddaaac requested changes

2020-09-16 07:11 UTC, ddaaac commented on src/main/kotlin/apply/ui/api/EvaluationRestController.kt
> +class EvaluationRestController(
평가항목은 관리자 페이지에 노출되지 않나요?

2020-09-16 07:13 UTC, toneyparky commented on src/main/kotlin/apply/ui/api/EvaluationRestController.kt
> +    fun findItemsByID(@PathVariable("id") evaluationId: Long): ResponseEntity<List<EvaluationItem>> {
오잉 오타를 냈군요. 수정하겠습니다!

2020-09-16 09:30 UTC, toneyparky commented on src/main/kotlin/apply/ui/api/EvaluationRestController.kt
> +class EvaluationRestController(
오 이부분은 제 미스네요. 

평가항목은 api로 쏠 일이 없기에 해당 컨트롤러 제거하도록 하겠습니다.

조금 더 요구사항을 고려하여 코딩하도록할게요😢
고마워요 범!

2020-09-16 09:57 UTC, toneyparky commented on src/test/kotlin/apply/domain/evaluationitem/EvaluationItemRepositoryTest.kt
> +            { assertThat(results).usingElementComparatorOnFields("id").isNotNull() }
59번째 라인에서 id를 제외한 다른 필드들에 대해서 position 순서에 따라 반환되는지를 확인했으니,
60번째 라인에서는 id가 잘 들어있는지 해당 필드만 확인하는 개념으로 사용하였습니다🙂

물론 isNotNull을 사용하여 전체를 검사해도 괜찮지만 **테스트에서는 명시적으로 id만이 들어있는지의 여부를 보여줄 필요성**이 있다 생각했습니다.

2020-09-16 11:58 UTC, ddaaac approved these changes
좋습니다 👍

2020-09-16 13:14 UTC, LTTTTTE approved these changes
공통 컴포넌트 만들어지기전의 선행 코드군요
깔끔한 코드 잘봤습니다.
모두들 너무 잘하네요...😄

2020-09-16 13:14 UTC, LTTTTTE commented on src/main/kotlin/apply/domain/evaluationItem/EvaluationItem.kt
> +    val maximumScore: Int = 2,
기본값은 정해주지 않으면 2인것은 의도한건가요?

2020-09-16 13:16 UTC, toneyparky commented on src/main/kotlin/apply/domain/evaluationItem/EvaluationItem.kt
> +    val maximumScore: Int = 2,
저희 프로토타입에 있는 평가항목의 최대 점수가 2로 나와있기에 이를 반영해서 2로 뒀습니다.

추후에 충분히 변경가능하다고 생각합니다🙂

2020-09-16 13:18 UTC, LTTTTTE commented on src/main/kotlin/apply/domain/evaluationItem/EvaluationItem.kt
> +    val maximumScore: Int = 2,
오호 설명감사합니다

2020-09-17 07:50 UTC, lalize approved these changes
잘 구현하셨어요! 👍

2020-09-18 00:22 UTC, woowahan-pjs approved these changes
수고 많으셨습니다. 👍

2020-09-18 00:22 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationItemService.kt
> +    fun findByEvaluationId(evaluationId: Long): List<EvaluationItem> {
함수 이름만 수정하면 됩니다. 👍 

```suggestion
    fun findByEvaluationIdOrderByPosition(evaluationId: Long): List<EvaluationItem> {
```

2020-09-18 00:42 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationItemService.kt
> +    fun findByEvaluationId(evaluationId: Long): List<EvaluationItem> {
수정하여 커밋완료했습니다~!

2020-09-18 00:46 UTC, merged