feat(evaluation target): implement evaluation target and load logic
woowacourse/service-apply pull request #91
Opened 2020-09-23 06:35 UTC by toneyparky

resolve: #89 

복잡하고 중요도 높은 로직이고 저 혼자 구현했기에 상세한 리뷰 부탁드립니다..!!
허점이 있을게 분명해요🙃

구현은 아침에도 보여드렸듯 4가지 분기로 처리됩니다. 

알려드릴 사항이 있습니다.

1. 테스트 코드의 픽스쳐를 정리하지 못했습니다. 
[해당 리뷰](https://github.com/woowacourse/jwp-refactoring/pull/2#discussion_r491043437)를 보고나니 setUp으로 분리하기 힘든 여지가 많이 보여서 문맥에 맞추기 위해 각 메서드에 놔뒀습니다.
추후 메서드나 fixture 파일로 분리할 여지가 있습니다.
가독성을 위한 아이디어가 있다면 부탁드립니다~!

2.
평가 대상자 갱신(update) 시 삭제를 진행합니다(EvaluationTargetRepository의 메서드 사용) 
이때 전략에 대해 이야기 나눠보고 싶습니다.

~~~java
interface EvaluationTargetRepository : JpaRepository<EvaluationTarget, Long> {
... 중략 ...

    fun deleteByApplicantIdIn(applicantIds: Collection<Long>)

    fun deleteByEvaluationIdAndApplicantIdIn(evaluationId: Long, applicantIds: Collection<Long>)
}
~~~
현재는 두 삭제 메서드 중 deleteByEvaluationIdAndApplicantIdIn 메서드를 사용하여 삭제를 진행합니다.

즉 EvaluationId를 이용하여 해당되는 평가에서만 평가 대상자를 제거합니다. 

예를 들자면 평가 1, 2, 3이 있습니다.
이미 평가 2은 평가 대상자를 불러와서 평가 1로부터 정보를 가져와 평가 대상자를 DB에 저장한 상태입니다.

또한 평가 3은 평가 대상자를 불러와서 평가 2로부터 정보를 가져와 평가 대상자를 DB에 저장한 상태입니다.

평가 대상자 A는 평가 1, 2 모두 PASS했고 부정행위자가 아니기에 평가 3의 평가 대상자에 포함되어 있습니다. (WAIT 상태)

이 상황에서 기존 1 평가에서 PASS를 받은 평가 대상자의 평가를 FAIL로 바꾸고 평가 2를 다시 불러온다면, 
**현재 상황에서는 평가 2에서는 평가 대상자 A가 삭제되지만 평가 3에서는 삭제되지 않습니다.**

반면 deleteByApplicantIdIn 메서드를 사용한다면 평가 3에서도 평가 대상자A가 삭제될 것입니다. 

이 부분에 대한 정책을 생각해보면 좋을 것 같습니다.

3. 요구사항 상 자주 눌리지 않는 버튼으로 알고 있고, DB 성능에 대해 많이 고려하지 않고 구현을 진행하기로 해서 레포지토리를 요리조리 활용했습니다. 
최적화할 수 있는 여지가 있다면 피드백 부탁드립니다 😎

감사해요~!

2020-09-24 15:47 UTC, ddaaac reviewed
대단하다는 말밖에 할 말이 없네요 👍 
저도 열심히 리뷰해봤습니다!

논의해보면 좋겠다고 하신 2번 문제에 대한 제 의견을 말씀드리면
한 지원자가 모집 A와 모집 B에 지원했을 경우, 첫번째 `deleteByApplicantIdIn`을 사용하면 
모집 A의 평가 1,2,3에 해당하는 target만 삭제해야되는데
모집 B의 평가 4,5에 해당하는 target도 삭제해버릴 것 같아요.

2020-09-24 15:47 UTC, ddaaac commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +    private fun saveEvaluationTarget(evaluation: Evaluation): MutableList<EvaluationTarget> {
리턴 타입이 그냥 `List`여도 될 것 같습니다 😄

2020-09-24 15:47 UTC, ddaaac commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .filter { EvaluationStatus.PASS.equals(it.evaluationStatus) }
코틀린은 null safe하기 때문에 `==` 비교도 괜찮아보입니다!(사실 인텔리제이에서 추천해주더라고요)

2020-09-24 15:47 UTC, ddaaac commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            evaluation.hasBeforeEvaluation() && isSavedBefore -> updateEvaluationTarget(evaluation)
기존 target이 없으면 save, 있으면 update를 실행하네요.
save, update의 공통점은 새로운 `EvaluationTarget`들을 생성한다는 점이고
차이점은 update는 필요 없어진 target들을 지우고 새로운 target들을 추가한다는 점이고요.

그런데 save 대신 항상 update를 실행하면 어떨까?라는 생각이 듭니다.

이렇게 수정하면 필요없는 메서드들이 조금 더 실행될 수는 있겠지만, 아래 분기문은 4개에서 2개로 줄어들어서 코드가 읽기 편할 것 같아요.

제가 써놓고도 잘 이해가 되지 않는 코멘트네요... 내일 만나서 얘기해보면 좋을 것 같아요 😂

2020-09-24 15:47 UTC, ddaaac commented on src/test/kotlin/apply/application/EvaluationTargetServiceTest.kt
> +    private val evaluationTargetRepository: EvaluationTargetRepository
이 레파지토리도 mocking하면 `@DataJpaTest`는 뺄 수 있지 않나요?

2020-09-24 15:47 UTC, ddaaac commented on src/test/kotlin/apply/application/EvaluationTargetServiceTest.kt
> +                )
링크 걸어주신 용근 님의 코멘트를 보면 중복처리는 메서드로 분리할 수 있다고 하네요 :)

`ApplicantForm`에서 꼭 달라져야 되는 값인 `id`, `applicantId` 등 파라미터로 받아서 생성하는 메서드가 있으면 코드 줄 수가 줄어들 수 있을 것 같아요

2020-09-24 15:47 UTC, ddaaac commented on src/test/kotlin/apply/domain/evaluationtarget/EvaluationTargetRepositoryTest.kt
> +    @ParameterizedTest
원시타입에 대해서는 `CsvSource`를 쓰는건 어떻게 생각하시나요?

저는 스크롤을 움직이지 않고 확인할 수 있어서 그 편을 조금 더 선호합니다 ㅎㅎ

2020-09-25 06:39 UTC, dks301 reviewed
어려운 로직인데도 잘 구현하셨네요!! 💯 
간단한 수정사항만 남겼습니다.
질문하신 부분은 개인적으로 평가 3이 수정되지 않는다면,
두 명 이상의 관리자가 작업했을 경우 관리자 A는 평가 1을 Fail, 관리자 B는 평가3을 Pass로 하는 등 예외처리 로직이 복잡해질 것 같아요

2020-09-26 05:38 UTC, LTTTTTE reviewed
저도 2번문제에 관해서 의견을 드리자면,
2번문제에 있을 상황이 엄청 특이 케이스라 생각합니다.
부정행위자가 아닌이상 결과가 번복될일이 없을거라 생각하거든요.

2020-09-26 05:38 UTC, LTTTTTE commented on src/test/kotlin/apply/application/EvaluationTargetServiceTest.kt
> +    fun `이전 평가가 있고 저장 된 평가 대상자가 있을 경우 갱신하고 불러온다`() {
지금 보이는 경우가 있기 전에
'이전평가가 있고 저장 된 평가 대상자가 없을 경우'가 먼저 올거라 생각해요.
그럼
evaluation.hasBeforeEvaluation() && !isSavedBefore -> saveEvaluationTarget(evaluation)
분기를 통해 
saveEvaluationTarget(evaluation) 메소드가 먼저 실행 되는데,
그렇게 되면 
`이전 평가가 있고 저장 된 평가 대상자가 있을 경우 갱신하고 불러온다` 테스트 에서는
이전 평가의 결과가 필요없을 것이라 생각이 듭니다.

(만약 이말이 맞으면 로직이 조금더 간단해질수도??)

2020-09-27 11:02 UTC, ddaaac commented on src/main/kotlin/apply/domain/evaluationtarget/EvaluationAnswer.kt
> +    private val EvaluationItemId: Long
참고하다가 우연히 발견한건데, 맨 앞글자가 대문자네요!

2020-09-28 02:19 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        evaluationTargetRepository.saveAll(additionalEvaluationTargets)
너무 늦은 답변이네요 😂
자소서 수고해써용

우선 `update`라는 메서드를 호출하는 메서드 자체가 이전에 `load` 메서드가 실행되어 평가 대상자가 DB에 저장되어 있는 경우에 한하여 호출됩니다.

그리고 말씀하셨듯 `update` 관련 메서드들은 이전 평가 대상자가 부정 행위자로 등록되거나(현재 평가 대상자에서 삭제) 이전 평가에서 새로운 지원자가 들어올 경우(현재 평가 대상자에 새롭게 추가)에 호출됩니다.

거기에 **추가적으로 이전 평가에 있는 평가 대상자의 평가 상태의 영향**도 받습니다.
평가 상태가 PASS에서 FAIL로 바뀌거나(현재 평가 대상자에서 삭제) 그 반대의 경우(현재 평가 대상자에 새롭게 추가)에도 지금 평가의 평가 대상자에 업데이트를 해줘야하기에 그 상황에 대해서도 처리를 했습니다.

범이 말해줬듯 해당 케이스들에 대해 테스트 메서드 명으로 더 잘 명시했다면 이해하기 쉬웠을텐데 정말 간단하게 4가지 분기에 대한 내용만 명시했네요. 

수정해보겠습니다😬

2020-09-28 02:25 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +    private fun saveEvaluationTarget(evaluation: Evaluation): MutableList<EvaluationTarget> {
처음 설계에서는 생성하고 나온 평가 대상자에 추가하는 로직이 있었기에 MutableList로 해두고 수정하지 못했네요.

좋은 포인트 땡큐!

2020-09-28 02:29 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .filter { EvaluationStatus.PASS.equals(it.evaluationStatus) }
==로 바꾸라는 인텔리제이의 말을 보고서 이놈이 뭔 소리를 하는건가 하고 구글링을 해도 별 이야기가 안나왔어서 넘겼는데, 제가 깊게 알아보지 못했네요.

Target에 
~~~kotlin
    fun isSameStatusWith(evaluationStatus: EvaluationStatus) = this.evaluationStatus == evaluationStatus
~~~
을 만들어 비교하도록 했습니다.

2020-09-28 03:16 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            evaluation.hasBeforeEvaluation() && isSavedBefore -> updateEvaluationTarget(evaluation)
load 내부 구현에 대해서 피드백 줘서 고마워용
저도 4개 분기 말고 다른 방법이 있으면 적용하고 싶네요.

범이 말한 부분을 더 고려해서 리팩토링 진행해볼게요...!

2020-09-28 03:18 UTC, toneyparky commented on src/test/kotlin/apply/domain/evaluationtarget/EvaluationTargetRepositoryTest.kt
> +    @ParameterizedTest
맞아요..! CsvSource를 사용하는 편이 더 나을거 같네요!

수정해씀니다🙂

2020-09-28 03:28 UTC, toneyparky commented on src/test/kotlin/apply/application/EvaluationTargetServiceTest.kt
> +                )
넵 저도 그런 방향으로 리팩토링하는게 가장 현실적이라구 생각드네요..!

현재 mock 사용이 많아 load 로직이 바뀔 경우 수정될 여지가 있기에 로직을 확정한 후에 다시 처리해보겠슴니다.

유익한 피드백 고마범😀

2020-09-28 03:31 UTC, toneyparky commented on src/test/kotlin/apply/application/EvaluationTargetServiceTest.kt
> +    private val evaluationTargetRepository: EvaluationTargetRepository
load 메서드의 내부 구현이 바뀌더라도 핵심이 되는 EvaluationTargetRepository를 사용하는 로직의 변화를 최대한 줄여보려고 이 친구는 Mock을 사용하지 않았습니다.
아래의 코멘트와 같이 load 메서드의 내부 로직이 확정되고 모두 Mock을 사용하는게 낫다고 느껴질 때에 수정해볼게요.

다른건 다 Mock인데 이거만 아니라 충분히 ? 를 던질 수 있다구 생각합니다😌

2020-09-28 03:32 UTC, toneyparky commented on src/test/kotlin/apply/domain/evaluationtarget/EvaluationTargetRepositoryTest.kt
> +                1L
항상 제 코드에서는 안보이는 마아법... ㅋㅋㅋ

잘 집어줘서 고마워요 !

2020-09-28 03:34 UTC, toneyparky commented on src/main/kotlin/apply/domain/evaluationtarget/EvaluationAnswer.kt
> +    private val EvaluationItemId: Long
앗...
수정해씀니다.

캐시미어처럼 섬세해요...👍

2020-09-28 07:17 UTC, toneyparky commented on src/test/kotlin/apply/application/EvaluationTargetServiceTest.kt
> +    fun `이전 평가가 있고 저장 된 평가 대상자가 있을 경우 갱신하고 불러온다`() {
오구 말대로 갱신과 관련된 메서드들이(`updateEvaluationTargetOfFirst, updateEvaluationTarget`) 실행되기 전에는 저장된 평가 대상자가 없을 때에 실행되는 저장과 관련된 메서드(`saveEvaluationTargetOfFirst, saveEvaluationTarget`)가 선행이 되어있는 상태겠죠.

예를 한번 들어볼게요. 9월 27일 어제, 평가 2에 대해 `load()`를 호출하니 `saveEvaluationTarget()`가 호출되었습니다.
`load()`가 호출되기 전 상황은 평가 1과 평가 2가 있고 평가 1에는 지원자 A, B, C가 있었어요. 모두 PASS 상태구요. 또한, 평가 2에 대한 평가 대상자는 아직 생성되지 않은 상태죠. 다만 지원자 PASS 상태로 된 이후에 부정 행위가 발견되어서 C는 부정 행위자로 등록이 되어있어요.
이 경우에서, `load()` 호출 후에는. 지원자 A, B가 `EvaluationTarget`에 들어가겠지요.

여기까지가 `이전평가가 있고 저장 된 평가 대상자가 없을 경우`에 대한 시나리오였고 이제 `이전 평가가 있고 저장 된 평가 대상자가 있을 경우 갱신하고 불러온다`로 가볼게요.

9월 28일 오늘 평가 2에 대해 `load()`를 호출하니 `updateEvaluationTarget()`가 호출되네요.
그런데 하루 사이에 평가 1의 지원자 평가대상자 대한 수정과 지원자 추가가 이뤄졌어요.
우선 기존 평가 대상자(지원자) A의 평가가 PASS에서 FAIL로 바뀌었구요. 지원자 D가 추가되었네요.

이 경우에는 기존에 저장되어있던 EvaluationTarget A, B에서 A가 FAIL이기에 제거되고, D가 추가되어야 하기에 => B, D로 저장 내용이 바뀌어야 하겠지요.

EvaluationTarget A의 평가 결과(상태?)가 바뀔 경우에 업데이트를 해줘야 한다는 생각에서 이렇게 로직을 짜봤어용.

혹여나 제가 이전 평가의 결과라는 말을 잘못이해했다면 코멘트 부탁해요 오구오구~오오구~

2020-09-28 10:06 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +                .filter { isNotCheater(it.id) }
맞아요. 그걸 눈치 채셨군요(?) 현재 로직에서는 부정행위자 필터링을 거친 지원자들만 넘어오기에 필요가 없는 라인입니다.

하지만 추후에 update를 호출하는 로직에서 부정행위자 필터링을 안하도록 수정될 수 있다고 생각하여 안전을 위해 중복작업을 해줬습니다.

제가 구현한 메서드의 중요도, 사용 빈도를 고려해서 성능보다는 안전성을 택했습니다.

이런 부분에 대한 코멘트 너무 좋아요. 제가 위의 3번에 달았던 부분의 연장선이라 생각해주시면 좋을 것 같아요.

제 혼자 생각이라 이 부분에 대해 현재 구현대로 픽스할건데 굳이 또 검사할 필요가 없다고 느낀다거나 성능에 초점을 더 맞춘다면 제외해도 될 것 같으니 의견을 말씀부탁드립니다.

2020-09-28 14:42 UTC, ddaaac commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +                .filter { isNotCheater(it.id) }
의도하신거라면 둬도 괜찮을 것 같네요 
꼼꼼함 좋네요 👍

2020-09-29 03:36 UTC, woowahan-pjs requested changes
수고 많으셨습니다. 👍 
변수 이름도 고민해 보세요.

2020-09-29 03:36 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        val evaluation: Evaluation =
헷갈리지 않는다면 지역 변수에 대한 자료형은 지정할 필요가 없다고 생각해요.

2020-09-29 03:36 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .filter { isNotCheater(it.id) }
모든 부정행위자를 처음부터 불러오면 어떨까요?

2020-09-29 03:36 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .filter { it.isSameStatusWith(PASS) }
'통과한 지원자'라는 명확한 도메인 언어가 있기 때문에 `isSameStatusWith()`보다 `isPassed`가 더 적절해 보여요.

2020-09-29 03:36 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        val deletingApplicantIds = persistApplicantIds subtract newApplicantIds
아래의 코드로 개선해 보면 어떨까요?

```suggestion
        val deletingApplicantIds = persistApplicantIds - newApplicantIds
```

2020-09-29 03:36 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +                .filter { isNotCheater(it.id) }
이 함수에서 부정행위자를 제외할 것이라고 생각하기 어렵네요. 이 함수를 호출하는 클라이언트를 믿고 제거해 봐요.

2020-09-29 03:36 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        evaluationTargetRepository.saveAll(additionalEvaluationTargets)
이전 평가를 통과한 지원자 목록을 불러오고 차이가 없으면 `update()`가 동작하지 않는 방법도 있겠어요.

2020-09-29 04:35 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .filter { isNotCheater(it.id) }
List형태로 캐싱을 해두고 포함되었는지 여부로 처리하는 편이 더 성능을 높힐 수 있겠군요.

2020-09-29 09:06 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        val deletingApplicantIds = persistApplicantIds subtract newApplicantIds
피드백을 반영하여 수정했습니다. 
가독성이 좋아지네요..!

2020-09-29 09:25 UTC, lalize commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        val deletingApplicantIds = persistApplicantIds subtract newApplicantIds
연산자 오버로딩 👍

2020-09-29 09:41 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .filter { it.isSameStatusWith(PASS) }
명확한 도메인 언어를 따라 객체가 행동을 수행하게 하라.

좋은 느낌입니다. 반영했습니다😀

2020-09-29 09:46 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        val evaluation: Evaluation =
지금과 같이 findByIdOrNull을 사용하거나, toSet을 사용하거나 map을 돌아서 나온 결과의 지역변수들에 대해서는 자명한 결과라 생각하여 자료형을 생각했습니다.

set정도는 적어줘도 될까 생각했지만 toSet으로 명시하니 괜찮다고 생각했습니다.

최대한 적어주자라고 생각했는데 프로퍼티 정도만 명시하는게 더 깔끔하네요. 

세심한 부분 고맙습니다 제이슨🤓

2020-09-29 11:26 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .filter { it.isSameStatusWith(PASS) }
아래의 글이 도움 될 거예요.
https://blog.kotlin-academy.com/kotlin-should-i-define-function-or-property-6786951da909

2020-09-29 13:12 UTC, toneyparky commented on src/test/kotlin/apply/application/EvaluationTargetServiceTest.kt
> +    private val evaluationTargetRepository: EvaluationTargetRepository
현재 테스트에서 update를 한 후 find를 해서 검증을 하기에 evaluationTargetRepository은 주입받아 사용하는게 더 나을거 같슴다!

2020-09-29 13:19 UTC, LTTTTTE commented on src/test/kotlin/apply/application/EvaluationTargetServiceTest.kt
> +    fun `이전 평가가 있고 저장 된 평가 대상자가 있을 경우 갱신하고 불러온다`() {
그렇군요 이해했습니다! 제 무지때문에 토니 손가락이 고생했네요😛

2020-09-29 13:54 UTC, woowahan-pjs requested changes
수고 많으셨습니다. 👍 
부정행위자가 더 많은 경우의 수를 만들고 있네요.

2020-09-29 13:54 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +    fun update(evaluationId: Long) {
불러오기 기능이므로 'load'가 적절하지 않을까요?

2020-09-29 13:54 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        val cachedCheaterApplicantIds = cheaterRepository.findAll().map { it.applicantId }
변수 이름이 길어지고 있어요.

```suggestion
        val cheaterApplicantIds = cheaterRepository.findAll().map { it.applicantId }
```

2020-09-29 13:54 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        }
if식으로 변경하면 어떨까요?

```suggestion
        if (evaluation.hasBeforeEvaluation()) {
            updateEvaluationTarget(evaluation, cachedCheaterApplicantIds)
        } else {
            updateEvaluationTargetOfFirst(evaluation, cachedCheaterApplicantIds)
        }
```

2020-09-29 13:54 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .filter { !cachedCheaterApplicantIds.contains(it) }
`(oldApplicantIds + newApplicantIds).filter { cachedCheaterApplicantIds.contains(it) }`가 있음에도 필터링할 이유가 있나요?

2020-09-29 13:54 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        if (isAlreadyUpToDate(oldApplicantIds, cheaterApplicantIds, newApplicantIds)) {
`cheaterApplicantIds`를 넘겨야 하는 이유는 무엇일까요?

2020-09-29 13:54 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            newNormalApplicantIds.containsAll(oldNormalApplicantIds)
아래의 코드로 개선해 보면 어떨까요?

```suggestion
        return oldNormalApplicantIds == newNormalApplicantIds
```

2020-09-29 13:54 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .toSet()
중복 코드를 메서드로 분리합니다.

2020-09-29 13:54 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +    }
코드가 `updateEvaluationTargetOfFirst()`와 동일하게 보이는 건 제 착각인가요? `createEvaluationTargetsFromFirst()`와 `createEvaluationTargetsFrom()`의 차이라면 `updateEvaluationTarget()`에 전달하는 인자로 차이를 만들어 보는 건 어떨까요?

2020-09-29 13:57 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        val cachedCheaterApplicantIds = cheaterRepository.findAll().map { it.applicantId }
`EvaluationTargetService` 내에서 `cheaterIds`도 납득이 가는데 다른 사람들은 어떻게 생각할까요?

2020-09-29 14:14 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +    fun update(evaluationId: Long) {
기존 load 메서드에서 생성과 삭제 그리고 조회까지 많은 역할이 부여되었다고 생각하여 리턴 값을 제거하였기에 기존 메서드 자체로 불러오기라는 행위를 수행할 수 없다고 판단하여 update로 메서드 명을 수정하였습니다.

해당 api로 요청이 오게되면 컨트롤러의 메서드에서 update로 갱신하고 findByEvaluationId로 조회하는 행위를 합쳐 불러오기라는 행위를 수행할 수 있다고 생각했는데 어떻게 생각하시나요?

2020-09-29 14:15 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        }
이 부분은 수정하는게 훨씬 가독성이 올라가겠네요. 

기존 네개의 분기에서 두개로 나뉘며 처리해줬어야 했는데 놓친 부분입니다😂

바로 반영할게요!

감사합니다~

2020-09-29 14:36 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +    fun update(evaluationId: Long) {
프런트 엔드는 불러오기 기능을 호출한 뒤 페이지 새로 고침을 하겠네요. 'load'는 '적재하다'라는 뜻도 있어 반환 값이 없어도 될 것 같아요.

2020-09-29 14:36 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            newNormalApplicantIds.containsAll(oldNormalApplicantIds)
이 부분을 학습테스트로 처리해봤을 때에 돌아가지 않아서 저렇게 구현했었는데, 제이슨이 피드백 남겨주신 부분을 확인하고 다시 테스트를 해보니 돌아가는군요😇

==를 이용해서 비교하도록 하겠습니다.

2020-09-29 14:47 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +    }
요걸 분리하니 에초에 4개로 분기가 나눠져있던 부분에서 2개로 분기를 나눴던 부분도 사그라지네요. 

더 리팩진행해보겠습니다😬

2020-09-29 14:48 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            newNormalApplicantIds.containsAll(oldNormalApplicantIds)
`List`와 `Set`의 차이일 것 같아요.

2020-09-29 14:50 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .toSet()
분리합니다 실시~!

2020-09-29 14:51 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .toSet()
아래 코멘트를 반영하니 하나로 묶이며 분리할 필요가 없어졌군요..😂

2020-09-29 15:58 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +    fun update(evaluationId: Long) {
그런 흐름이라면 완벽하게 이해가 되는군요.

프론트에서 새로고침을 한다고 생각하지 못했던 점과 load를 불러오기로만 생각하여 뭔가 값을 내어놔야 한다고 생각했기에 update를 주장했었지만 제이슨의 의견에 동의하여 load로 수정하도록 하겠습니다..!

감사합니다😀👍

2020-09-29 16:01 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        val cachedCheaterApplicantIds = cheaterRepository.findAll().map { it.applicantId }
기존 코드에서는 여러 곳에서 사용하기에 cached를 붙였으나 리팩토링 과정에서 제외되어 수정하였습니다. 

당시 cached를 붙였던이유는 클래스 내의 다른 곳에서 cheaterApplicantIds를 사용하기 때문이었지만 리팩토링 과정에서 그런 내용이 사라졌기에 없는게 이해하기 쉬운 변수명이라 생각합니다🙂

2020-09-29 16:06 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            newNormalApplicantIds.containsAll(oldNormalApplicantIds)
이번 pr의 Enum Equals와 == 비교부터 지금까지를 보아하니, 코틀린의 기본을 깊게 공부해야겠습니다!

2020-09-29 16:21 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .filter { !cachedCheaterApplicantIds.contains(it) }
중복으로 처리를 해줬었네요. 
좋지 못한 처리라고 생각합니다.
이 부분을 제거한다면 아래 코멘트에서 cheaterApplicantIds를 넘기지 않아도 된다 생각합니다.

2020-09-29 16:22 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        if (isAlreadyUpToDate(oldApplicantIds, cheaterApplicantIds, newApplicantIds)) {
`oldApplicantIds`는 부정행위자 처리를 하지 않고, `newApplicantIds`는 해줘서 발생한 차이 때문에 넘겼었네요. 
다만 위에서 답변을 남겼듯, 중복된 필터링을 제거한다면 넘길 필요가 없습니다.

2020-09-29 16:49 UTC, ddaaac approved these changes
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 

따봉이 아깝지 않은 코드네요! 복잡한 로직 구현하시느라 고생 많았습니다
과정을 지켜보는 제가 더 신났던 것 같아요 😄 

저는 이만하면 충분하다고 생각해서 어프루브 드릴게요~

2020-09-29 16:49 UTC, ddaaac commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +                save(updatingApplicantIds, currentApplicantIds, evaluation)
`val newlyAddedApplicantIds = updatingApplicantIds - currentApplicantIds` 와 같은 변수를 만들면 `save` 메서드에 이 변수만 넘겨도 될 것 같아요.
지금은 동일한 차집합 연산을 두번 반복하네요

2020-09-29 23:10 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +                save(updatingApplicantIds, currentApplicantIds, evaluation)
오호라 일어나서 보니 안보이는 부분이 보이는군요
변수 명도 너무 좋네요. 

반영해볼게요.
늦은 시간에 리뷰해주셔서 고마워요😬

2020-09-29 23:26 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .filter { it.isSameStatusWith(PASS) }
궁금한 점이 있습니다..!
제이슨은 레퍼런스 글을 어떻게 관리하시나요??

notion clipper를 사용하시려나요. 구글 독스?! 즐겨찾기 혹은 taggle...?😀

2020-09-29 23:33 UTC, woowahan-pjs requested changes
수고 많으셨습니다. 👍 
코드 디테일을 다듬었습니다.

2020-09-29 23:33 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            createUpdatingEvaluationTargets(evaluation).filter { !cheaterApplicantIds.contains(it.applicantId) }
아래의 코드로 개선해 보면 어떨까요?

```suggestion
            createUpdatingEvaluationTargets(evaluation).filterNot { cheaterApplicantIds.contains(it.applicantId) }
```

2020-09-29 23:33 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        if (isSavedBefore) {
if식을 삭제해도 될 거예요. 삭제 전후의 쿼리에 차이가 있는지 확인해 주실래요?
https://github.com/woowacourse/service-apply/issues/89#issuecomment-700736252

2020-09-29 23:33 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +    private fun createEvaluationTargetsFromFirst(evaluation: Evaluation): List<EvaluationTarget> {
전체 함수 이름에서 'From'을 삭제하거나, 'FromRecruitment'는 어떨까요? 아래 코멘트에 대해 고민해 봐요.
https://github.com/woowacourse/service-apply/pull/91#discussion_r496357024

2020-09-29 23:35 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            createUpdatingEvaluationTargets(evaluation).filter { !cheaterApplicantIds.contains(it.applicantId) }
그쵸 코틀린에 없을 리가 없군요..😂

처리하겠슴니다.

2020-09-29 23:37 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            newNormalApplicantIds.containsAll(oldNormalApplicantIds)
위의 동작들은 Java에도 적용됩니다. 참고로 코틀린의 `==`는 Java의 `equals`와 동일하고 코틀린의 `===`는 Java의 `==`와 동일합니다.

2020-09-30 00:00 UTC, woowahan-pjs requested changes
거의 다 왔어요. 👍

2020-09-30 00:16 UTC, woowahan-pjs commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .filter { it.isSameStatusWith(PASS) }
키워드를 기억해 두고 매번 검색합니다...

2020-09-30 00:25 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +        if (isSavedBefore) {
삭제하기 전이 오히려 isSavedBefore를 위해 select문이 한 번 더 찍히는 일이 발생하는군요.

2020-09-30 00:25 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .filter { it.isSameStatusWith(PASS) }
앗......

2020-09-30 00:26 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            .filter { it.isSameStatusWith(PASS) }
ㅋㅋㅋㅋ 감사합니다

2020-09-30 00:30 UTC, toneyparky commented on src/test/kotlin/apply/application/EvaluationTargetServiceTest.kt
> +    fun `이전 평가가 있고 저장 된 평가 대상자가 있을 경우 갱신하고 불러온다`() {
앜ㅋㅋ 아녀용 저도 테스트 코드를 다시 복기하고 좋아씀다

2020-09-30 00:48 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +    private fun save(newlyAddedApplicantIds: Set<Long>, evaluation: Evaluation) {
맞네요. 놓쳤습니다. applicantIds로 수정했습니다🙂

2020-09-30 00:56 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +            if (newlyAddedApplicantIds.isNotEmpty()) {
삭제하였고 체크하는 도중에 위의 delete 메서드를 잘못 사용하고 있는 것을 발견하여 수정하였습니다.
테스트코드 보완 예정입니다.

2020-09-30 00:57 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +    private fun createEvaluationTargetsFromFirst(evaluation: Evaluation): List<EvaluationTarget> {
두 메서드를 아래와 같이 수정했습니다.

createEvaluationTargets
createEvaluationTargetsFromRecruitment

target이 gitignore에 걸리는 바람에 메서드와 변수 명이 전체적으로 길어지는군요 😇

2020-09-30 03:47 UTC, dks301 reviewed
재미있어 보여서 한 발 담궈봅니다... 😄

2020-09-30 03:47 UTC, dks301 commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +    private val evaluationRepository: EvaluationRepository,
`Collection<EvaluationTarget>` 이 많이 보이는데요...!
일급 컬렉션 `EvalutationTargets`를 만들어서 사용하면 서비스를 더 간결하게 가져갈 수 있지 않을까요?

2020-09-30 03:50 UTC, toneyparky commented on src/main/kotlin/apply/application/EvaluationTargetService.kt
> +    private val evaluationRepository: EvaluationRepository,
묵직하네요 😀

2020-09-30 04:08 UTC, dks301 approved these changes
정말 고생하셨습니다 👍 👍 
시간관계상 일급컬렉션은 다음기회에... ㅋㅋ

2020-09-30 04:08 UTC, LTTTTTE approved these changes
테스트코드부분 마지막으로 한번봤습니다!👍🏼

2020-09-30 04:44 UTC, woowahan-pjs approved these changes
수고 많으셨습니다. 💯 
6개월이 지나도 1년이 지나도 읽을 수 있는 코드가 되었네요.

2020-09-30 04:48 UTC, merged